### ISSUE TITLE
Geocoding alternative

### ISSUE THREAD

**Issue by bkjohnson** [OneBusAway/onebusaway-android#1019]
**Summary:** 

The [blog post](https://onebusaway.org/trip-planning-on-android-phone-turned-off-for-now/) about trip planning being turned off says:

> **What’s next** – We are working on finding an alternative to Google’s Places API geocoding service, which converts street addresses into machine-readable latitude/longitude coordinates.

#### Nominatim

Has [nominatim](https://nominatim.openstreetmap.org/) been considered?  Some potential issues here:
- incomplete/outdated OSM data compared to Google
- limited to [1 request per second](https://operations.osmfoundation.org/policies/nominatim/)

If the request limit is an issue then you could [self-host an instance](http://nominatim.org/release-docs/latest/admin/Installation/)

**Comment by barbeau** [comment]
@bkjohnson Thanks for opening this!  Yes, Nominatim is an option, although we're currently looking closely at Pelias:
https://github.com/pelias/pelias

Pelias has been used successfully by TriMet in Portland, OR for transit geocoding, including some custom configuration to allow for searching for stop ID, etc. There are also hosted instances of Pelias that provide non-profits discounts (e.g., [GeocodeEarth](https://geocode.earth/)).

I've started working on an implementation here:
https://github.com/OneBusAway/onebusaway-android/pull/1018

**Comment by bkjohnson** [comment]
Thanks for letting me know!  Pelias looks pretty interesting.

**Comment by barbeau** [comment]
I'm going to use this issue to capture a few other options that others have suggested too:
* Microsoft Bing REST APIs (with non-profit discount) - https://docs.microsoft.com/en-us/bingmaps/rest-services/

**Comment by barbeau** [comment]
Support for Pelias as the default trip planning geocoder is now implemented in https://github.com/OneBusAway/onebusaway-android/pull/1018.

We're still doing testing to evaluate it as a replacement, and we still need to figure out how to pay for it :). So it won't be immediately deployed. But the software now exists!
