### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#1022]
**Summary:** 

From a user:

>I would like to see a dark/night mode for the app.Having  another color other than white in the background is nice. Especially if your trying to be discreet on the phone.

I agree, dark mode would be nice!

**Steps to reproduce:** 

Try to enable dark mode in the app

**Expected behavior:** 

Give me a dark mode option

**Observed behavior:** 

No dark mode option exists

**Comment by aaronbrethorst** [comment]
This has been fixed.
