### ISSUE TITLE
Arrival notification stalls after about 25 minutes

### ISSUE THREAD

**Issue by bcroup** [OneBusAway/onebusaway-android#1040]
**Summary:** 

After setting up a 30 minute reminder, the notification appears as expected and updates with the new arrival time about every 60 seconds, however it stalls and stops updating after about 25 minutes.

**Steps to reproduce:** 

I've been able to reproduce this pretty consistently on two android phones. Create a 30 minute reminder for an arrival. Once the arrival notification appears do not close it by swiping it away or by tapping it. Every minute or so, the notification will update with the latest arrival time. After about 25 minutes the notification will stop updating and a second notification will appear that says "Updating your reminders - Setting up your reminders". Both of these notifications will stay in your notification area indefinitely until you close out the stalled arrival notification.

**Expected behavior:** 

Like the 10 minute, 20 minute, and 25 minute reminder time notices, I would expect this notice to continue to update until the bus arrives. 

**Observed behavior:** 

Once the arrival notification appears the notification will update with the latest arrival time every minute or so for about 25 minutes. After that the notification will stop updating and a second notification will appear that says "Updating your reminders - Setting up your reminders". Both of these notifications will stay in your notification area indefinitely until you close out the stalled arrival notification.

**Device and Android version:** 

Issue occurs on a Samsung Galaxy S9 (non-rooted) running Android 10. Google Play Services is version 20.15.16
Issue also occurs on a Pixel 2 XL (rooted) running Android 10. Google Play Services is version 20.15.16

**Screenshots:** 

![Screenshot_20200430-164528](https://user-images.githubusercontent.com/34462181/81734699-c14fa580-9448-11ea-8a9c-4a62727be90f.png)

**Comment by barbeau** [comment]
I'm able to reproduce this as well using 2.10.0 release on Samsung Galaxy S21+ with Android 12, although I don't yet know why it happens...

**Comment by amrhossamdev** [comment]
Fixed: #1258
