### ISSUE TITLE
Update background location permissions for Android 11

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#1046]
**Summary:** 

As described here, the process to access background location has changed in Android 11:
https://developer.android.com/about/versions/11/privacy/location#change-details

These changes happen on Android 11 even if we haven't updated the app to target Android 11.

Background location is only used in one place in OBA Android right now, being entirely opt-in:
1. Travel behavior data collection for research studies - if the user goes through the informed consent process to join a research study and voluntarily contribute their travel behavior data, the location of activity transitions is captured in the background.

It looks like a new permission process is required to support background location access that needs to be followed when the user enrolls in the study.

Related to background location permissions based on `targetSdkVersion` as mentioned in https://github.com/OneBusAway/onebusaway-android/issues/1015.

(Note that destination reminders, activated by long-pressing on stop in status view and saying yes to "Do you want to be reminded when approaching this stop?", aren't considered background location. They fall under the navigation category of [foreground location](https://developer.android.com/training/location/permissions#foreground).)

**Steps to reproduce:** 

Follow the "Would you like to help improve transit?" dialog series to complete the informed consent documentation and enroll in the research study

**Expected behavior:** 

On Android 11 devices, follow the new process to request background location access

**Observed behavior:** 

The process isn't any different on Android 11 than previous Android versions

**Device and Android version:** 

Android 11

**Comment by mds08011** [comment]
Is background location required to be enrolled in the study?  I was under the impression that the study is tracking users only while they use the app.

**Comment by barbeau** [comment]
@mds08011 Good question. Right now we're not enforcing any location requirements to be part of the study - so users could turn off location entirely, in which case we would get activity transitions and timestamp data but no location information to go along with that.

The user's location is only collected at the point in time when an activity transition happens (e.g., from WALKING->IN_VEHICLE) to avoid negative impacts on battery life (i.e., we're not doing breadcrumb trail tracking) - activity transitions can occur when the app isn't in the foreground. My understanding is that currently we're not getting any location data on Android 11 until we update to the new background location permission requirements for Android 11 as mentioned above.

More information about the data collection software and methodology is in the final report for the project that funded the initial implementation here if you're interested:
https://scholarcommons.usf.edu/cutr_nctr/13/

**Comment by barbeau** [comment]
This is closed by https://github.com/OneBusAway/onebusaway-android/pull/1061, tested on Pixel 5 with Android 11. Android takes care of this automatically and prompts for background access with a link to system settings where the user needs to enable it.
