### ISSUE TITLE
Add epilepsy warning before night light activation 

### ISSUE THREAD

**Issue by Elyanne** [OneBusAway/onebusaway-android#1052]
**Summary:** 

The android application doesn't show a warning for flashing lights before activating the night light function. This could be a nice feature to insert for people with photosensitive epilepsy.
Flashing or flickering lights or images between 3 and 60 hertz (flashes per second) could cause an epilepsy attack in people affected by this kind of epilepsy, so make sure the night light function respects this.

**Comment by barbeau** [comment]
Thanks @Elyanne! I'll see if I can squeeze some additional text about this in the next release.

**Comment by barbeau** [comment]
In the next release, an epilepsy warning will now appear in the message that is shown for the Night Light feature before it starts flashing. A new option "Cancel" will also appear that let's you go back without starting the flashing lights. A screenshot is below. Thanks again @Elyanne for the feedback!

![image](https://user-images.githubusercontent.com/928045/109071575-e5236580-76c1-11eb-87a4-43d75d90822e.png)
