### ISSUE TITLE
Removed stop still shown (San Diego MTS)

### ISSUE THREAD

**Issue by mds08011** [OneBusAway/onebusaway-android#1055]
**Disclaimer:**
This pertains to a source data issue, not necessarily a bug in the app itself.  I am reporting this on Github because I received an error when attempting to report through the app's built-in feedback (#1054) but please let me know if there is a more appropriate channel.

**Summary:** 

A San Diego MTS bus stop was previously removed (mid-2019?) but the stop still shows in OneBusAway.  The stop is shown in the main map, trip/route progress, and selecting the stop shows ETAs for buses that will not actually be stopping.  Google Maps also show this erroneous stop, so perhaps the issue is stemming from GTFS data?  I can confirm that on November 18, 2020 there are no poles, signs, or anything else at the location shown on the map.
- *Stop number*: 99191
- *Stop Location*: Viewridge Avenue and Balboa Avenue (East Bound)
- *Bus Route*: 60

**Screenshots:** 

<img src="https://user-images.githubusercontent.com/8010709/99773939-015fa700-2ac2-11eb-84fc-4c972825cd8d.jpeg" width="50%">

<img src="https://user-images.githubusercontent.com/8010709/99773936-00c71080-2ac2-11eb-93a3-40f2afb78ce4.jpeg" width="50%">

**Comment by barbeau** [comment]
@mds08011 Thanks for the report! If the in-app issue reporting is having problems, the next best approach would be to do in main navigation drawer "Send feedback->Contact Customer Service", which should lead you to the helpdesk@sdmts.com option for SDMTS.

cc @devinbraun

**Comment by mds08011** [comment]
I contacted MTS and both OBA and the MTS website have been corrected. Thank you!

**Comment by barbeau** [comment]
@mds08011 Glad it's fixed!
