### ISSUE TITLE
Add trip short name to trip view (on map or list view)

### ISSUE THREAD

**Issue by wkulesza** [OneBusAway/onebusaway-android#1056]
**Summary:** 
When viewing trip details (be it map view or list view), it would be handy to include trip short name (if agency uses it).
In some cases, trips follow different trip patterns (i.e. are shorter and head earlier to depot or are longer and pass through additional stops). If trip short name is provided in GTFS, it could be displayed alongside vehicle id.

**Screenshots:** 
Below is a suggested screenshot, based on purely fictional data.

http://prntscr.com/vt4rwc

**Comment by barbeau** [comment]
@wkulesza @devinbraun Do you have an example of a trip that has a trip short name in San Diego?

I've implemented this in https://github.com/OneBusAway/onebusaway-android/pull/1063 but can't easily find any trips with short names to test.

**Comment by barbeau** [comment]
Nevermind, I actually found an example in Puget Sound:

![image](https://user-images.githubusercontent.com/928045/110695890-685fb380-81b8-11eb-9d06-77b64fb6f8f3.png)
