### ISSUE TITLE
Add timestamp to the activity-transitions document

### ISSUE THREAD

**Issue by welozano** [OneBusAway/onebusaway-android#1062]
**Summary:** 

In order to activate a filter by activity start time on the trevel-behavior-analysis tool, it is necessary to at least have access to the activity start time as a field on the document. Suggested field names are: systemClockCurrentTimeMillis and systemClockElapsedRealtimeNanos.

**Comment by barbeau** [comment]
Another note from discussion between @welozano and I offline:

>In the export tool, the getActivityStartTime method is currently using the eventTimeMillis from the first element of the array.

**Comment by barbeau** [comment]
If we're just copying the timestamp from first activity, we don't need the nanos timestamp, just the "eventTimeMillis" timestamp. The eventTimeMillis is calculated using the event nanos timestamp, and the nanos timestamp doesn't mean anything outside of the device (it's just a monotonically increasing value that starts at boot and increments per nanosecond - but isn't a wall clock time).
