### ISSUE TITLE
Adding Italian localization

### ISSUE THREAD

**Issue by Elyanne** [OneBusAway/onebusaway-android#1077]
**Summary:** 

I translated the app in Italian and I would like to add it to the project.
I've already tested it on android studio and I prepared the values-it folder with the strings and arrays files to add to the main project. 

If you want to insert my name in the credits (I'd really appreciate that :)) my name is Eleonora Fabbri, and I translated this with the help of Paola Poletti.

[values-it.zip](https://github.com/OneBusAway/onebusaway-android/files/6787013/values-it.zip)

**Comment by barbeau** [comment]
Thanks @Elyanne! I'll try to take a look at this soon. If you're able to put this into a GitHub pull request, including adding both your name to the credits, that would help speed things along.

**Comment by Elyanne** [comment]
I created the pull request and added the names to the credits, thank you!

**Comment by barbeau** [comment]
Thanks @Elyanne!
