### ISSUE TITLE
User Bug Report: Notifications and reminders of bus arrivals have stopped working

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-android#1106]
From a user:

> Hello,
> 
> First of all thank you for the app - it's super helpful for me, who uses public transport in King county everyday!
> 
> With the latest update of the app, notifications and reminders of bus arrivals have stopped working.
> The option to enable notifications in the system settings is disabled and locked - I am just not able to enable it. I see the message - "At your request Android is blocking notifications from this app on your device."
> 
> Device OS: Android 13 Nov 2023 update
> Device: Moto G stylus 2022
> 
> Could you please look into this and fix it?
> The app notifications were super useful for me.
> 
> Not sure if related but on googling for the symptoms found information that mentions that for Android 13 changes the opt-out model of notifications to opt-in model of notifications.

The latest versions of Android have made changes to permissions around exact alarms and notifications. We need to ask for new permissions.

**Comment by millanp** [comment]
I'll check this out!
