### ISSUE TITLE
Visibility Issue: Circular Progress Loader Color Blend with Header Background

### ISSUE THREAD

**Issue by sebesti0n** [OneBusAway/onebusaway-android#1115]
**Summary:** 

The Circular Progress Loader color blends with the header background, making it difficult to see.

**Steps to reproduce:** 

Step 1:Star a Route.
Step 2:Open Starred Route.
Step 3:View Circular Loader in the top-left corner.

**Expected behavior:** 

The Circular Progress Loader should have a contrasting color with the background for clear visibility.

**Observed behavior:** 

At times, the screen appears frozen due to the similarity in color between the progress bar loader and the background.

**Device and Android version:** 

Xiaomi 11i running Android 13 with the latest version of Google Play Services.

**Screenshots:** 
![Screenshot_2024-02-24-09-02-25-782_com joulespersecond seattlebusbot](https://github.com/OneBusAway/onebusaway-android/assets/114914556/0eed4da0-d040-4802-ac73-b92ae986dbfc)

I'm currently Working on this issue.

**Comment by safatdroid** [comment]
hey @sebesti0n i want to work on this issue please assign me this issue
