### ISSUE TITLE
Crashes on clicking news/situations/alerts on stops. 

### ISSUE THREAD

**Issue by Samuel-Aktar-Laskar** [OneBusAway/onebusaway-android#1149]
**Summary:** 

When I click on situations or news on any stop, sometimes it crashes. 
**Steps to reproduce:** 

Click on any stop. Click on news items. Sometime, it crashes. 

https://github.com/OneBusAway/onebusaway-android/assets/83684042/6c722f9f-8f63-4551-9748-92d8cbe01b79

**Comment by Samuel-Aktar-Laskar** [comment]
I have solved the issue. In the SitutionDialogFragment, the getStringI() method of Bundle throws NullPointerException. In case description is not available, it throws NullPointerException causing it to crash. 
I just added null checks for it. I am raising PR for it.

**Comment by amrhossamdev** [comment]
Fixed.
