### ISSUE TITLE
Activity is restarted on orientation

### ISSUE THREAD

**Issue by gourabsingha1** [OneBusAway/onebusaway-android#1153]
**Summary:** 

When I switch from portrait to landscape mode and vice versa, the activity is restarted giving a bad UX.
This happens in almost all activities.
Also, during this process, the map is filled with blue when a route is shown.
Plus the route detail which shows on top, follows with switching activities from any one activity to any other activity of the first 4 activities on navigation drawer.

**Steps to reproduce:** 

Switch from portrait to landscape mode and vice versa.

**Expected behavior:** 
Activity should not restart. Map shouldn't turn blue. Route detail shouldn't follow.

**Observed behavior:** 

Described above.

**Screenshots:** 

https://github.com/OneBusAway/onebusaway-android/assets/110812339/b7ffbfc4-4474-4fdd-9c61-0a94efac9bbc

**Comment by amrhossamdev** [comment]
I think this is completed
