### ISSUE TITLE
Vehicle labels bounce around vehicle icon when selected on map

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-android#1155]
**Summary:** 

The vehicle information label bounces around the vehicle icon after being selected on the map.

**Steps to reproduce:** 

Click on any stop with real-time arrivals.  Click the three vertical dots on an arrival to see the context menu and select "Show route on map".  Find a vehicle icon on the route and click on it.  The information label will open up and bounce around.

**Expected behavior:** 

The label should not bounce around the vehicle icon.

**Observed behavior:** 

The label bounces around the vehicle icon.

**Device and Android version:** 

Pixel 8 Pro
Android Beta 14 AP21.240216.010
OBA 2.12.1

**Screenshots:** 

[See video](https://drive.google.com/file/d/1Te1UVI27ZkjazUYRRQRF1bihpn8eNUO8/view?usp=sharing)

**Comment by aaronbrethorst** [comment]
@devinbraun that's annoying! we'll get that fixed asap

**Comment by amrhossamdev** [comment]
investigating now.

**Comment by aaronbrethorst** [comment]
@devinbraun This has been fixed and I'll be cutting a new build soon to get it into the Play Store. (thank you @amrhossamdev!)
