### ISSUE TITLE
Crashes on clicking temporary detour

### ISSUE THREAD

**Issue by gourabsingha1** [OneBusAway/onebusaway-android#1157]
**Summary:** 

App crashes on clicking temporary detour. Refer to the screenshot below for clear understanding.

**Steps to reproduce:** 

Select any stop which shows arrivals list. Click on temporary detour.

**Device and Android version:** 

Asus Zenfone Max pro M1, Android Pie
Pixel 7 pro API 34

**Screenshots:** 

![IMG_20240310_122750_550~2](https://github.com/OneBusAway/onebusaway-android/assets/110812339/9b639a85-2863-4c1f-8ee4-70f1d5777de2)

**Comment by amrhossamdev** [comment]
Thank you for finding that, I worked on this dialog before adding an html parser we need to check if we have a non-null description for the alert because a crash happen when the parser parsing a null, I will submit a fix.
