### ISSUE TITLE
User Reported Bug: Plan Trip Time Picker looks broken in dark mode

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-android#1180]
> Hi,
> 
> Thanks for this app. I would like to report that the plan trip time picker doesn't work correctly on dark mode, see attachment.

![image](https://github.com/OneBusAway/onebusaway-android/assets/2254/801636e7-ac9d-4b84-aabc-7c9febd30e9f)

**Comment by amrhossamdev** [comment]
I can work on this.
