### ISSUE TITLE
User reported bug: "Updating your reminders" notification pops up from time to time

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-android#1183]
> Is there a way to o get rid of the "updating reminders" notifications? They seem to pop up randomly. I went in to the android notification manager but didn't see anything about these notifications. Couldn't find any notification settings in Onebus settings. 
> 
> App Version: 2.12.2
> Model: Pixel 6a
> OS Version: 14 / 34
> Google Play Services App: 24.08.12 (190400-608507424)
> Google Play Services Library: 12451000
> Region/API: Puget Sound (selected automatically)

![Screenshot_20240318-082243](https://github.com/OneBusAway/onebusaway-android/assets/2254/60a7a7ca-9090-4ae5-94ce-151b71c929a4)
![Screenshot_20240318-082444](https://github.com/OneBusAway/onebusaway-android/assets/2254/003dbc44-3987-40ab-b207-164d76bdf3c1)

**Comment by 12sachingupta** [comment]
System Settings: 
In addition to the app's settings, check your device's system settings for notification management. On Android, you can usually access notification settings by going to Settings > Apps & notifications > Notifications. Look for the OneBusAway app in the list of installed apps and see if there are any options to customize its notifications.

Update the App:
 Make sure you're using the latest version of the OneBusAway app. Developers often address user feedback and issues like unwanted notifications in updates, so updating the app might resolve the problem.


#1183

**Comment by amrhossamdev** [comment]
Fixed: #1258
