### ISSUE TITLE
Donation Overlay close button is missing with larger font sizes

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-android#1199]
![Screenshot_20240412_102730_OneBusAway](https://github.com/OneBusAway/onebusaway-android/assets/2254/1d670d0f-edd6-4e37-a71e-f098729ee4a9)

**Comment by amrhossamdev** [comment]
I will submit a PR.

**Comment by aaronbrethorst** [comment]
@amrhossamdev thank you!
