### ISSUE TITLE
Add "Vehicle Info" option to provide arrival list/map for a single vehicle

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#120]
From a former OBA iPhone user:

> On the iPhone OneBusAway app, if you click on a specific bus's status, one of your choices is "Vehicle Info" which leads to a screen that shows the vehicle number (not the route number) and a list of times that the bus reached previous stops and is projected to reach future stops. This functionality is valuable for estimating when a specific bus -- say, the one my kid is on -- will reach a specific stop. I don't see how to access this functionality on the Android version.

If we want feature parity with OBA iPhone we should add this feature.

**Comment by bendu** [comment]
Is anyone working on this? I'm willing to volunteer some time to make this happen.

**Comment by barbeau** [comment]
@bendu Nope, feel free to give it a shot!  Any help is appreciated!  I would definitely work off the `develop` branch for this.

**Comment by bendu** [comment]
Thanks @barbeau

**Comment by bendu** [comment]
I've put together an arrivals list. I'm thinking of replacing "Show route information" with "Show trip details" in the arrivals list to enter this view since they provide nearly identical information except for the the route stops in the reverse trip.

It's been a while since I used OBA on iPhone, are the times displayed there the real time arrival times? The ones provided by the trip-details endpoint appear to be scheduled.

![tripdetails](https://cloud.githubusercontent.com/assets/5668844/9426302/a4b6f8b2-48ec-11e5-874a-62f73504532b.PNG)

![showrouteinformation](https://cloud.githubusercontent.com/assets/5668844/9426303/b764dd6c-48ec-11e5-801a-8c02648e8a49.PNG)

**Comment by bbodenmiller** [comment]
iPhone appears to be showing realtime but does not properly indicate that it is realtime:

![image](https://cloud.githubusercontent.com/assets/1192780/9426450/04ffdea0-48f7-11e5-9203-ca6a801a0058.jpg)
![image](https://cloud.githubusercontent.com/assets/1192780/9426452/0a53a396-48f7-11e5-830b-c2e96f797858.jpg)
![image](https://cloud.githubusercontent.com/assets/1192780/9426453/10855ca0-48f7-11e5-8724-457cd57acace.jpg)

**Comment by barbeau** [comment]
@bendu Looking good!  Thanks again for working on this.

@aaronbrethorst or @bbodenmiller can you confirm that "Trip Schedule" screen on iPhone is actually showing real-time info, and if so, that it's calculating them by applying the `scheduleDeviation` to the schedule times?

Here's an example of the API call that's being used:

http://api.tampa.onebusaway.org/api/where/trip-details/Hillsborough%20Area%20Regional%20Transit_98402.json?key=TEST

The [OBA trip-details docs](http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/elements/trip-details.html) say:

>Note that arrival and departure times are the scheduled times and do not reflect real-time arrival information, even if its available

So, the `schedule` element should be schedule (not real-time) values, and the `status` element should contain the real-time attributes for the vehicle/trip, including the `scheduleDeviation`.  So I believe the only simple way to calculate real-time values for all stops along the trip is to apply the `scheduleDeviation` to the scheduled times, unless I'm missing something.  Thinking ahead, this currently works for OBA because the internal server-side data model is based around a single deviation value for an entire trip, but we've been working lately on supporting GTFS-rt feeds that supply per-stop estimates as part of on-boarding another agency in Tampa.  In this case, applying the `scheduleDeviation` to the scheduled times downstream of the vehicle won't actually yield the same real-time value as if you pulled up that same stop in the arrivals view.  With that being said, if OBA iOS is calculating the real-time values this way for trip details, I'm ok with implementing the same in OBA Android for now, as it will still work for most of the agencies using OBA - we'll figure out the per-stop stuff later.

@bendu a few other comments:

* I'm ok with replacing "Show route information" with "Show trip details".  I'd still like to make the full route info activity accessible somewhere in the app where you can see both directions, but that can be TBD at this point.  The Transit App has a nice interface where you can swipe left/right to show the opposite direction, which might work well here, although off the top of my head I'm not sure how easy that is to accomplish given the APIs we currently have for OBA.  At any rate, I agree that trip details makes sense here.
* I'd prefer to remove the stop direction from this list as I think it only confuses things here.  Just stop name and time should be enough.
* Eventually I'd like to show a more graphic rendering of the stop sequence, something like:
![image](https://cloud.githubusercontent.com/assets/928045/9426542/d2a6e5ae-4917-11e5-860d-a33af1dea7db.png)

...but this can be a future enhancement, not necessary for this initial implementation.

**Comment by bendu** [comment]
I traced through the [source code](https://github.com/OneBusAway/onebusaway-iphone/blob/2c3de527342f672ab8f7fcfba59a9ba82ce14f64/ui/trip_details/OBATripScheduleListViewController.m#L318) for OBA-iphone. It appears that schedule deviation is being added on to the scheduled stop time.

@barbeau Thanks for the feedback. I will remove stop direction and put up a PR soon. I've been a bit busy lately so I haven't had the time to work on this.
The graphic is interesting, do you know of the library that produces it? I could take a look at it when I have more time.

**Comment by barbeau** [comment]
Cool!  Thanks for your work on this.  Above graphic is just a mockup I put together.  I think it can be accomplished with some XML shape drawables in the layout of the list item - its basically just a circle and line that's stylized based on the position of the element in the list.

It will be nice to get this feature into the app, another user just asked for it the other day.

**Comment by barbeau** [comment]
Fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/issues/120.
