### ISSUE TITLE
App dependencies need to be updated

### ISSUE THREAD

**Issue by amrhossamdev** [OneBusAway/onebusaway-android#1202]
**Summary:** 

A lot of dependencies need to be updated to ensure the app's performance and functionality

**Screenshots:** 

![image](https://github.com/OneBusAway/onebusaway-android/assets/29693819/e421b9af-7d2c-4618-8950-e4f0e422349f)

**Comment by aaronbrethorst** [comment]
I support this, but let’s focus on non-major version bumps and do them one at a time. Sent from my iPhoneOn Apr 13, 2024, at 9:45 AM, Amr Hossam ***@***.***> wrote:﻿
Summary:
A lot of dependencies need to be updated to ensure the app's performance and functionality
Screenshots:
image.png (view on web)

**Comment by amrhossamdev** [comment]
Yes, we can try to update every dependency in linear progress to ensure everything works because I think many libs updates will require refactoring to the codebase.

**Comment by dattasneha** [comment]
Hi @amrhossamdev, I would like to work on this issue. Please assign me.

**Comment by amrhossamdev** [comment]
Hi @dattasneha, I'm actually working on this. Feel free to check our issues list and tackle any issue you can solve!
