### ISSUE TITLE
[BUG] Backup Storage Functionality Broken on Android 13 and Above - Storage Permissions

### ISSUE THREAD

**Issue by amrhossamdev** [OneBusAway/onebusaway-android#1212]
**Summary:** 

We got a report from a user with Android version `33` that he can't grant permissions for saving a backup in the storage, I started to investigate and I found that we use permissions `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` now replaced with `READ_MEDIA_IMAGES` and `READ_MEDIA_VIDEO` for higher android version from `API 33` and above. See [android docs](https://developer.android.com/training/data-storage/shared/media#storage-permission)

I tested this on my Android 13 emulator and can confirm it's broken.

**Useful discussion/articles:**

- [Storage Permission in Android 13](https://medium.com/@bilalzurmati/storage-permission-in-android-13-89372e543864#:~:text=Three%20new%20permission%20is%20introduced,permission%2C%20then%20all%20is%20good)
- [Stackoverflow](https://stackoverflow.com/questions/72948052/android-13-read-external-storage-permission-still-usable)
- [Ankidroid discussion](https://github.com/ankidroid/Anki-Android/issues/14423)

**Steps to reproduce:** 

1. Go to the settings 
2. Try to save a backup to storage

**Expected behavior:** 

Dialog pop-up asking for the permissions

**Observed behavior:** 

No dialog asking for permission

**Device and Android version:** 

Android Version:  13 - API 33

**Video** 

[Screencast from 04-28-2024 11:35:15 PM.webm](https://github.com/OneBusAway/onebusaway-android/assets/29693819/09abacb0-730e-4e67-8521-bfa09e0deb0f)

**Comment by david-allison** [comment]
(just caught the issue link, great timing!)

`READ_MEDIA_IMAGES` and `READ_MEDIA_VIDEO` are not going to be sufficient for your intention

You want to look into `ACTION_OPEN_DOCUMENT_TREE` to obtain permissions to write to a folder on external storage (incl. cloud providers).

Note that this uses a `androidx.documentfile.provider.DocumentFile`, but this should be sufficient for writing backups.

https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE

**Additional Reading**

CommonsWare has a great series on the Android 10/11 storage changes:

https://commonsware.com/blog/2019/10/19/scoped-storage-stories-saf-basics.html

Also see:

* https://developer.android.com/about/versions/11/privacy/storage
* https://source.android.com/docs/core/storage/scoped

**Comment by jackL999** [comment]
So what is the solution? To use adb to grant new permissions? 

I followed the instructions noted here https://github.com/ankidroid/Anki-Android/issues/14423#issuecomment-1777536234
and issued the commands 

adb shell pm grant com.ichi2.anki android.permission.WRITE_EXTERNAL_STORAGE
adb shell pm grant com.ichi2.anki android.permission.READ_EXTERNAL_STORAGE

Although that granted file permissions for version 2.17.6 on Android 33 it will not allow writing to any directory. On launching the app it states an error report is being generated and that the directory path is inaccessible. Upon changing it, I get the error "The path specified isn't a valid directory" regardless of what directory it's set to including resetting it to the default. 

Which version of AnkiDroid doesn't have these problems?
