### ISSUE TITLE
Warning icon overlaps with long route name

### ISSUE THREAD

**Issue by amrhossamdev** [OneBusAway/onebusaway-android#1219]
**Summary:** 

Warning icon overlaps with longer route names

**Steps to reproduce:** 

- Select Washington region 
- Click on any stops with long route names

**Expected behavior:** 

Should not overlap

**Observed behavior:** 

Overlaps happen 

**Device and Android version:** 

any device.

**Screenshots:** 

![image](https://github.com/OneBusAway/onebusaway-android/assets/29693819/4e7ea848-5d79-4b79-b710-09ce7a269ebb)

**Comment by amrhossamdev** [comment]
> @amrhossamdev Please Assign me. I will be working on this.

Go on!

**Comment by Shimork04** [comment]
What's the status? @Aditya13s

**Comment by aaronbrethorst** [comment]
@Aditya13s I have unassigned this ticket from you
