### ISSUE TITLE
No proper space between "Privacy Policy , Lisence and  Contact us" in the footer of website

### ISSUE THREAD

**Issue by Ayush307K** [OneBusAway/onebusaway-android#1224]
Summary:
There is insufficient spacing between the "Privacy Policy," "License," and "Contact Us" links in the footer of the website.

Steps to reproduce:

Navigate to the footer section of the website.
Observe the spacing between the "Privacy Policy," "License," and "Contact Us" links.
Expected behavior:
The links in the footer should have proper spacing between them to enhance readability and user experience.

Observed behavior:
The links "Privacy Policy," "License," and "Contact Us" are too close to each other, making it difficult to distinguish them clearly.

Device and Android version:
Not applicable (issue observed on a web browser).

<img width="1679" alt="Screenshot 2024-08-13 at 1 42 25 PM" src="https://github.com/user-attachments/assets/91af0878-5f1e-4f34-b8e7-b7b2531ab334">

**Comment by aaronbrethorst** [comment]
thanks for the report. I've fixed this.
