### ISSUE TITLE
Out of Area warning text is missing

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-android#1247]
While out of range of the set region, a message pops up that is supposed to say you are out of range of your home address, but the text is missing from the message. 

![Screenshot_20240912-113706](https://github.com/user-attachments/assets/3e3ddc11-2a75-41ae-96b6-0e4a8238d6aa)

**Comment by amrhossamdev** [comment]
Hi Devin thanks for reporting this.

can I have more information about your Android version and mobile name?

**Comment by devinbraun** [comment]
Pixel 8 Pro
Android 15

**Comment by amrhossamdev** [comment]
Thanks, Devin...

I will try to reproduce and test it on Android 15.

Thanks again really appreciate your time and efforts!
