### ISSUE TITLE
Add alert message on the map when a transit agency server or schedule update is delayed

### ISSUE THREAD

**Issue by amrhossamdev** [OneBusAway/onebusaway-android#1255]
We have received multiple reports from users stating that the app "no longer works" or that "no bus stops are showing up on the map." These issues often occur when a transit agency's server is down or when schedule updates are delayed, which are not within our app's control.

This issue recently affected schedules from agencies such as Sound Transit and InterCity Transit, who were working to resolve problems caused by delayed schedule updates.

To address this issue, we suggest adding an alert in the app to let users know when a transit agency's server is down when there are no stops available, or when there's a delay in getting and updating schedule information. This will help users understand what's happening and avoid confusion when information is missing.

By keeping users informed about server status, stop availability, or schedule delays, we can improve their experience and reduce frustration.

**Comment by aaronbrethorst** [comment]
FYI, this feature exists in the iOS app and is powered by onebusaway.co
