### ISSUE TITLE
[BUG] - Incorrect Styling for Situation Dialog Title

### ISSUE THREAD

**Issue by amrhossamdev** [OneBusAway/onebusaway-android#1264]
**Summary:** 

there is incorrect styling for the situation dialog title

**Screenshots:** 

![Screenshot_1728520917](https://github.com/user-attachments/assets/cd4751f6-5751-4197-81e0-a22592d99ab2)

**Comment by salehdemir** [comment]
If there is any bug I can solve it . would you assign me this issue.

**Comment by amrhossamdev** [comment]
Thank you, Saleh. A fix for this issue is already in place. Please check the issue section, and let me know if you'd like me to assign the tickets to you.

**Comment by salehdemir** [comment]
I like to work on it @amrhossamdev , assign it to me .

**Comment by amrhossamdev** [comment]
@salehdemir there is already a fix.
