### ISSUE TITLE
have to set in the path in readme 

### ISSUE THREAD

**Issue by SophiaLi20** [OneBusAway/onebusaway-android#1283]
In the permission section of readme the path as to why we the each permission needed is not found hence it displays the the 404-"file not found error" 
Below is the screenshot of how the page shows 
![Screenshot (69)](https://github.com/user-attachments/assets/2b0a12ec-2791-4db5-b35c-b44d029f86bd)

Have to fix the broken path so that it can display the condition of the permission that needed as it will be helpful for the developers

**Comment by vikasprajapati-01** [comment]
@SophiaLi20 I cannot locate the PERMISSIONS.md file. Does it exist?

**Comment by barbeau** [comment]
See https://github.com/OneBusAway/onebusaway-android/blob/main/PRIVACY.md

**Comment by aaronbrethorst** [comment]
thanks @barbeau and @SophiaLi20 fixed.
