### ISSUE TITLE
UI re-design

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#155]
As part of the current work I'm doing on OBA Android, I'd like to refresh the UI a bit to bring it in line with modern Android UI components/design (especially [the bottom sliding drawer](http://stackoverflow.com/questions/16680985/a-library-for-a-sliding-up-drawer-similar-to-new-google-music-and-rdio) used in apps such as Google Maps).  In particular, I'd like to make the main ways of viewing stops (Map, Favorites, Recent) more apparent, and reduce the taps and hard transitions (e.g., opening new Activities) needed to get from the map to the arrival times and route displays.

I've drafted an initial mock-up in [a Google Drawing](https://docs.google.com/drawings/d/1PdinaBVpNYaMg_-yvomHibOpCAiWzk33GwVLOv9APIY/).  The drawings are also shown below in-line for easier iterative review/comment.

Please provide feedback!!  These are considered a starting point for conversation.

![oba android ui mockup-default home](https://cloud.githubusercontent.com/assets/928045/3680894/d5e05f66-12b3-11e4-8859-27deff0b0539.png)

![oba android ui mockup-stop selected](https://cloud.githubusercontent.com/assets/928045/3680899/da325f24-12b3-11e4-94a5-c8c496d0f70a.png)

![oba android ui mockup-on menu key](https://cloud.githubusercontent.com/assets/928045/3680902/dcf809c0-12b3-11e4-8007-cf71c82b8fec.png)

**Comment by barbeau** [comment]
So here's a shot at a small pointy end on the circular stops to represent travel direction, but still using the red marker to denote the selected stop.  Largely inspired by how Google Maps represents orientation on the blue real-time location dot.  Thoughts?

![oba-circlestopmarkerwithdirection-50](https://cloud.githubusercontent.com/assets/928045/5671393/8d98747e-9755-11e4-9568-e4ca54e9fd48.png)

**Comment by caitbonnar** [comment]
@barbeau Definitely agree with @jrharshath about the directionality. The screenshot you just posted looks good. :-)

Sorry for not responding to your previous comment about contrast! The star outline is still a bit tough to distinguish, but everything else looks good!

**Comment by barbeau** [comment]
@caitbonnar Thanks!  Yes, I should have specified that I haven't touched the star or header organization yet - that will change a bit still based on past feedback.

**Comment by caitbonnar** [comment]
@barbeau Sounds good. :-) Looking forward to the final result!

**Comment by bbodenmiller** [comment]
With the new icon is there a way to differentiate bus stops from train
stops?

**Comment by barbeau** [comment]
@bbodenmiller We lose that ability on the map when changing to the simplified circular icon.  It's definitely a tradeoff - cleaner and simpler icons like the plain circle lose some information along the way.  I'm hoping, though, to somehow keep that info in the header.  For example, currently there is a bus icon representing the next bus arrival - it would be a train if the next arrival was a train.  I'm open to ideas as long as they stick within the current application flow.

**Comment by barbeau** [comment]
Another option to display different modes would be to enlarge the icon for train/rail stops.  Do you have  a stop ID that I could test this with in Puget Sound that has train/rail arrivals?  We only have bus in Tampa.

**Comment by bbodenmiller** [comment]
#455 has both bus & train. #99905 has just trains.

**Comment by barbeau** [comment]
Looking at the [REST API response](http://api.pugetsound.onebusaway.org/api/where/arrivals-and-departures-for-stop/1_99905.json?key=TEST) for stop 99905, "train" routes in Puget Sound have `type=0`:

~~~
agencyId: "40",
color: "",
description: "LINK to Sea-Tac",
id: "40_100479",
longName: "",
shortName: "LINK",
textColor: "",
type: 0,
url: "http://www.soundtransit.org/Schedules/ST-Express-Bus/599"
~~~

...and bus routes have `type=3`:

~~~
agencyId: "1",
color: "",
description: "Tukwila - E Marginal - CBD",
id: "1_100023",
longName: "",
shortName: "124",
textColor: "",
type: 3,
url: "http://metro.kingcounty.gov/schedules/124/n0.html"
~~~

So, "train" is classified under [GTFS route_type category](https://developers.google.com/transit/gtfs/reference#routes_fields) for:

>Tram, Streetcard, Light rail.  Any light rail or street level system within a metropolitan area.

**Comment by barbeau** [comment]
Hi all!  I've been able to get back to some of this UI work recently, and wanted to share what we currently have.  Thanks again to everyone that's provided feedback so far, it's definitely improved the design, IMHO.  

For this redesign, I want to stick to the main app flow that OBA users are familiar with, which is tapping on a bus stop icon to get information about that stop.  When you tap on a stop, a bottom panel slides in with the next arrivals for that stop.  You can then tap the expand/collapse indicator (or slide it up) to slide the panel up to reveal route details cards:

![image](https://cloud.githubusercontent.com/assets/928045/9283555/bcfe0f3c-42a2-11e5-8cbe-92dd85995f83.png)

You can continue to pull the panel up to scroll through all the route cards for that stop:

![image](https://cloud.githubusercontent.com/assets/928045/9283958/c2f90db2-42a5-11e5-876e-11db494034f5.png)

This redesign also introduces a new feature of being able to star route/destination by tapping on the star either in the header of the panel, or on the card.  When a route/destination is starred, it is pinned to the header.  A route/destination can be starred for all stops, or just specific stops (user is prompted when starring the route/destination).

Feedback is welcome!  Just please keep in mind that I'd like to stick with the same familiar OBA flow of tapping on a bus stop, and showing information for that stop in the header/sliding panel.  One design TODO here is how to indicate that the arrival time shown in the panel header is real-time or schedule information.  And a question - is the schedule vs. real-time distinction clear enough in the cards?

Also of note - for anyone really nostalgic for the OBA arrivals list with the color-coded arrival times, you can switch from the cards presentation back to the classic OBA look in the Settings.

The code for all this is in the `develop` branch (and PR https://github.com/OneBusAway/onebusaway-android/pull/177, which is identical to `develop`).  I plan to push this out as an alpha release late next week or early the following week, assuming we can get Google Analytics added to the new features by then (https://github.com/OneBusAway/onebusaway-android/issues/283).

So, if you'd like to get this alpha version via Google Play, please [sign up for alpha updates](https://github.com/OneBusAway/onebusaway-android/blob/master/BETA_TESTING.md#register-as-an-alpha-tester)!

cc @cagryInside

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by cagryInside** [comment]
@barbeau How does the alerts look like in the new UI design?

**Comment by barbeau** [comment]
@cagryInside I haven't tested this in a while, but they should look like the screenshots [here](https://play.google.com/store/apps/details?id=com.logictree.ontime), in terms of how they are presented in the sliding panel.  Tapping on them should open the alert in a new `SituationFragment`.  This is definitely something we should test further, though.

**Comment by jrharshath** [comment]
The RideTime screenshots sure look very similar to our OBA :)

**Comment by barbeau** [comment]
@jrharshath :)  Hopefully we'll see more rebranding implementations inside the main project now that we support white-labeling (https://github.com/OneBusAway/onebusaway-android/pull/252).

**Comment by cagryInside** [comment]
The ```my location``` button has shadow on Motorola Nexus 6:

![device-2015-08-18-103937](https://cloud.githubusercontent.com/assets/2777974/9333160/5553db86-4596-11e5-8aba-a56404f0fe4f.png)

**Comment by barbeau** [comment]
@cagryInside Thanks!  I've noticed this on my LG G4 too.  I'll take a look again at the design support library that this button comes from - there was a workaround you had to do in earlier versions of the support library to get the button to render properly on Gingerbread, which I believe is fixed now.  Maybe this workaround is now causing problems with the updated design support library.

**Comment by cagryInside** [comment]
@barbeau I have also noticed this on the ```Amazon firephone```, its a little bit different than the nexus device:

![device-2015-08-18-103937](https://cloud.githubusercontent.com/assets/2777974/9337226/1c654740-45ac-11e5-94a2-5e8db8d5cafd.png)

**Comment by barbeau** [comment]
Thanks!  Yeah, I think this shows up differently on Lollipop than previous API levels, IIRC.  IIRC the way its shown on Fire Phone is the way it appears on all non-Lollipop devices (and strangely, the main shadow there renders correctly).  I'll have to dig into this further...

**Comment by barbeau** [comment]
@cagryInside I believe the clipped/rectangular shadow for the MyLocation FAB on Lollipop should now be fixed in the `develop` branch, if you want to try that again on your Nexus 6.  I believe the non-Lollipop devices will still appear the same (or very similar) to the above Fire Phone screenshot.  I tested an HTC EVO Shift with Android 2.3.4, and the white circle appears all the way around the button, but slightly thicker at the bottom.  I think this is the best we can do - we're now using the official support library `android.support.design.widget.FloatingActionButton` without any workarounds and directly in the layout (i.e., without any unneeded parent layouts).

**Comment by barbeau** [comment]
I've been working on adding the red/green/blue indicators for early/ontime/late status to the new UI.

Here's how the cards currently look:
![image](https://cloud.githubusercontent.com/assets/928045/9766018/fa225156-56e4-11e5-9ddf-d788fb2d5b09.png)

I'm also trying to figure out a way to add it to the sliding panel header, but this one has been a little more difficult.  The goal is to allow users to easily see whether their starred routes shown in the header are early/ontime/late without having to pull up the panel.  Here are two possible implementations:

![image](https://cloud.githubusercontent.com/assets/928045/9766105/4ab122e6-56e5-11e5-87ec-f2c519753b25.png)

The little white dot has an expanding/contracting animation, which along with the color indicates real-time info.  

Tapping on the ETA will show a small popup window with the delay amount, something like:

![image](https://cloud.githubusercontent.com/assets/928045/9766350/63b1b872-56e6-11e5-870e-4c9787d50e68.png)

Preferences between the two header presentations?  Any other ideas for integrating the early/ontime/late color info into the header differently?

**Comment by bendu** [comment]
I've been using the re-designed UI on my phone over the past week or so and here is my feedback on the sliding panel header.

Swiping the panel header down out of the screen seems like an intuitive way to dismiss it, but the real way to dismiss is touching the map.
Showing the ETA in the popup window is nice, but tapping on the ETA a second time does not actually dismiss the popup.

**Comment by barbeau** [comment]
@bendu Thanks for the feedback!

>Showing the ETA in the popup window is nice, but tapping on the ETA a second time does not actually dismiss the popup.

Agreed, we should dismiss the popup on 2nd tap of ETA, as that's more intuitive - I just fixed that in https://github.com/OneBusAway/onebusaway-android/commit/4119bef080a1c60f3094a404af4d82e7e61e2c75 (and it was more complicated than it should have been).  `develop` branch should now have the desired behavior.

>Swiping the panel header down out of the screen seems like an intuitive way to dismiss it, but the real way to dismiss is touching the map.

We could potentially support a swipe down to hide the header.  We're using [a library](https://github.com/umano/AndroidSlidingUpPanel) for the sliding panel, so implementation could be tricky.  The other item to consider is that the other apps I'm aware of that feature a bottom sliding panel (Google Maps, Google Music, Netflix) do not support hiding the panel on swipe down.

I took an initial shot at implementing the swipe down in [this branch](https://github.com/CUTR-at-USF/onebusaway-android/tree/swipeDown), but its not currently working.  I don't think I'll have much time to work on it in the very near future, but feel free to try it yourself if you have a chance.

**Comment by barbeau** [comment]
@bendu I just opened a PR at https://github.com/OneBusAway/onebusaway-android/pull/349 which is the above branch I referenced for swiping down on header to hide it, so its easier to find later.

**Comment by bendu** [comment]
@barbeau Sounds good. I'll hopefully have time to take a look at this next week.

**Comment by bendu** [comment]
@barbeau Thanks for doing all this. I've spent some time trying to get the SwipeDownGestureDetector:onFling to work and I suspect that something in the sliding panel library would need to be changed to get this to work.

Since neither Google Maps, Google Music, Netflix, or the sliding panel library itself supports swipe to hide, I suppose this is not a big concern. However, unlike the sliding panels in other apps, the one in OBA takes up more screen space than other apps, so there should be some way of dismissing the panel without touching the map. This is particularly useful in areas with a high concentration of stops (transit centers, downtown core, etc.) where trying to dismiss one stop could end up opening another. I'll implement dismissing with the back button and see if that would be good enough, since that is what Google Maps does.

**Comment by barbeau** [comment]
>I'll implement dismissing with the back button and see if that would be good enough, since that is what Google Maps does.

Sounds good!

**Comment by barbeau** [comment]
Alright everyone, we're closing in fast on a v2.0 release with the new UI.  So, I'm going to bring this long, winding issue to a close :).

A few things from the original mockup/concept didn't make the v2.0 cut, so I've pulled some of the items out into their own issues for future work/release, including:
* [Improved search (including integration of recent stops/routes)](https://github.com/OneBusAway/onebusaway-android/issues/309)
* [Nearby routes](https://github.com/OneBusAway/onebusaway-android/issues/352)

Thanks to everyone for their time and feedback!!  I really appreciate it, and I think it improved the UI overhaul tremendously.  If I missed anything or you have more feedback, please feel free to comment here, on one of the remaining issues, or open a new issue.

All UI redesign work is currently in the `develop` branch, so I'll be merging this into the master branch in the very near future.  There are some conflicts resulting from some intermediate/hotfix releases, so I won't be merging PR https://github.com/OneBusAway/onebusaway-android/pull/177#issuecomment-58111721 directly via Github.  I'll merge manually instead.  However, #177 will contain all the commits for the UI redesign, if anyone wants to revisit it at some point.

Closed via work in `develop` branch, to be merged into master shortly.

**Comment by barbeau** [comment]
For the record, getails on the route/direction/stop favorites (i.e., "starring a route") implementation done as part of the UI redesign are mentioned in https://github.com/OneBusAway/onebusaway-iphone/issues/457#issuecomment-155565598.

**Comment by jrharshath** [comment]
Although the issue is marked closed, I'm post some ideas after feedback was solicited on the developer email list. 

[Link to the email thread](https://groups.google.com/forum/#!topic/onebusaway-developers/XYVvHpsCZtY).

**Comment by barbeau** [comment]
Thanks!  I should also say that this is by no means the end of UX
improvements - it just closes out this iteration.  Ideas/suggestions are
always welcome here as new issues and on the OBA dev list.

Although the issue is marked closed, I'm post some ideas after feedback was
solicited on the developer email list.

Link to the email thread
<https://groups.google.com/forum/#!topic/onebusaway-developers/XYVvHpsCZtY>.

—
Reply to this email directly or view it on GitHub
<https://github.com/OneBusAway/onebusaway-android/issues/155#issuecomment-156734174>
.
