### ISSUE TITLE
Add Finnish translation

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#159]
Discussed here:

https://groups.google.com/forum/#!topic/onebusaway-developers/IIbTIlv85L4

>Can someone make this code change?

>Localization for finnish is now ready. It can be found here, https://dl.dropboxusercontent.com/u/47508878/oba_android_loc_finnish.zip
I made changes to two files: strings.xml and arrays.xml.
>- Turo

**Comment by arirusakko** [comment]
Hi guys

I've made pull request #253 that solves this enhancement.

**Comment by barbeau** [comment]
Fixed via https://github.com/OneBusAway/onebusaway-android/pull/253.
