### ISSUE TITLE
Destination reminders

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#17]
Right now we only have arrival reminders for when a bus is coming to the
stop where you want to board.

Multiple users have requested the ability to have a reminder for when you
want to get off the bus.

This will be dependent on showing the trip schedule; we'll have to wait
until that API is stabilized and create a screen for it.

Labels: Milestone-1.5
Comment 3 by devin@twuni.org, Jun 13, 2011
A workaround for this issue could be to set a reminder for when the bus that you are on is scheduled to arrive at the stop where you want to get off.

**Comment by barbeau** [comment]
See also the same issue on OTP Android:
https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/issues/415

**Comment by barbeau** [comment]
Quoted from the OTP Android issue above:

>It should be noted that we (USF) implemented this feature in a closed-source project, specifically for individuals with disabilities (i.e., the [Travel Assistance Device (TAD) mobile app](http://www.locationaware.usf.edu/ongoing-research/projects/travel-assistance-device/) - see [YouTube video](https://www.youtube.com/watch?v=pfqqIrrZYKU)).

>As part of this, USF owns two U.S. Patents ([US 8,138,907](http://www.freepatentsonline.com/8138907.pdf) and [US 8,169,342](http://www.freepatentsonline.com/8169342.pdf)) on the technology that was developed.  So, this is going to be a bit tricky - we either need to get permission from USF to use the above patented-technology, or come up with a new method.

>One possibility is to develop a plug-in model, where different implementations to notify the user could be used.  The USF technology could be one of those plugins.

>I'd like to see all implementations and a plugin model use [JSR293 Location API 2.0](https://jcp.org/en/jsr/detail?id=293) as the main interface design.  We used this interface design with TAD, and it worked well.  JSR293 is generalized well to different modes, so it can be used as part of the real-time nav implementation (https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/issues/297) as well.

>Also, it should be noted that OneBusAway Android currently implements reminders for when to *board* the transit vehicle - perhaps OneBusAway Android would be a better place to implement this (see https://github.com/OneBusAway/onebusaway-android/issues/17), unless we implement this as part of real-time nav in OTP Android (https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/issues/297).

**Comment by barbeau** [comment]
For the basic mechanism of notifying users when they are approaching their destination, the Android Geofencing API (http://developer.android.com/training/location/geofencing.html) seems like a good place to start.

**Comment by barbeau** [comment]
A presentation with an animation for the algorithm is downloadable from:
https://www.dropbox.com/s/x798cozmqccji9e/Barbeau%20-%20Cell%20Phone%20and%20GIS%20-%20GIS%20in%20Transit%202009.ppt?dl=0

If you put it in full-screen mode it has animations.  Slides 15-19 explain problems with simpler algorithms, and Slide 20 starts the animation for the algorithm we created.

**Comment by barbeau** [comment]
As part of this feature, I'd also like to improve the "We found a better trip plan" notifications.

From a user:

>Even after I have boarded my bus, I receieve "We found a better trip plan" emails....I boarded the Southbound bus #19, due at Hyde Park Ave and Cleveland St at 11:21 AM today, actually arriving at 11:26 AM. I received two "better route" notices after I had disembarked at my destination, Armenia Ave and De Leon St. A five minute delay is something I can wait on.
The proposed change had me taking the #30 Kennedy bus West to Armenia Ave, transferring, I believe, to the #14 Southbound bus. Workable, but too late to be of any help.

If we're tracking the user as part of the destination alert, we should be able to determine when a notification is no longer useful to the user, and cancel any pending notifications (or at least filter them out for completed sections of the route).

Related to https://github.com/OneBusAway/onebusaway-android/issues/758, which is about providing more context about the changed trip in the notification itself.

**Comment by barbeau** [comment]
From HART's travel trainer:

>This ability to create it on the individual’s phone on OneBusAway… can it be “saved” for reparative trips, or must it be reestablished each time? In other words, can I build a Trip Plan on the individual’s phone that they simply re-start each day. Such as an AM Trip and a PM Trip? Must it matchup with a particular “scheduled” trip, or will it work on that certain direction route at any time of day?
>
>Still looking for the SIMPLE to operate and dependable process.

Things to think about as we implement this to ensure it can be used by individuals with cognitive disabilities.
