### ISSUE TITLE
Hide "Contact Us" when custom API is set

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#180]
Currently, if you tap "Contact Us" menu option while having a custom API set, the app does nothing (just returns to map view) and provides no message.  We should add an informational message saying that no contact information is available because a custom API is set (contact information for each region comes from the Region API).

**Comment by barbeau** [comment]
Actually, removing the the "Contact Us" option completely is a better approach.

**Comment by bbodenmiller** [comment]
Is there an issue for this in the iPhone repo also?

**Comment by barbeau** [comment]
@bbodenmiller Not that I know of.  I'm not sure what the current behavior is for iOS.

**Comment by bbodenmiller** [comment]
I made a similar issue on the iPhone repo. It is probably worth discussing together however so we have similar functionality between apps.

**Comment by barbeau** [comment]
Fixed in `develop` branch via https://github.com/OneBusAway/onebusaway-android/commit/bbad77551b3a3c84514e5d76f6d663f88c2c5e61.
