### ISSUE TITLE
	Reminders don't restart after an update

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#19]
What steps will reproduce the problem?
1. Schedule a reminder
2. Update the app 
3. Wait for the reminder

What is the expected output? What do you see instead?

Android doesn't seem to be restarting the TripService, and so the reminder
alarms are removed. The user has to go and re-save a reminder, add a new
reminder, or reboot their phone.

Figure out a way for Android to run the server post-update, or always run
the service when the user runs the app.

**Comment by barbeau** [comment]
Looks like this might be caused by a missing `=` in an IF statement in HomeActivity, that is checking for `oldVer > 0` before rescheduling the reminders.  See https://github.com/OneBusAway/onebusaway-android/issues/220.
