### ISSUE TITLE
improve the green directional arrows with better/thicker outlines/shadows

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#23]
Honestly I think we can improve the whole pin to make it look better and to have different resolutions for different screen sizes.

This is migrated from this bug, where there is a PSD attached:
http://code.google.com/p/seattle-bus-bot/issues/detail?id=56

**Comment by barbeau** [comment]
This is fixed in `develop` with the new icon images (has been for a while), so I'm closing this:

![image](https://cloud.githubusercontent.com/assets/928045/9262935/e6512afc-41e6-11e5-9136-299ab6b1e798.png)
