### ISSUE TITLE
Change location accuracy threshold for Google Analytics

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#232]
@cagryInside I was looking at some of the location data from a few Android phones, and I'm thinking it probably makes sense to tighten up the horizontal accuracy threshold prior to a production release.

Currently, [we're using 100m](https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/java/com/joulespersecond/oba/ObaAnalytics.java#L43) as the cutoff threshold - meaning that we report analytics for distance to stop if the estimated error radius of the device location is less than 100m, and throw it away if its >= 100m.

I'm thinking it may be better to change this to 50m, so we have a tigher bound/accuracy on the analyitics data.  Looking at a few devices, most of them report accuracy < 50m when its reasonable.  If its more than 50m, it starts getting questionable, especially for our [smallest radii](https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/java/com/joulespersecond/oba/ObaAnalytics.java#L51), which is defined at 50m separation.

Your thoughts?  Any data from your devices?

Good apps to test with are [GPS Benchmark](https://play.google.com/store/apps/details?id=com.gpsbenchmark.android) and [GPSTest](https://play.google.com/store/apps/details?id=com.android.gpstest) (yes, they are both my apps ;) ).

**Comment by cagryInside** [comment]
@barbeau In the high-end device (nexus 6) I usually measure the horizontal accuracy <30m. But, I think we should also measure some results with older devices to see the variation.

**Comment by barbeau** [comment]
I was looking at data I collected from a number of Android 2.1 and 2.2
devices a while back, and it seems consistently <50m are good locations.
