### ISSUE TITLE
StopInfo event reported for incorrect button press in master branch

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#233]
Right now, when the user taps on the icon the map, we're reporting a "Loaded StopInfo from X", where X is the region name.  This event on iOS is actually related to the StopInfo project, the icon for which is shown next to the stop name on the ArrivalList Fragment, as discussed in https://github.com/OneBusAway/onebusaway-android/issues/103.

We should remove the "Loaded StopInfo from X" event from the current master branch, and replace it with a new event (not currently reported on iOS) called "Clicked MapStopIcon from X".

We should then report a similar map icon click event on iOS, to be opened in a new issue on OBA iOS.

**Comment by bbodenmiller** [comment]
Side note, why include the region in the event when we already report that and you can cross reference it?

**Comment by cagryInside** [comment]
@bbodenmiller At first, I thought it might be better to include the region in the event to keep it to be consistent with IOS stopInfo event. But, since they are different event, we might not need to include the region for MapStopIcon.

**Comment by barbeau** [comment]
Agreed to remove region from MapStopIcon event - my fault for writing up this ticket incorrectly.

**Comment by barbeau** [comment]
@cagryInside I believe we're ready to release another beta off the master branch.  Am I forgetting anything that needs to go in before the next release?

**Comment by cagryInside** [comment]
@barbeau I agree. I don't have anything else to submit for analytics.
Thanks
