### ISSUE TITLE
Sounder does not display route label

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#24]
Reported by cookieguru, Sep 21, 2010
Both the route popup under "show routes" in map view and the arrivals view show an empty label when viewing Sounder.  Similarly, Amtrak fails.

This is probably due to the fact that, despite being a required field, the shortName is not defined for these routes.  The API does not return a container for shortName either:

http://api.onebusaway.org/api/where/arrivals-and-departures-for-stop/40_S_KS.xml?key=TEST&version=2

Comment 1 by cookieguru, Sep 21, 2010
Correction, shortName is not required if longName is present.

Comment 2 by bdferris@onebusaway.org, Sep 21, 2010
Just to be clear, route shortName isn't technically a required field.  Instead, one of either route shortName or longName must be specified.  Both may be specified.  It's up to the app to use the most appropriate.  Either way, maybe the Android app could handle this better?

Comment 3 by cookieguru, Apr 20, 2011
This is fixed, though the bounding box for the text label is fixed in width which causes most of the "e" and all of the "r" in "Sounder" to be cut off.

Comment 4 by devin@twuni.net, Jun 6, 2011
A grid view works best when the route names are all approximately the same length. If any route has to fall back to its long name, then the grid view should probably be adjusted to suit routes with longer names. This could simply mean toggling between two different column widths, but it could be an indication that a grid view is no longer the ideal candidate for this route list.

I would say that the most significant portion of this issue has been resolved, and that the issue of the label being cut off should be pulled into a separate task.

**Comment by barbeau** [comment]
I believe this has been fixed - if anyone is aware of this still happening, please let me know.
