### ISSUE TITLE
GoogleAnalytics.setDryRun(true) doesn't work on Amazon Fire Phone (develop)

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#243]
We've observed a number of Google Analytics (GA) events reported from Amazon Fire Phones, which is strange because:

1. if `BuildConfig.DEBUG == TRUE` we set `GoogleAnalytics.getInstance(context).setDryRun(true);`, which should disable event reporting on any non-production signed build
2. The currently deployed production-signed beta that includes analytics does not run on a Fire Phone (currently only the develop branch supports the amazon build flavor)
3. There haven't been any production-signed releases of the amazon build flavor on the develop branch

Upon further inspection, it appears that `GoogleAnalytics.getInstance(context).setDryRun(true);` does not have any affect devices without Google Play Services (including the Fire Phone).  In other words, this is likely a bug in the Google Analytics SDK with local dispatching.  [The GA documentation](https://productforums.google.com/forum/#!topic/analytics/1zAmZCu1Bx4) does not state anything about this method not working on non-Google Play Services devices, so we assume it should work on devices like the Fire Phone:

>**public void setDryRun (boolean dryRun)**
>Toggles dry run mode. In dry run mode, the normal code paths are executed locally, but hits are not sent to Google Analytics servers. This is useful for debugging calls to the Google Analytics SDK without polluting recorded data.

Related StackOverflow post:
http://stackoverflow.com/questions/28842499/google-analytics-setdryruntrue-doesnt-work-in-amazon-firephone
Related post on Google GA forum:
https://productforums.google.com/forum/#!topic/analytics/1zAmZCu1Bx4

**Comment by cagryInside** [comment]
One possible workaround solution could be like this: 

    public static void initAnalytics(Context context) {
        if (BuildConfig.DEBUG) {
            //Disables reporting when app runs on debug
            GoogleAnalytics.getInstance(context).setDryRun(true);
            
            if( the device is amazon fire phone) {
                GoogleAnalytics.getInstance(this).setAppOptOut(true);           
             }
        }
    }

**Comment by barbeau** [comment]
Agreed, although I think the item that may be difficult (or at least has been in the past) is `if( the device is amazon fire phone)`.

This info normally comes from [`android.os.Build.MANUFACTURER`](http://developer.android.com/reference/android/os/Build.html#MANUFACTURER), but since this is just a string I've seen it change on different model phones from the same manufacturer, or characters within the string change case, which can cause problems depending on how you're checking for "equality".

However, according to this [Kindle spec](https://developer.amazon.com/appsandservices/solutions/devices/kindle-fire/specifications/01-device-and-feature-specifications) and this [Fire Phone spec](https://developer.amazon.com/public/solutions/devices/fire-phone/docs/fire-phone-specifications) it looks like it should be `Amazon` for all Amazon devices.  So, hopefully Amazon devices hold to this.

Given the above specs, let's go ahead and implement this workaround in the develop branch to prevent Fire Phone debug builds from sending analytics data, although let's do the check without assuming that `Amazon` is always the same case.  Just please be sure to reference this issue in the code comments, something like:

~~~
public static final String mAmazonManufacturer = "amazon";
...
public static void initAnalytics(Context context) {
    if (BuildConfig.DEBUG) {
        //Disables reporting when app runs on debug
        GoogleAnalytics.getInstance(context).setDryRun(true);

        // Workaround for #243- setDryRun(true) doesn't work on Fire Phone
        if(android.os.Build.MANUFACTURER.toLowerCase().contains(mAmazonManufacturer) {
            GoogleAnalytics.getInstance(this).setAppOptOut(true);           
         }
    }
}
~~~

**Comment by bbodenmiller** [comment]
Another option might be to setup a seperate tracker id for debug builds so you don't have to worry about turning GA off.

**Comment by cagryInside** [comment]
@barbeau thanks.

**Comment by barbeau** [comment]
Fix via https://github.com/OneBusAway/onebusaway-android/pull/246
