### ISSUE TITLE
How to use onebusaway-android with other GTFS databases

### ISSUE THREAD

**Issue by aj07mm** [OneBusAway/onebusaway-android#257]
I can't find a guide on how to use the project with my own files instead of the default data from florida that comes with it. How can i do this?

**Comment by cagryInside** [comment]
@aj07mm You need to run OneBusAway server to show your own GTFS data. This is the wiki page that explains how to configure the application:
https://github.com/OneBusAway/onebusaway-application-modules/wiki

**Comment by aj07mm** [comment]
Gracias!

**Comment by bbodenmiller** [comment]
Related it'd be awesome if the OBA apps were to support GTFS & GTFS-RT in the future for non-OBA agencies.
