### ISSUE TITLE
Add custom markers to BaseMapFragment

### ISSUE THREAD

**Issue by cagryInside** [OneBusAway/onebusaway-android#260]
We have implemented several enhancements (PR https://github.com/OneBusAway/onebusaway-android/pull/249) in ```BaseMapFragment``` to be able to use the  ```BaseMapFragment``` in other activities. However, when we are using Maps API v2 objects (e.g., adding a marker: ```mMapFragment.getMap().addMarker(...)``` ) outside of the maps package, Amazon build flavor is failing (https://github.com/OneBusAway/onebusaway-android/pull/255#discussion_r28558592). 

One possible approach could be to implement a method in the  ```BaseMapFragment``` which adds a marker from given lat/long.

**Comment by cagryInside** [comment]
@barbeau I implemented a method (https://github.com/cagryInside/onebusaway-android/commit/e9a1fa46a6d6ca8cb5cb69e1b60885e18fe688f1#diff-5542c1da09f3ac946281c3f258d88e8cR739) that adds markers to ```BaseMapFragment```. It seems working (I only tested with Google phone), but I will also test this with Amazon phone tomorrow and open a PR.

Furthermore, I would like to add this method to ```ObaMapView``` interface, however I had to return created marker from the method. So, I couldn't add this method as interface. Created marker object is important because, if we want to remove the marker from the map, simply we can call ```marker.remove()```.

**Comment by cagryInside** [comment]
Also, I tested this development with Amazon firephone.

**Comment by barbeau** [comment]
@cagryInside I just opened https://github.com/OneBusAway/onebusaway-android/pull/263, please check it out and see if it meets your needs for use in #255.

**Comment by cagryInside** [comment]
@barbeau Thanks, I checked the implementation. It seems it's going to solve all marker related problems. I will test this with Amazon phone tomorrow, and let you know.

**Comment by cagryInside** [comment]
Closed in favor of PR https://github.com/OneBusAway/onebusaway-android/pull/263
