### ISSUE TITLE
Improve stop/trip problem reporting API requests

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#264]
Looks like there is an issue with how OBA Android is sending REST API requests for stop/trip problem reporting - see https://github.com/OneBusAway/onebusaway-application-modules/issues/126#issuecomment-94544761.

If we can confirm that the documented APIs are currently working, we should change to using that method:

* http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/report-problem-with-stop.html
* http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/report-problem-with-trip.html

**Comment by barbeau** [comment]
@cagryInside Could you please take a shot at fixing this?  You should be able to use the app.staging.obahart.org machine to test (i.e., you can log into the admin webapp to see the problem reports).  There is an existing PR open here, but there are still some issues to be worked out - https://github.com/OneBusAway/onebusaway-android/pull/382.

**Comment by barbeau** [comment]
Newest status - issue reporting seems to be working in Puget Sound, but not Tampa or Atlanta.  So to fix this issue, we need to test against at least those three regions and make sure it works.

**Comment by barbeau** [comment]
And we should probably confirm with admins of Puget Sound and Atlanta that they actually get the problems reports after we fix this.

**Comment by cagryInside** [comment]
@barbeau I just pushed a fix for this issue.  There was a problem with post requests (Sheldon mentioned   [here] (https://github.com/OneBusAway/onebusaway-application-modules/issues/126#issuecomment-94544761)). So, I used get requests instead of post requests for stop/trip problem reporting. Further, there was a parsing problem [here] (https://github.com/cagryInside/onebusaway-android/commit/10fa4b34e7095ee8e271034a700767a1454ba355#diff-0c511ed41cc723fd7c7df26cc2136ed6R179). It wasn't checking the response's error fields.

**Comment by barbeau** [comment]
@cagryInside Awesome!  Just copied you on an email - I want to test this with the 3 main production OBA instances to confirm it works, then you can submit a PR.

**Comment by cagryInside** [comment]
Atlanta's server returns an internal error for API request:

Request:
```
http://atlanta.onebusaway.org/api/api/where/report-problem-with-stop.json?app_ver=58&app_uid=fc35c268f18c0929249cdad89e8d5fcc&version=2&key=v1_BktoDJ2gJlu6nLM6LsT9H8IUbWc=cGF1bGN3YXR0c0BnbWFpbC5jb20=&stopId=MARTA_906231&code=other&data=%7B%22code%22%3A%22other%22%7D&userComment=Sean%2FCagri%20test%20-%20please%20ignore&userLat=28.0586106&userLon=-82.4164027&userLocationAccuracy=22
```

Response:
```
{
code: 500,
currentTime: 1456424006667,
data: null,
text: "Cannot access Hessian remote service at [http://localhost/onebusaway-transit-data-federation-webapp/remoting/transit-data-service]; nested exception is com.caucho.hessian.io.HessianFieldException: java.sql.SQLException.next: 'org.postgresql.util.PSQLException' could not be instantiated",
version: 1
}

```
