### ISSUE TITLE
Minor UI bug: keyboard doesn't hide after navigating away from the search tab

### ISSUE THREAD

**Issue by shakeelmohamed** [OneBusAway/onebusaway-android#265]
This is for 1.7.8 of the app, if that's relevant.
Please close if this is irrelevant, already fixed, or not possible.

0. Summary: The on-screen keyboard doesn't hide after navigating away from the search tab, it's a bit annoying to have to tap the hide icon every time.
0. Steps to reproduce: Open the app, tap the menu (3 dot thing in the corner), tap "my stops", it defaults to "search" (not sure if that's most preferred behavior, especially for daily commuters) & the keyboard shows up because the search box is selected automatically, then tap either the starred or recent tabs and the on screen keyboard will still be there.
0. Expected behavior: The on screen keyboard should hide itself if the user navigates away from the search tab
0. Observed behavior: Already mentioned in point 2
0. Device and Android version: Nexus 4, CyanogenMod 11 M 12 (Android 4.4.4 KitKat) - but I believe I saw this even when I was using stock Android.
0. Screenshots: 
  - 
![screenshot_2015-05-08-23-55-51](https://cloud.githubusercontent.com/assets/1480063/7549214/fddd0cce-f5e0-11e4-9417-6bdc5af70fdc.png)

0. Possible fixes: Not sure since I haven't done much Android programming. A theoretical fix would be when the user is in the "my stops" menu, check which tab the user is on, if it's not "Search" then hide the keyboard if it's showing.

Thanks for this app! I've been using it for a few years and it's saved me many times :smile:

**Comment by barbeau** [comment]
@shakeelmohamed Thanks for the report, and I'm glad you find the app useful!  Thanks for including the steps to reproduce too.

I've never noticed this, but you're right, the desired behavior would be to hide the keyboard when you can no longer enter any text.  This applies to the "My Routes" search as well as the "My Stops" search.  I'll push a quick fix to Github shortly.

**Comment by shakeelmohamed** [comment]
Thanks @barbeau I'll be on the lookout for an app update!
