### ISSUE TITLE
Shortcuts are renamed after installing an app update

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#271]
Reported by a user:

> App Version: 1.7.9
> Model: SM-N910V (Samsung Galaxy Note 4 (Verizon))
> OS Version: 5.0.1 / 21
> All of my home screen shortcuts lose their names every time you issue a new version of the software.  This completely defeats the purpose of having home screen shortcuts.

Me:
> 1.       When you create the shortcut on your home screen, are you leaving the default stop name, or changing it to a new name?

User:
> Leaving the default in most cases 

Me:
> 2.       When the shortcuts lose their names, is the end result a blank name?  Or, if you’re changing the name (see 1), is the end result the original stop name?

User:
> Every shortcut is renamed to OneBusAway 

I can't replicate this on a LG G4.

My feeling is that its a device issue, and not an issue in OneBusAway - here's a report of something similar happening on a Galaxy S4 with Google Maps:
http://forums.androidcentral.com/android-4-1-4-2-4-3-jelly-bean/317001-google-maps-update-keeps-renaming-navigation-shortcuts-generic-maps.html

**Comment by barbeau** [comment]
@cagryInside When you have a chance, could you see if you can replicate this on your devices?  You can download past release APKs from https://github.com/OneBusAway/onebusaway-android/releases.  Not an emergency, but I'd like to see if it happens on other devices.

Steps to replicate:

1. Uninstall OBA
2. Install v.1.7.8
3. Star a stop in the app on the arrivals list screen
4. Go back to main screen
5. Go to "My Stops->Starred"
6. Long press on stop, and select "Create shortcut".  A shortcut with the name of the stop should appear on your home screen, check to make sure its there.
7. Install v.1.7.9 as an update
8. Go back to your home screen and see if the shortcut name changed.

**Comment by barbeau** [comment]
More of my questions to user:

>A few more questions:
* Are you creating the shortcuts by long-pressing on stop in your favorites list, or by going to your device’s Widgets menu and dragging the “OneBusAway Stop” icon to your home screen?
* Have you seen this problem on other devices outside of your Note 4?

User:

>It's been awhile since I created those shortcuts. I know I did at least some of them from the Widgets menu rather than from inside the One Bus Away app, but I'm not sure whether or not I did all of them that way. And no, I can't remember whether or not I have seen this issue on my older phones.

**Comment by cagryInside** [comment]
@barbeau I try to replicate the issue on my Nexus 6. I tried to add shortcuts in both ways (from the app and from the widgets). But everything works fine.

**Comment by barbeau** [comment]
Thanks @cagryInside!  Since I don't believe there is anything we can do to fix this in OneBusAway, I'm going to close this as "won't fix".  If we can find a device to reproduce this on, or if we get more info on how we can prevent this from within the app, then we can re-open.

**Comment by cagryInside** [comment]
@barbeau I just test with HTC EVO 3D and replicate the issue. The shortcuts turns to generic "OneBusAway".

**Comment by barbeau** [comment]
@cagryInside Oh, ok.  Any hints from the log as to what is going on?  It would be nice if we could try and reproduce this for another app, but since it only happens after an app update that's a bit tricky.

**Comment by barbeau** [comment]
Also, what Android version is the HTC EVO 3D?

**Comment by cagryInside** [comment]
HTC EVO 3D Android 4.0.3.

Also, I try to do further tests. Now it stopped changing the names.

**Comment by cagryInside** [comment]
@barbeau Same issue was observed with Google Maps on HTC device.

**Comment by barbeau** [comment]
@cagryInside Ok, thanks - good to know about Google Maps.  Sounds like its out of our control, and possibly non-deterministic (from our perspective) too.
