### ISSUE TITLE
Active time windows of Alerts (i.e., Situations) aren't respected

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#278]
Reported on the [OBA Dev list](https://groups.google.com/forum/#!topic/onebusaway-developers/GWiGsMzae94):

>I am having issue with old alerts still showing up on Android phone. Looking at the '/api/where/arrivals-and-departures-for-stop' there is 'data.references/situations.activeWindows' element but I do not find any code that checks these values on Android.

>Is there update / patch available for this?

If we can get a hold of a response that includes this info we can add support for it in OBA Android.

**Comment by barbeau** [comment]
As I mentioned in the above thread on the dev list, the current behavior of OBA Android is to display whatever situations are returned in the API call for arrivals-and-departures-for-stop, regardless of any time window.  I believe this is because the built-in tools to publish service alerts in the OBA webapp don't include the ability to set an active time window (IIRC), so it wouldn't have been an issue for clients not supporting it if alerts weren't published with a time window.  But, other tools will definitely allow this, so we should support it and only show alerts if they are in the active time window.

**Comment by softrunit** [comment]
```
{

    "code": 200,
    "currentTime": 1438749126726,
    "data": 

{

    "entry": 

{

    "arrivalsAndDepartures": [ ],
    "nearbyStopIds": 

[

    "DART_4053"

],
"situationIds": 

    [
        "DART_54"
    ],
    "stopId": "DART_4041"

},
"references": 
{

    "agencies": 

[

    {
        "disclaimer": "",
        "id": "DART",
        "lang": "en",
        "name": "Des Moines Area Regional Transit Authority",
        "phone": "515-283-8100",
        "privateService": false,
        "timezone": "America/Chicago",
        "url": "http://www.ridedart.com"
    }

],
"routes": 
[

    {
        "agencyId": "DART",
        "color": "996600",
        "description": "",
        "id": "DART_17",
        "longName": "HUBBELL AVE / ALTOONA",
        "shortName": "17",
        "textColor": "FFFFFF",
        "type": 3,
        "url": ""
    }

],
"situations": 
[

{

    "activeWindows": 

[

    {
        "from": 1435005045,
        "to": 1436072372
    }

],
"allAffects": 
[

    {
        "agencyId": "DART",
        "applicationId": "",
        "directionId": "",
        "routeId": "",
        "stopId": "",
        "tripId": ""
    }

],
"consequences": [ ],
"creationTime": 1436072383004,
"description": 
{

    "lang": "en",
    "value": "DART will not operate bus service on Saturday, July 4, 2015 in observation of Independence Day.\n\nDART will operate Saturday service on Friday, July 3, 2015 for the day before the holiday. Hours for the customer service window and phones are 8 a.m. to 4 p.m. and Administrative offices are also closed on Friday, July 3, 2015.\n\nThe following routes will not operate on Friday, July 3, 2015:\n\n· Local Routes 5, 8, 11, 13, 51\n\n· Express Routes\n\n· Flex Routes 73, 74\n\n· D-Line Downtown Shuttle\n\n· The LINK Shuttle\n\n· On Call Services\n\nFor more information, contact DART Customer Service at 515-283-8100 or by email at dart@ridedart.com.."

},
"id": "DART_54",
"publicationWindows": [ ],
"reason": "",
"severity": "",
"summary": 

        {
            "lang": "en",
            "value": "No DART bus service on Saturday, July 4, 2015"
        },
        "url": null
    }

],
"stops": 
[

{

    "code": "3790",
    "direction": "E",
    "id": "DART_4041",
    "lat": 41.600276,
    "locationType": 0,
    "lon": -93.609101,
    "name": "UNIVERSITY AVE / PENNSYLVANIA AVE, DSM",
    "routeIds": 

    [
        "DART_17"
    ],
    "wheelchairBoarding": "UNKNOWN"

},
{

    "code": "3802",
    "direction": "W",
    "id": "DART_4053",
    "lat": 41.600464,
    "locationType": 0,
    "lon": -93.60921,
    "name": "E UNIVERSITY AVE / PENN AVE, DSM",
    "routeIds": 

                    [
                        "DART_17"
                    ],
                    "wheelchairBoarding": "UNKNOWN"
                }
            ],
            "trips": [ ]
        }
    },
    "text": "OK",
    "version": 2

}
```

**Comment by barbeau** [comment]
Thanks @softrunit!  I've been doing work trying to finish off the develop branch and get it out at least into an alpha in the next week or so.  Is that reasonable for your timeline?  Or is this something that you'd prefer to see get pushed out to production in a hotfix (e.g., if this is affecting users of your deployment)?

**Comment by softrunit** [comment]
Thanks Sean, we would prefer hotfix asap if possible. In fact, I was going
to work on it in our fork to get it patched today. I can send you patch
unless u get to it first. Let me know what your day look like.

**Comment by barbeau** [comment]
@softrunit Yes, if you have a patch please go ahead and submit it as a PR against the master branch.  That would be the fastest resolution.

**Comment by softrunit** [comment]
@barbeau pull request is in progress.

**Comment by barbeau** [comment]
PR at https://github.com/OneBusAway/onebusaway-android/pull/280

**Comment by barbeau** [comment]
New PR at https://github.com/OneBusAway/onebusaway-android/pull/281.
