### ISSUE TITLE
Sounder route label is cut off

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#28]
This task is derived from  Issue 68  (http://code.google.com/p/seattle-bus-bot/issues/detail?id=68); specifically, comment #3. The example stop given in that issue (http://api.onebusaway.org/api/where/arrivals-and-departures-for-stop/40_S_KS.xml?key=TEST&version=2) does not seem to exist any longer. To reproduce this problem, one must either mock the API call or find a route that contains a longName but whose shortName is absent. The column in the grid view is set to be a constant 40sp, which does not give enough room for longer route names, like 'Sounder'.

Comment 1 by cookieguru, Jan 22, 2012
http://api.onebusaway.org/api/where/arrivals-and-departures-for-stop/40_S_KS_NB.xml?key=TEST&version=2

**Comment by barbeau** [comment]
This was fixed as part of the UI redesign, so I'm closing.
