### ISSUE TITLE
Add Google Analytics to new features

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#283]
I'd like to get an alpha release out soon based on the current `develop` branch, but before that we need to add Google Analytics to a few of the new items we've added recently.  Off the top of my head, this includes:

* Route favorties - starring and unstarring a route/headsign combination for a specific stop, or selecting to star it for all stops
* Arrival times style - we will be switching to a cards style of arrival times by default, but allow users to switch back to "classic OBA" arrival times style as well.

Also, we could use GA on a few other old items that don't currently appear to be outfitted:

* SearchResultsFragment
* RouteInfoListFragment
* SituationFragment

@cagryInside Could you tackle this?  Also please let me know if there is anything I'm forgetting.

**Comment by cagryInside** [comment]
@barbeau Do we have the latest UI changes in develop branch?

**Comment by barbeau** [comment]
Yes, all UI changes are in the develop branch.  Develop is the current HEAD for the entire project.

**Comment by cagryInside** [comment]
@barbeau please find Google Analytics implementations below. IMO, ```Arrival times style``` implementation is fine, however I am pushing too many long labels in the ```Route favorties``` implementation. In this case, we can use secondary dimensions, but then we will be using a dimension for  very specific ```label```.

> Arrival times style - we will be switching to a cards style of arrival times by default, but allow users to switch back to "classic OBA" arrival times style as well.

Implementation:

| Event Category  | Event Action | Event Label |
| ------------- | ------------- | ------------- |
| app_settings  | general  | Set Arrival info style: Cards  |
| app_settings  | general  | Set Arrival info style: OneBusAway Classic  |

GA Console Screenshot:

![screen shot 2015-08-20 at 1 18 48 pm](https://cloud.githubusercontent.com/assets/2777974/9390399/cf0ce11c-473e-11e5-84a0-3150c100ae30.png)




> Route favorties - starring and unstarring a route/headsign combination for a specific stop, or selecting to star it for all stops

Implementation:

| Event Category  | Event Action | Event Label |
| ------------- | ------------- | ------------- |
| ui_action  | edit_field  | Starred route <route_id> for <stop_id> or <All stops> |
| ui_action  | edit_field  | Unstarred route <route_id> for <stop_id> or <All stops> |

GA Console Screenshot:

![screen shot 2015-08-20 at 1 18 16 pm](https://cloud.githubusercontent.com/assets/2777974/9390487/6ddebf0e-473f-11e5-9e3e-bcb837e0c372.png)

**Comment by barbeau** [comment]
@cagryInside Looks good!  My only change would be for tracking route favorites, it should be `<route_id> and <headsign> for <stop_id> or <All stops>`.  This would allow us to track which direction of a route the user was starring.

**Comment by cagryInside** [comment]
> My only change would be for tracking route favorites, it should be <route_id> and <headsign> for <stop_id> or <All stops>. This would allow us to track which direction of a route the user was starring.

Now the route favorites looks like this:

| Event Category  | Event Action | Event Label |
| ------------- | ------------- | ------------- |
| ui_action  | edit_field  | Starred route `<head_sign>_<route_id> for <stop_id> or <All stops>` |
| ui_action  | edit_field  | Unstarred route `<head_sign>_<route_id> for <stop_id> or <All stops>` |


![screen shot 2015-08-20 at 1 55 54 pm](https://cloud.githubusercontent.com/assets/2777974/9391218/8b8d929c-4743-11e5-9db7-065ffa390963.png)

**Comment by barbeau** [comment]
@cagryInside Any reason in particular its not in the order `routeId_headsign`?  I would think this would be a more natural ordering.  Plus, we'd be guaranteed that the first "_" would always separate the agency and routeId - if we move routeId after headsign, we can no longer guarantee that, as headsign GTFS text won't be pre-processed, but routeId and agencyId will.

**Comment by cagryInside** [comment]
> @cagryInside Any reason in particular its not in the order routeId_headsign? I would think this would be a more natural ordering. Plus, we'd be guaranteed that the first "_" would always separate the agency and routeId - if we move routeId after headsign, we can no longer guarantee that, as headsign GTFS text won't be pre-processed, but routeId and agencyId will.

Fixed in commit https://github.com/cagryInside/onebusaway-android/commit/9b481f7bf6d1f4dbe37a6a0f7343970e4ac636d6#diff-f5287a81d12fc959d16389e79aa779a4R1267

**Comment by barbeau** [comment]
Thanks @cagryInside!

**Comment by barbeau** [comment]
This is fixed in `develop` branch via https://github.com/cagryInside/onebusaway-android/commit/9b481f7bf6d1f4dbe37a6a0f7343970e4ac636d6 and https://github.com/cagryInside/onebusaway-android/commit/9b481f7bf6d1f4dbe37a6a0f7343970e4ac636d6#diff-f5287a81d12fc959d16389e79aa779a4R1267.
