### ISSUE TITLE
MyRoutesActivity has full package name in Google Analytics reports

### ISSUE THREAD

**Issue by cagryInside** [OneBusAway/onebusaway-android#284]
In the Google Analytics console every screen name should have only the activity or fragment name not the full package name.
 
![screen shot 2015-08-13 at 1 37 38 pm](https://cloud.githubusercontent.com/assets/2777974/9256967/eaec3f78-41c0-11e5-9c6e-fbd590e11e5f.png)

**Comment by cagryInside** [comment]
Same problem happens for ```RegionsActivity```.

![screen shot 2015-08-13 at 1 54 10 pm](https://cloud.githubusercontent.com/assets/2777974/9257356/23312c7a-41c3-11e5-829d-25a222837cbe.png)

**Comment by cagryInside** [comment]
![screen shot 2015-08-18 at 11 40 33 am](https://cloud.githubusercontent.com/assets/2777974/9335127/4876dec2-45a0-11e5-94ec-bf471818b8d7.png)

We don't have ```TripListActivity``` in the ```develop``` branch. When we switch the ```develop``` branch in production, this issue will be resolved.

**Comment by barbeau** [comment]
>We don't have TripListActivity in the develop branch.

@cagryInside Good point, I believe I refactored this to `MyRemindersActivity` for clarity.

**Comment by barbeau** [comment]
And, the fragment also to `MyRemindersFragment`.

**Comment by barbeau** [comment]
Fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/pull/285.
