### ISSUE TITLE
Distinguish between arrivals and departures clearly at terminal stops for routes

### ISSUE THREAD

**Issue by jrharshath** [OneBusAway/onebusaway-android#287]
The stop info screen for a regular stop shows only departures from that stop, but that screen of a terminal stop shows departures as well as arrivals. This is inconsistent with the behavior of all other stop info screens.

Let me know how you guys think this can be addressed.. My suggestion is to show the schedules/predicted arrival time underneath/beside the scheduled departure time if that route starts at that stop. For all other routes, these times are going to be the same, so we can safely ignore them.

![Uploading Screenshot_2015-08-26-08-25-01.png…]()

Thoughts?

**Comment by barbeau** [comment]
@jrharshath I agree that arrivals and departures aren't very clearly displayed on Android currently.

Can you provide examples of how this is clearly displayed elsewhere?  I thought OBA Android was consistent(ly bad) as the other platforms in this regard.

Also, your screen shot didn't seem to upload correctly - could you please repost?

I'd also like to figure out how this could be better displayed on both the classic OBA display of arrival times, and the new cards display we're planning to use (see https://github.com/OneBusAway/onebusaway-android/blob/develop/REBRANDING.md#configuration-options for early screenshots).

Note that this is also related to https://github.com/OneBusAway/onebusaway-application-modules/pull/142, as there are a few situations where full arrival/departure info may not be entirely correct.

**Comment by barbeau** [comment]
Actually, here is the newest UI for OBA Android (above link is a bit dated now):
https://github.com/OneBusAway/onebusaway-android/issues/155#issuecomment-131239723

**Comment by barbeau** [comment]
Related to this issue - it would be nice to have a filter option per stop to show only departing routes (i.e., trips with `stopSequence = 0`).  This would cut down on the noise of arrivals of the same route name (not including headsign) that are incoming, not outgoing.

**Comment by barbeau** [comment]
To improve this in the clients, I believe we need a new element in the REST API response indicating whether or not a stop is the last stop in a trip - see https://github.com/OneBusAway/onebusaway-application-modules/issues/148.

@jrharshath Just wanted to ping you again on the above questions earlier in this thread that I asked, when you get a chance to respond.

**Comment by jrharshath** [comment]
I've not seen how other apps are doing it better. In the case of OBA, the information shown doesn't specify whether this is arrival time or departure time, and it makes me lose confidence in those time estimates.

Scheduled information is much more useful when looking up departures from terminal stops, so I've personally resorted to looking up schedules on an app for those cases.

Anyway, I've put together a mockup of how departures from terminal stations can be shown:

![image](https://cloud.githubusercontent.com/assets/85807/11165220/5f461c86-8ad7-11e5-9740-19e1e11adc7d.png)

Reviews/Feedback/loopholes are solicited as usual :)

**Comment by barbeau** [comment]
From https://github.com/OneBusAway/onebusaway-iphone/pull/547#issuecomment-195779008, OBA iOS just made a change to the UI control for filtering departures.  Here's the new UI:

![image](https://cloud.githubusercontent.com/assets/928045/13747023/aa248dc4-e9cc-11e5-93ef-ded01f313fbb.png)

**Comment by barbeau** [comment]
My mistake on the iOS screenshot - this is just for filtering routes, it has nothing to do with arrivals vs. departures (see https://github.com/OneBusAway/onebusaway-iphone/pull/547#issuecomment-196403059).

**Comment by barbeau** [comment]
Via https://github.com/OneBusAway/onebusaway-application-modules/issues/148 and PR https://github.com/OneBusAway/onebusaway-application-modules/pull/149, we now have access to a new API parameter `totalStopsInTrip` on some OBA installations that should help with this.

>* totalStopsInTrip - the total number of stops visited on the trip for this arrival.  If the same stop is visited more than once in this trip, each visitation is counted towards the total.
* stopSequence - the index of the stop into the sequence of stops that make up the trip for this arrival.  This value is 0-indexed, and is generated internally by OneBusAway (it is **not** the GTFS `stop_sequence`).  The first stop in the trip will always have `stopSequence = 0`, while the last stop in the trip will always have `stopSequence = totalStopsInTrip - 1`.

Here is a request for the above stop - you can see the `totalStopsInTrip` field in the response:

http://app1.staging.obahart.org/api/where/arrivals-and-departures-for-stop/PSTA_1767.json?minutesAfter=65&key=TEST

**Comment by barbeau** [comment]
PR at https://github.com/OneBusAway/onebusaway-android/pull/449.
