### ISSUE TITLE
Add analytics to the "Sort By" buttons, negative arrival setting

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#298]
In `develop` branch, there are now "Sort By" buttons in the Action Bar for the `ArrivalsListFragment` (which sorts arrivals by route or ETA), as well as `MyStarredStopsFragment` (which sorts stops by name or frequency of use in the app).

We need to add Google Analytics to both of these.

@cagryInside Would you be able to work on this tomorrow morning so I can get a new alpha release out tomorrow?

Also, please note that the sort by arrivals is replacing the old analytics for the Style A / Style B preference.  The preference to change this is now replaced by the Sort By button in `ArrivalsListFragment`, and we're referring to Style A as "sort by ETA", and Style B as "sort by route".  So I think we should have two new analytics labels for these sort buttons, and forget about the Style A / Style B labels.

**Comment by barbeau** [comment]
Also, for `MyStarredStopsFragment`, there will likely be a "Sort by proximity" in the future - it doesn't exist now.

**Comment by barbeau** [comment]
Forgot another one - I added a setting for turning on/off negative arrivals.  We should add analytics to this too.

**Comment by cagryInside** [comment]
@barbeau I implemented the Analytics as following, if you are also agree on them, I will open a pr.

 Event Category  | Event Action | Event Label |
| ------------- | ------------- | ------------- |
| app_settings  | general  | Show Departed Buses: YES |
| app_settings  | general  | Show Departed Buses: NO |
| ui_action  | button_press  | Clicked sort by ETA from ArrivalsListFragment |
| ui_action  | button_press  | Clicked sort by route from ArrivalsListFragment |
| ui_action  | button_press  | Clicked sort by name from MyStarredStopsFragment |
| ui_action  | button_press  | Clicked sort by most frequently used from MyStarredStopsFragment |

**Comment by barbeau** [comment]
@cagryInside Thanks, looks good to me!

**Comment by cagryInside** [comment]
Fixed via https://github.com/OneBusAway/onebusaway-android/pull/299#event-417368586
