### ISSUE TITLE
When searching for numeric stops, switch the soft keyboard to digits

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#30]
Reported by eric.hanchrow, Dec 16, 2010
What steps will reproduce the problem?
1. Somehow get to the page with the magnifying glass in the rightmost top tab, then click it
2. Tap in the text entry area.  The soft keyboard appears -- but it's displaying letters, not numbers; in order to type a number, I have to first hit the "123" button in the lower-left corner.

What is the expected output? What do you see instead?

I'm pretty sure I've seen other apps bring up the numeric keyboard when it's clear from context that I'm only going to want to type some digits.  For example, if I use the built-in "Contacts" app, add a new contact, and tap in the "Phone" text entry field, I get a nice telephone-style sixteen-key keyboard, with the digits, and just a couple relevant symbols.

I wish OneBusAway did the same thing.

What version of the product are you using? On what operating system?
(It sure would be nice if there were an easy way to figure out what version of the app I'm using; I have to grovel around inside Settings/Applications to get that info)

Version 1.2.8, on Android 2.2 (on a Nexus one, which of course has no physical keyboard)

Please provide any additional information below.

Comment 1 by project member paulcwatts, Dec 19, 2010
Originally OneBusAway did bring up a digits-only keyboard. But you also need to be able to search for non-number routes like "Link" or "Sounder."

Yes, I'd love to have the digits appear first, because it's more likely that you'll want to search for numbers. Unfortunately there didn't seem to be a way to tell Android to do that. It's worth taking another look to see if they haven't added something in newer SDKs.

I'll also add something in Help to get the Version. A cheap way right now is to click on Help / "I found a bug!" and the version is listed in the email template that you are taken to.

Comment 2 by devin@twuni.org, Jun 6, 2011
The Android SDK does let you specify the input format so that the numeric keyboard is used. Unfortunately, the numeric keyboard is exclusive and does not let you get back to the 'regular' one. To support both, maybe a toggle next to the input field for the preferred keyboard would suffice. If the most common use case is for strictly numbers and this is the default, then I might never use that little icon except in a 'Ooo, this is new... what does this do?' context. If you need to type something like 'Link' or 'Sounder' and all you get is a numeric keypad, then you'll probably start looking for a way to get a regular keyboard. An icon next to the text field that says 'Abc' would then seem pretty obvious.

It's worth experimenting with, I think. Ideally, though, you'd get a numeric keypad by default and the Android OS would provide an integrated way to get back to a regular keyboard. Maybe there is a way to do this.

Comment 3 by cookieguru, Jan 22, 2012
Launch this app: https://market.android.com/details?id=com.usps
From the landing page, select zip codes.
Tap the "Cities in a ZIP code" field.
Focus on the only text box.

Default keyboard is numeric, and I can switch to my ABC keyboard.  This is NOT the "dialer" numeric keyboard but the one with all the symbols.

**Comment by barbeau** [comment]
I recently tried to implement this (see [this commit](https://github.com/OneBusAway/onebusaway-android/commit/1de62ee1943414062d394d63c634145ea2ab8121), and the only configuration I could find was defaulting to the numeric keyboard, but this also prevents you from entering alpha values.  As far as I can tell you can't default to numeric pad but still allow the user to switch to alpha.  And, because routes (and I guess technically stops) can have alpha values to search for, this doesn't work for us.  I ended up reverting in https://github.com/OneBusAway/onebusaway-android/commit/bc6dfb791a8dbde0b69d269c2391ce1919646490.  If anyone else knows how to default to numeric pad but keep ability to enter alpha values, please let me know.

**Comment by barbeau** [comment]
Closing this as part of clean-up, as it doesn't seem feasible.
