### ISSUE TITLE
Allow OBA Android to be multiwindow

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#302]
Requested by user:

> I have a Note 4. (n910t). Please update One Bus Away to support the Multi Window feature found on the larger Samsung phones. This would let me have One Bus Away open while using email or Firefox, without the need for constant switching. 
> Thank you!
> App Version: 1.7.9
> Model: SM-N910T
> OS Version: 5.0.1 / 21

I'm not sure what all needs to happen in OBA Android to make this work, but it would be very useful.

Here's a general article about multi-window on Note 4.0:
http://www.androidcentral.com/multitasking-samsung-galaxy-note-4-0

**Comment by barbeau** [comment]
Looks like this actually may be relatively simple.  From http://www.modaco.com/news/android/developers-add-support-for-samsung-multi-window-to-your-apps-r823/:

>In your AndroidManifest.xml, do the following...

>Make your application appear in the Multi Window bar. Add the `MULTIWINDOW_LAUNCHER` intent category to your application's main launcher activity... so just below your `android.intent.category.LAUNCHER` line, add:

>`<category android:name="android.intent.category.MULTIWINDOW_LAUNCHER" />`

>Indicate you're using the Multi Window library. Include the following just before your `</application>` close tag:

>`<uses-library required="false" name="com.sec.android.app.multiwindow"> </uses-library>`

>Add the metadata to indicate your application is Multi Window compatible. Add the following metadata again just before your </application> close tag:

>`<meta-data android:name="com.sec.android.support.multiwindow" android:value="true" />`

>Specify the default window size. You should specify the default sizes for your Multi Window configuration using the additional metadata tags / dimens.xml entries below. The `dimens.xml` values below show the default values taken from Samsung's Gallery application, adjust for your needs if necessary. ;) 

>Add the metadata again just before the </application> close tag:

>~~~
<meta-data android:name="com.sec.android.multiwindow.DEFAULT_SIZE_W" android:resource="@dimen/app_defaultsize_w" />
<meta-data android:name="com.sec.android.multiwindow.DEFAULT_SIZE_H" android:resource="@dimen/app_defaultsize_h" />
<meta-data android:name="com.sec.android.multiwindow.MINIMUM_SIZE_W" android:resource="@dimen/app_minimumsize_w" />
<meta-data android:name="com.sec.android.multiwindow.MINIMUM_SIZE_H" android:resource="@dimen/app_minimumsize_h" />
~~~

>and in your dimens.xml:

>~~~
<dimen name="app_defaultsize_w">632.0dip</dimen>
<dimen name="app_defaultsize_h">598.0dip</dimen>
<dimen name="app_minimumsize_w">632.0dip</dimen>
<dimen name="app_minimumsize_h">598.0dip</dimen>
~~~

**Comment by waltarmour** [comment]
Given the age of this issue, is this something that still needs to happen?   Wouldn't the current Android split-screen support cover this case?

OBA seems to be handling split-screen just fine at the moment.

**Comment by barbeau** [comment]
@waltarmour If OBA currently seems to be working fine in split-screen I'll close the issue.  Thanks for testing!
