### ISSUE TITLE
Add a brief tutorial for how to use features in the v2.0 app with new UI

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#313]
I've used this library in other apps:
https://github.com/amlcurran/ShowcaseView

...but its now deprecated.

@cagryInside or anyone else - know any good Android libraries to take the user on a tour of new features in your app?

@cagryInside I know you did a version of showing screenshots for #187.  If possible I'd like to have an interactive one for some of the core features in the app, just to introduce the user to the new look and feel.

**Comment by barbeau** [comment]
We may end up using the Tutorial Fragment implementation in https://github.com/OneBusAway/onebusaway-android/pull/335 for this, if we can't find a good library for in-app interactive tutorials.

**Comment by barbeau** [comment]
We should also include a definition of the blue/red/green color scheme for late/early/ontime - that's a frequent request from users.

**Comment by bbodenmiller** [comment]
Any idea what Google is using for Google Maps? The first use quick tips were useful and didn't appear to involve adding extra images.

**Comment by barbeau** [comment]
They probably rolled it themselves.

**Comment by barbeau** [comment]
Features to highlight (I'll continue to add to this list):

* Navigation via navigation drawer
* Sliding up panel
* Sorting arrivals by ETA or route
* Status colors (red/blue/green for early/late/ontime)

**Comment by barbeau** [comment]
Well, looks like https://github.com/amlcurran/ShowcaseView is no longer deprecated (?).  We can give that a shot, but now it's only API 11+.

**Comment by barbeau** [comment]
There is also https://github.com/deano2390/MaterialShowcaseView, although its minSdkVersion is 14.

**Comment by barbeau** [comment]
With this feature, we can also remove the auto-opening nav drawer and make it part of the tutorial.

**Comment by barbeau** [comment]
WIP PR for this feature is at https://github.com/OneBusAway/onebusaway-android/pull/406.

**Comment by barbeau** [comment]
PR ready to merge now at https://github.com/OneBusAway/onebusaway-android/pull/414.
