### ISSUE TITLE
Trip Details list - on initial load list doesn't always fill

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#322]
I thought I fixed this in https://github.com/OneBusAway/onebusaway-android/commit/e91ce7dc7c66e40af5cba04b7f29642d12fd8e49, but apparently not.

This is likely a result of this change to avoid hitting the API twice on Fragment load:
https://github.com/OneBusAway/onebusaway-android/commit/651328d6819545f10e3dd59149a2cb44731179ce

**Comment by bendu** [comment]
Interesting. I'll take a look at this in the next few days. I'm a bit overwhelmed right now to debug this.

@barbeau thanks for your help testing and adding features to the trip details list. I've only used the Puget Sound part of OBA, so there is a lot that I did not expect to happen

**Comment by barbeau** [comment]
@bendu Yes, if you could find time to look at this, it would be great.  I'll circle back to this prior to the 2.0 public release, but that probably won't be for a few weeks.  It might help to change the `TripDetailsAdapter` to extend `org.onebusaway.android.util.ArrayAdapter` - this is what `ArrivalsListAdapterBase` does, and it might be easier to bring `TripDetailsListFragment` behavior in-line with `ArrivalsListFragment` for all the corner cases (refreshing in `onResume`, not calling the API twice on init, keeping the currently element in view when refreshing, etc.).

No worries!  There are a lot of different scenarios based on the underlying data, and I didn't catch them either when reviewing it.

**Comment by bendu** [comment]
@barbeau Sorry for the slow response. I've been busier than I expected lately. I have been unsuccessful in getting the trip details list not to load, both in emulator and a 3rd gen Moto G. I'll continue trying to repro it, but it seems unlikely I will be able to.

That being said, I fixed a small bug I noticed relating to the trip details list, which I will create a PR for in a few minutes.

**Comment by barbeau** [comment]
@bendu Thanks for looking at this.  I also haven't seen it lately, and couldn't repo it myself just now.  I'll go ahead and close this for now, and I'll re-open if I see it again.

Thanks for the other bug fix!
