### ISSUE TITLE
Add "Did you know..." prompts

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#324]
Users often don't know about all the underlying features in OBA, such as reminders, etc.  It would be nice to have a gentle longer-term tutorial that prompted them with occasional quick facts - a "Did You Know..." feature.  This should have a "Don't show this anymore" button so user's can easily kill it, and should only be shown every few days or weekly, so we aren't bugging them constantly.

This is different from https://github.com/OneBusAway/onebusaway-android/issues/313, in that https://github.com/OneBusAway/onebusaway-android/issues/313 would be a guided tour and only be shown on install update/installation and guide the user through the feature.  This issue is just occasional quick facts that pop up every so often.

**Comment by barbeau** [comment]
Ideas:

* In route mode, if you have trouble tapping on vehicle icon (stops get in the way), rotate the map by putting two fingers on screen and rotate them.

**Comment by amrhossamdev** [comment]
Closing due to disabling
