### ISSUE TITLE
Starring route for all stops after removing star for a single stop doesn't work

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#327]
If you follow the below steps:

1. Go to a stop
2. Star a route for this stop
3. Unstar the route for this stop
4. Star the route for all stops

The route isn't starred for the current stop.  It should be starred.

**Comment by bendu** [comment]
Worked out a fix for this. Will push PR soon

**Comment by barbeau** [comment]
Fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/pull/347.  Thanks @bendu!
