### ISSUE TITLE
Show Cancelled or Re-Routed Buses

### ISSUE THREAD

**Issue by markus4star** [OneBusAway/onebusaway-android#331]
All too often, I am left waiting at a stop due to either:

1) a bus' scheduled run being cancelled without any indication other than it indicating late and then simply disappearing with me left waiting another 20-30 minutes for the next bus....

...OR... 

2) a bus being re-routed due to an event, protest or weather without any indication in the app.  Can this be addressed with Metro?

**Comment by barbeau** [comment]
@markus4star The easiest way for Metro to address this would be to put out a service alert for the relevant route, and that would show up in the app.  This would definitely address 2) above well.  1) can be the result of a number of different technical issues, and might be a bit harder to solve.

Could you please email us with the above request at android-app@onebusaway.org?  We can then forward your request to the folks at Sound Transit who maintain OneBusAway, who in turn can try and coordinate with Metro about this issue.  Thanks!

**Comment by bbodenmiller** [comment]
FYI I have tried requesting this many times from Sound Transit and King County Metro and have so far received many excuses for why they haven't implemented this yet. The primary excuse being that there current processes don't support it and not being willing to update the processes or systems.

See some of my feedback: https://github.com/SoundTransit/soundtransit-rds/issues/35, https://github.com/SoundTransit/soundtransit-rds/issues/11

**Comment by bbodenmiller** [comment]
@barbeau for 2 I think it'd be useful for the app to actually show a map of the reroute. The current method of agencies publishing a text description of the reroute is quite hard to comprehend if you don't have all the cities roads memorized.

**Comment by barbeau** [comment]
@bbodenmiller Agreed, better description of re-routing would be good.  Unfortunately there really isn't a good way to represent this directly in GTFS/GTFS-rt data.  One simple way, though, for agencies to do this would be to include a link to a PDF or other website that includes the map in the service alert itself.

**Comment by markus4star** [comment]
@barbeau Thanks and email sent to the alias with some additional commentary on increasing rider-experience and associating with 2014's Proposition 1 :-)

**Comment by barbeau** [comment]
@markus4star Awesome, thanks for sending your feedback! :)
