### ISSUE TITLE
Add "About" screen

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#340]
We should add an "About" screen to provide users info about the following:

1.  Short description of app
2.  Link to onebusaway.org and OBA Android Github repo
3. Credit icon contributors
 * Map vehicle markers - Arrow icon by Zlatko Najdenovski, MK (https://thenounproject.com/icon/63549/), marker icon by Housin Aziz, SE (https://thenounproject.com/term/map-marker/37239/), bus icon from Google Material Design (https://github.com/google/material-design-icons/blob/master/maps/svg/production/ic_directions_bus_48px.svg)
* Google Play Services - Show result of `GoogleApiAvailability.getOpenSourceSoftwareLicenseInfo()` - https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability#getOpenSourceSoftwareLicenseInfo(android.content.Context) (this will be `null` on non-Google devices.  As far as I can tell Amazon doesn't have an equivalent for us to use in the `amazon` build flavors).
* Code contributors

**Comment by barbeau** [comment]
Fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/commit/ba2d2a1f5d53be2b05633d632b1e1fef07e5593f.

**Comment by barbeau** [comment]
@cagryInside Could you please take a quick look at the new `AboutActivity`:
https://github.com/OneBusAway/onebusaway-android/blob/develop/onebusaway-android/src/main/java/org/onebusaway/android/ui/AboutActivity.java

...and the new Preference click for About:
https://github.com/OneBusAway/onebusaway-android/blob/develop/onebusaway-android/src/main/java/org/onebusaway/android/ui/PreferencesActivity.java#L243

...to confirm I got the analytics correct?

Would actually be good if you could confirm analytics events are still sending and being received in most recent `develop` branch commit, after I had to [exclude a portion of the analytics library](https://github.com/OneBusAway/onebusaway-android/commit/e0c168aa07c69e769ba88c51650663f9297b0ff7) to get release builds to work.

**Comment by cagryInside** [comment]
@barbeau `Analytics` on `AboutActivity` looks good.

> Would actually be good if you could confirm analytics events are still sending and being received in most recent develop branch commit, after I had to exclude a portion of the analytics library to get release builds to work.

I tested and it works perfectly.

![screen shot 2015-10-27 at 10 27 14 pm 2](https://cloud.githubusercontent.com/assets/2777974/10778233/4aae2d26-7cfa-11e5-8489-537e196e8a21.png)

**Comment by barbeau** [comment]
Awesome, thanks!
