### ISSUE TITLE
Improve "Show route on map" UX

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#346]
From OBA dev group:
https://groups.google.com/d/msg/onebusaway-developers/FyFQn4KYtvg/nyFXowrbBwAJ

>The "show route on map" option takes the app to a totally different screen, where it shows the entirety of the route. It makes the user lose context of where (s)he is. I'd suggest making it a sort of "toggle" which turns on a layer on the existing map, and just show routes on it directly.

I agree that these interactions could definitely be improved - the current UX was somewhat driven by the ease of implementation given the existing code in OBA Android.

I think there are probably 4 items that the user would want to keep track of, in terms of context, when selecting “show route on map”:

1.  Their real-time position
2.  The location of the currently-selected stop
3.  The closest vehicle (more in relation to their real-time position and currently-selected stop)
4.  The arrival time they selected "show route on map" from

The current UX does 4 fairly well (you just hit the back button, and you’re back where you were), but doesn’t do the first 3 very well.  1-3 could probably be accomplished when launching the new activity as well via some clever camera zooming, but you have the same experience of first being launched to a new Activity.  Google Maps always seems to reset the initial map view to lat/long (0,0) when launching a new Activity before the app can initialize the position, which exacerbates loss of context.

Changing to a "toggle" that shows the route mode in the current activity could be accomplished.  IIRC this was closer to the behavior of OBA v1.x (I'll have to review this).  I think 1-3 are straighforward to accomplish from a design perspective in the current activity, but 4 is a little bit harder - we'd probably need to collapse or hide the sliding panel to show enough of the route on the screen to be useful.  This could be a jarring UX when the user isn't expecting it.

It should be noted that we also need to think about the "Route Filter" option that appears in the Action Bar menu.  This could be confusing in the context of either UX - in both, we're showing one route on the map, but showing arrivals from multiple routes in the sliding panel.  The filter only affects the sliding panel arrival times, not the route view on the map.

Finally, I've wanted to investigate the possibility of adding an "explore"-type feature to OBA that, when tapping on the stop, would show the route lines for all trips that visit that stop.  Something like the below, taken from [this comment](https://github.com/OneBusAway/onebusaway-android/issues/155#issuecomment-61194037):

![image](https://cloud.githubusercontent.com/assets/928045/10799926/c7c822c2-7d85-11e5-93dd-8c84fecdfcfd.png)

I'm currently not show what performance of this would be like, especially on lower end devices.  And it could potentially crowd the map significantly, especially for transit centers.  But, we could think about how this works in the context of showing just a single route on the map as well.

**Comment by wittelw** [comment]
I love the feature but found two things (already discussed) to be the best candidates for improvement:
1) Once in "Show route on map" you loose the current scheduled and real-time estimates.
2) The initial map view of lat/long (0,0).

For 1) rather than rely on the back button it would be great to have these values in blue as in the TripDetailsActivity.

For 2) if technically possible a wait spinner until the map is zoomed to the route would be preferable. I would further find it more useful if the route was zoomed to my stop and the nearest bus in that direction. Regular map navigation would allow me to get the route-wide view if I desired.

**Comment by barbeau** [comment]
Thanks for the feedback @wittelw!  Good points.

**Comment by bbodenmiller** [comment]
Great job on this feature so far. One part of the current UX that I think could be improved is when the stops are shown. Currently, once a user zooms out far enough all you can see is a bunch of overlapping stops. I think it'd make sense at a certain zoom level to only show the route line and the currently selected stop. The current setup also makes it hard to click the bus icon.

Other features to consider could be only showing the stops, route, & bus for the trip the user selected, only showing stops and buses for one direction at a time, highlighting the route differently for the part past the stop the users waiting at.

How about leaving my stop selected when I select show route on map?!

**Comment by bbodenmiller** [comment]
In regards to the bus location feature, I noticed that it is showing data updated x minutes x seconds ago but it isn't updating once a second so the label isn't entirely accurate.

**Comment by barbeau** [comment]
>One part of the current UX that I think could be improved is when the stops are shown.

Agreed - this is now ticketed at https://github.com/OneBusAway/onebusaway-android/issues/367.

>In regards to the bus location feature, I noticed that it is showing data updated x minutes x seconds ago but it isn't updating once a second so the label isn't entirely accurate.

This is on my TODO list but hadn't been ticketed yet - just opened https://github.com/OneBusAway/onebusaway-android/issues/373 for this.

**Comment by barbeau** [comment]
I just pushed https://github.com/OneBusAway/onebusaway-android/commit/88007bbce2d3be1dc09ee61eb26b1064347b4783 to master, which should help with this significantly.  The "Show route on map" button now enables the route as an overlay on your existing map view, instead of kicking you out to a new Activity, and only changes your map view if the current view doesn't include the closest active vehicle on that route.  In that case, it just zooms out slightly so your view bounds includes the closest vehicle as well.  The selected stop remains selected as well.  I'll see if I can get another alpha out soon that includes this as well.

I think there is still room for improvement in the UX and I welcome more feedback, but let's open new tickets for specific improvements after taking a look at the existing improvements.

**Comment by barbeau** [comment]
v2.0.7 alpha is now rolling out, and includes these improvements to the "show route on map" UX:
https://groups.google.com/forum/#!topic/onebusaway-developers/TVeFxo4a22s
