### ISSUE TITLE
Accessibility feedback on UI redesign implementation

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#355]
From https://github.com/OneBusAway/onebusaway-android/pull/177#issuecomment-58111721.  Some of these items we can probably get into the v2.0 release, and some may need to get pushed.  I'll cross off the items in strike-through that are no longer an issue based on current code or new commit tagged with this issue number.

>**TalkBack/Accessibility feedback**:
* There are a few issues with the drawer in the map view:
  * Tapping on the drawer for the first time starts reading the routes, not the stop name/direction. Stop name should be read first, then the direction, then the routes. 
  * ~~Raising/lowering the drawer is confusing. You have to figure out that once it starts reading the routes that you have to double tap to get it to raise/lower, and then there is no indication that it has actually done so. When she was swiping through the elements using TalkBack, it read the elements behind the drawer (the "my location button") and a few stops, so she thought it had lowered when it hadn't, and had difficulty selecting things. Labels/hints on the header would be helpful -- "Drawer raised -- double tap to lower" or something like that.~~ (Fixed in https://github.com/OneBusAway/onebusaway-android/commit/8baa6bbe3e08fa0dac46746d0072112871d316c8 - content description of chevron is now set based on sliding panel state).
  * ~~Lastly, this might be our unfamiliarity with Android showing, but the "Bus options" menu was difficult because finding the back button was at the bottom of the screen which took awhile to navigate to if she accidentally opened the options window. Having a tab that allows you to exit the window without going back would be nice.~~ (This is a no-no from Android design standpoint, and I think most Android users are used to the back button navigation.  If we hear otherwise from a larger group of users we can revisit.)
* ~~Hovering over/tapping on the OneBusAway name in the upper left should also say something about the current view that they are on -- for example, can set the accessibility label for the main screen to "OneBusAway - Home"  (or map, whatever you think is apt to call it). This aids a lot with navigability.~~ (Fixed in https://github.com/OneBusAway/onebusaway-android/commit/246f1d02718332c069f908871ccd39c9694b1a74 - currently selected nav drawer name is now shown in title bar.) 
* ~~From your navigation mockup above, I'm not sure if you were going to put a bookmarks link there as well. Accessing that from anywhere in the app would be great (unless there already is a way, we just didn't find it).~~ (We now have "Starred stops" in the main nav drawer)
* The way it reads arrival times in the table is confusing without contextual information (i.e. seeing the column headers). On OneBusAway we changed this to read more logically as, "Route toward Destination. X minute(s) until arrival/departure at Predicted time - Status." ([iOS code & phrasing here] (https://github.com/OneBusAway/onebusaway-iphone/blob/0c47b5905bcd9c08c7ffe988bb50fc0ca80c5300/controls/table_cells/OBAArrivalEntryTableViewCellFactory.m#L82))
* ~~Really strange, but TalkBack pronounces OneBusAway as "Oh-nay Buse Away" -- pretty hilarious, but I think it should be fixed if possible. Not sure how you'd go about doing that with TalkBack rather than setting the accessibility label to have spaces in between the word whenever it encounters the string without the spaces.~~ (Appears the Talkback team fixed this - it's now pronounced more like "Un Bus Away", which is better)
* ~~Capitalize directions (i.e. "NE" instead of "Ne"), since it currently sounds like the [Knights Who Say Ni!](https://www.youtube.com/watch?v=QTQfGd3G6dg) :)~~ (I don't believe we're currently doing any of these abbreviations in the current UI)

>**Accessibility enhancements**:
* ~~Allowing to search by address is really useful for blind users, who can't navigate the map. (I've also heard it requested by sighted Android OBA users.) Also, kudos on the integrated search and stop list by route! We need to do that in iOS. :)~~ (Ticketed separately in https://github.com/OneBusAway/onebusaway-android/issues/191).
* ~~Showing a list of the stops along with the predicted arrival time for the bus you're currently viewing (i.e. under "Show route information" in "Bus Options") would be really useful accessibility-wise as well (might have brought this up in another thread, I can't remember). For stops that aren't announced over the audio system on the bus, this is helpful for letting the rider know when roughly they should expect to be off the bus. My friend reports using it all the time for that on iOS.~~ (We now have "Show trip status", which is this feature - I just added a few more improvements for Talkback on trip status in https://github.com/OneBusAway/onebusaway-android/commit/b11e761e58ac020348ca467ebe6b47378434b86a).
* ~~One more thing forward to me by a blind Android OBA user is that the saved routes list would delete the bottom-most stop when it got to be pretty full. Because this is the main way that blind users access their stops, it is useful to allow for many entries there. I'm not sure of the exact number he had.~~ (As far as I can tell there is no hard limit on the entries in the recent stops/routes lists, so I'm not sure what happened here.  Maybe user error and accidentally clearing the recent list?)

**Comment by barbeau** [comment]
ccing @caitbonnar on this issue, because we won't let her escape OBA ;).

@caitbonnar I did find some accessibility improvements you had suggested a while back buried in an issue thread based on a very early OBA redesign implementation - I've copied them to the initial post in this issue.  I'm trying to knock off a few of those (as feasible) prior to the 2.0 release - currently I'm striking-through what I think is no longer relevant based on changes since the feedback, and I'm also striking-through items as I add commits that tag this issue.

But, if you get any more accessibility feedback from B/LV users based on the current design prior to v2.0 release, this is currently the catch-all issue for remaining accessibility issues.  Post v2.0, I'll probably tag the remaining potential improvements in individual issues.

**Comment by caitbonnar** [comment]
Hi @barbeau! Sorry for the delay, I was traveling the past few weeks. :) 
Thanks for going through these and noting which ones are taken care of. I'll send an email out to some contacts again and see if I can round up any more feedback for you!

**Comment by barbeau** [comment]
Thanks @caitbonnar, any feedback is appreciated!

**Comment by caitbonnar** [comment]
@barbeau Of course! Are you in beta testing now or still in alpha? I want to make sure I pass on the correct info. :)

**Comment by barbeau** [comment]
New UI is still in alpha at this point, so these are the instructions to follow to download the alpha version:
https://github.com/OneBusAway/onebusaway-android/blob/master/BETA_TESTING.md#register-as-an-alpha-tester

We only have one more major item to knock off (#313 is a tutorial of the new UI) before going to a wider beta.

**Comment by caitbonnar** [comment]
@barbeau Awesome, thanks!

**Comment by barbeau** [comment]
I've managed to knock off most of these.  I'm pulling out the remaining items that aren't making v2.0 to a new issue at https://github.com/OneBusAway/onebusaway-android/issues/416, and am closing this one.

**Comment by caitbonnar** [comment]
Awesome!
