### ISSUE TITLE
Action Bar menu items for main fragments are occasionally duplicated

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#356]
I've noticed that occasionally the Action Bar menu items for the chosen fragment (e.g., "Starred stops") can be duplicated in the list (e.g., "Remove all starred stops" shows up multiple times).  It seems to happen when returning to the app after its been in the background for a while.

We're using the FragmentManager transaction `.show()` and `.hide` to switch between the "Nearby", "Starred Stops" and "My reminders" fragments, instead of `.replace()`.  We aren't using `.replace()` because that causes the loss of state of the "Nearby" map (in `BaseMapFragment`).

To manage the menu for each fragment (because of the above), we're managing the visibility of the menu items in `HomeActivity.onPrepareOptionsMenu()` by setting a menu group visible or not visible depending on boolean flags, tracked when the user switches fragments.  Something doesn't seem to be tracking right.

One note - apparently fragment `.onPause()` events don't fire when using FragmentManager transaction `.hide()`, and fragment `.onResume()` does not fire when using FragmentManager transaction `.show()`.  Instead, the fragment lifecycle is linked directly to the activity (`HomeActivity`), and a separate fragment method `onHiddenChanged(boolean hidden)` is called with `.show()` and `.hide()`.  Not sure if this is related (I discovered this when working on https://github.com/OneBusAway/onebusaway-android/issues/334).

**Comment by bbodenmiller** [comment]
I'm also seeing this. Some screenshots:

![screenshot_20151115-231654](https://cloud.githubusercontent.com/assets/1192780/11176159/2e68e260-8bef-11e5-9ae6-a860fc600e5a.png)

![screenshot_20151115-231658](https://cloud.githubusercontent.com/assets/1192780/11176167/3c821fce-8bef-11e5-83bf-9137293436cf.png)

**Comment by barbeau** [comment]
@bbodenmiller Do you have a set of steps to reproduce this?  It doesn't seem to happen consistently to me.

Also, do you only see this with the "Starred stops" options, or with other options as well?  I believe I've only see it with the "Starred stops" options.

**Comment by bbodenmiller** [comment]
I haven't been able to consistently reproduce yet but it does seem that resuming from running in the background is a factor. I've only seen it on the starred stops view so far. This morning I had three sort by buttons.

**Comment by barbeau** [comment]
I'm hoping this is fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/commit/0a4a67a73f3c53c3ed3647d3a028673a754956e3, but I can't reproduce consistently so I'm not sure.

@bbodenmiller if you can run the `develop` branch and let me know if you see this again, it would be helpful.  I'll see if I can get a new alpha out soon too.

**Comment by bbodenmiller** [comment]
Was this fix included in the 2.0.7 alpha on the play store? If so, it's not fixed. I just got this again:

1. Opened app, it started on starred stops view
2. Clicked starred stop
3. Slept phone (do not recall if I pressed home before sleeping or not)
4. Unslept phone after maybe 10 minutes (do not recall if app reopened or if home screen open and I clicked app)
5. App resumed to stop view
6. Selected back, 2 sort by buttons shown
7. Started this comment in chrome
8. Resumed OBA app, starred view is open and now is showing 3 sort by buttons

**Comment by barbeau** [comment]
@bbodenmiller Thanks - the possible fix https://github.com/OneBusAway/onebusaway-android/commit/0a4a67a73f3c53c3ed3647d3a028673a754956e3 was in v2.0.7 alpha on Play Store, so that means this issue is still happening.  I'm re-opening.  Thanks for the steps to reproduce.

**Comment by barbeau** [comment]
Yeah, I'm pretty sure it has something to do with the app being destroyed and resumed by the Android OS.  I can't reproduce by following the above steps in order without pausing - I'm assuming it's the "slept phone" step that actually causes this.

**Comment by barbeau** [comment]
Ah - so the easy way to reproduce this is to just open the starred stops view, and change your screen orientation from portrait to landscape, or vice versa.  It's an issue with resuming when `savedInstanceState` is not null and a previous instance of the fragment exists.  I'll look into this further.

**Comment by barbeau** [comment]
Ok, this should be fixed for real now:
* If we don't have a reference to a fragment accessible via the nav drawer, check the FragmentManager to see if an instance already exists before we create a new one.
* This fixes an issue with the Starred Stops fragment menu items appearing multiple times (because multiple instances of the fragment were being created), both when the activity was resumed after sleeping, and when changing orientations.
* This should also result in a performance increase, as each fragment doesn't need to be re-instantiated each time before it's shown
