### ISSUE TITLE
Increase size of real-time indicator on stop details header

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-android#364]
I think it'd be good to make the real-time indicator a bit bigger.

**Comment by barbeau** [comment]
@bbodenmiller Can you provide a screenshot of where you'd like to see it larger?  We're using it in several locations.

**Comment by bbodenmiller** [comment]
![screenshot_20151116-084229](https://cloud.githubusercontent.com/assets/1192780/11188079/11a4471a-8c3e-11e5-93cf-1ed55e62e75c.png)

**Comment by bbodenmiller** [comment]
This is certainly debatable however I think it'd be good if the indicator was about 1/3 to 1/4 the size of the number.

**Comment by barbeau** [comment]
The main problem here is that increasing the size starts pushing the ETA left, the way that the layouts are set up.  It also needs to look reasonable with the "NOW" text, which is even bigger than the normal ETA numbers.  I played with this a while and settled on the current size/placement - we're pretty cramped here on space the way it is, so I'm inclined to leave it as-is for now.  If we start getting a large number of user feedback with the same opinion, then we can revisit this.  Or, if someone wants to play with the layouts and open a PR that works for all the above situations, I'd be willing to take a look.
