### ISSUE TITLE
SearchView requires extra back button press to close it

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-android#365]
1. Open app
1. Select nav drawer then starred stops
1. Select back

At this point the app exits when I'd actually prefer for it to just go back to nearby view

Another area to consider is if back should undo your route filters. Currently if you set route filters and click back it does not undo the filters.

**Comment by bbodenmiller** [comment]
Also appears that clicking back after completing a search is taking a few more back clicks than I expected to clear out all the search details.

**Comment by barbeau** [comment]
>clicking back after completing a search is taking a few more back clicks than I expected to clear out all the search details.

Yeah, I agree with this one.  We're using the system SearchView so I'm not sure why that's happening.  I'll actually change this issue to focus on this (see below).

>At this point the app exits when I'd actually prefer for it to just go back to nearby view...Another area to consider is if back should undo your route filters.

When navigating between the main modes in the nav drawer (Nearby, Starred stops, My reminders), IMO back should kill the activity, not switch back to the previously focused mode.  Many Android users are used to hitting Back to kill the app and avoid leaving it run in the background.  The current navigation design allows this, and then the app resumes at the most recently selected mode.  If we change Back button to switch modes, many users will end up accidently transitioning to another mode they didn't intend to navigate to.  Filters don't belong in the backstack either.

The Android best practices docs agree with this.  From http://developer.android.com/training/implementing-navigation/temporal.html:

>Note: You should not add transactions to the back stack when the transaction is for horizontal navigation (such as when switching tabs) or when modifying the content appearance (such as when adjusting filters).

**Comment by bbodenmiller** [comment]
It appears that Google is not following it's own advice. For example open Gmail, select a label, select back - at this point it navigates back to the primary category rather than exciting the app like OBA.

> Many Android users are used to hitting Back to kill the app and avoid leaving it run in the background. The current navigation design allows this, and then the app resumes at the most recently selected mode.

On Marshmallow (maybe others?) when you click the back button enough times the app is closed but not killed.

**Comment by bbodenmiller** [comment]
Another back button difference: in Gmail if you open the nav drawer and then click back, the nav drawer is closed, but in OBA if you open the nav drawer and click back, the app is closed.

In Facebook I'm seeing the same nav drawer behavior as Gmail. Additionally selecting a tab then back is taking me back to the last tab rather than exiting.

Lastly here is a discussion that may help our conversation: http://ux.stackexchange.com/questions/72843/navigation-drawer-and-hardware-back-button-when-on-root-level-exit-app-or-go-b

**Comment by barbeau** [comment]
SearchView back button issue fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/commit/f8627d735126e121c09e1f5c0616463b47b72c37.

**Comment by Jokejiao** [comment]
<argument
    android:name="rootFolderOnly"
    android:defaultValue="false"
    app:argType="boolean" />

The defaultValue set to true and 

BottomSheetPagerAdapter.kt doesn't need
if (position == OFFLINE_INDEX) {
    OfflineFragment.setArgs(fragment as OfflineFragment, true)
}
that would be more tidy and elegant
