### ISSUE TITLE
Show stop nickname and official stop name in the "Stop Details" popup

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-android#368]
It appears that editing a stop name edits it everywhere in the app. I'd like to have a way to see both the stop nickname and realname. For example on iOS you can set the bookmark name but when you click it, it then takes you to the stop which shows the real name.

**Comment by barbeau** [comment]
Given the history in OBA Android of replacing the name entirely I don't think we should change that behavior.  But, we could add both names to the "Stop Details" popup, which is accessible via menu overflow when viewing the stop arrival info.

**Comment by bbodenmiller** [comment]
I think showing both names sounds good.
