### ISSUE TITLE
Selecting edit name does not open keyboard

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-android#369]
Appears that when you select edit name the keyboard is not automatically opened.

**Comment by barbeau** [comment]
Good catch - tapping on stop name to edit does open keyboard, but not selecting "Edit name" from menu.

**Comment by bbodenmiller** [comment]
That tap to edit feature is nice... to bad I didn't know about that feature when I was getting setup last night. Might be a nice feature to highlight in #313.

**Comment by barbeau** [comment]
Fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/commit/c5d3b8d9dbade4237c6084431c78b0dfbed6da61.
