### ISSUE TITLE
Display different vehicle icons per mode

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#411]
Sound Transit is now providing real-time ferry data in their OBA instance, which is awesome.

However, we currently are using the bus icon to represent all vehicles, which results in floating buses:

![image](https://cloud.githubusercontent.com/assets/928045/12227079/361de952-b7f4-11e5-9923-4755d1d205b4.png)

We should change the vehicle icon based on the route mode type.

Here's the API request that returns routes with ferry route types:
http://api.pugetsound.onebusaway.org/api/where/arrivals-and-departures-for-stop/95_7.json?key=TEST

~~~
agencyId: "95",
color: "",
description: "",
id: "95_73",
longName: "Seattle - Bainbridge Island",
shortName: "",
textColor: "",
type: 4,  // <-- This is the "ferry" route type
url: ""
~~~

The GTFS spec defines the following [route types](https://developers.google.com/transit/gtfs/reference?hl=en#routestxt):

>0 - Tram, Streetcar, Light rail. Any light rail or street level system within a metropolitan area.
1 - Subway, Metro. Any underground rail system within a metropolitan area.
2 - Rail. Used for intercity or long-distance travel.
3 - Bus. Used for short- and long-distance bus routes.
4 - Ferry. Used for short- and long-distance boat service.
5 - Cable car. Used for street-level cable cars where the cable runs beneath the car.
6 - Gondola, Suspended cable car. Typically used for aerial cable cars where the car is suspended from the cable.
7 - Funicular. Any rail system designed for steep inclines.

Here's where the current SVG bus vehicle icon files are:
https://github.com/OneBusAway/onebusaway-android/tree/master/icons/vehicle_markers

We can use those as a start for the marker/arrows, and then pull the other material design vehicle markers from:
https://github.com/google/material-design-icons/tree/master/maps/svg/production

...where the naming convention is `ic_directions_*` - for example, here's the boat icon for the ferry:
https://github.com/google/material-design-icons/blob/master/maps/svg/production/ic_directions_boat_48px.svg

...which looks like:

![image](https://cloud.githubusercontent.com/assets/928045/12227144/86fed5ce-b7f5-11e5-8224-b790f50eca80.png)

We can drop these icons on top of the SVG marker/arrow icons and create new mode icons.

**Comment by bbodenmiller** [comment]
"Floating buses"... This is a fun "bug".

**Comment by bendu** [comment]
For completeness, the trip details list shows a bus for the ferries which should also be addressed.

![screenshot_20160703-102753](https://cloud.githubusercontent.com/assets/5668844/16546744/22c570f2-4109-11e6-80bb-e3bb4b049d91.png)

**Comment by barbeau** [comment]
WIP PR at https://github.com/OneBusAway/onebusaway-android/pull/647.
