### ISSUE TITLE
Agency X and Y tutorial colors are wrong

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#420]
For the Agency X and Y demo apps, the tutorial colors are currently shown as green instead of the theme colors for each of these apps - red and blue respectively.  The color, and reference to color in the tutorial text (e.g., "green dots") should be changed for these apps to be the theme colors.

This affects the Agency X and Agency Y demo apps for build flavors, and not the OBA Google or Amazon builds, so it's not an emergency.  It can be fixed and released whenever the next update happens to roll out.

**Comment by barbeau** [comment]
Whoops, forgot to change tutorial text accordingly.  Re-opening.

**Comment by themonki** [comment]
@barbeau I think it is also necessary in the key tutorial_arrival_header_arrival_info_text:

This long! Colored background tells you
        if the bus is early (red) or late (blue). **On time = green background.** If we don\'t know
        where the bus is, the scheduled time is shown (gray background).

On time use the default background color.

For example on Agency Y maybe should say:

This long! Colored background tells you
        if the bus is early (red) or late (**dark blue**).**On time = blue background.** If we don\'t know
        where the bus is, the scheduled time is shown (gray background).

**Comment by barbeau** [comment]
@themonki Ah - good catch.  You're right - re-opening to fix that.

**Comment by barbeau** [comment]
@themonki Ok, this should be fixed in https://github.com/OneBusAway/onebusaway-android/commit/b9872aa9292d4969d427a6580204a9c4348e19f8.  The choice of the arrival time colors isn't the best in the demo apps, as both the blue and red of the theme colors overlap (to some degree) the arrival time early and late colors.  But, I think it at least gets the point across of how the colors can be customized in white-labeled versions of OBA.

**Comment by barbeau** [comment]
@themonki Actually, there should be a `values-es` folder under `src/agencyX/res` and `src/agencyY/res` with a translated `strings.xml` for those build flavors that match `src/agencyX/res/values/strings.xml` and `src/agencyY/res/values/strings.xml`, respectively.  Feel free to tackle if you'd like for Spanish ;).

**Comment by themonki** [comment]
@barbeau Yes, is cool the colors can be customized, but i think for the arrival time colors should be a standard for OBA. Because the user must already be accustomed to seeing these colors.

I send a PR soon for `values-es` for AgencyY and AgencyX.

Furthermore, if the `app_name` key can be change, some string can be change too, for example, i create a brand, only for test, here https://github.com/themonki/onebusaway-android/blob/metrocali/onebusaway-android/src/MIO/res/values/strings.xml

I say the app_name is `OneBusAway MIO`

the `route_shortcut` key should be say `OneBusAway MIO Route`.

I do not know if I made you understand my point.

**Comment by barbeau** [comment]
@themonki Yes, the cool this about rebranding is that minor changes like colors and text can be changed while still sharing the same code base (i.e., you don't even need to fork the project) - and you can still have your own app on the app store.  I'm open to adding more brands to the main OneBusAway project here in the main repo as well, because there would be more incentive for everyone to contribute new features to the same code base.  More info here on rebranding, if you haven't seen it - https://github.com/OneBusAway/onebusaway-android/blob/master/REBRANDING.md.  So if you'd like to merge your new brand into the main project, feel free to open a PR for this.

**Comment by themonki** [comment]
@barbeau is awesome. For now I only testing of the brand concept. Maybe when I implemented some new feature send a PR.

**Comment by barbeau** [comment]
:+1:
