### ISSUE TITLE
Allow hiding header arrival info when using ArrivalsListActivity

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#423]
When selecting starred stop from the "Starred Stops" fragment, or tapping on a home screen shortcut for a stop, users are taken directly to the `ArrivalsListActivity`.  This is the same `ArrivalsListFragment` that's shown in the sliding panel on the map screen, but locked to the top of the screen.  The header containing the two starred routes is arguably less useful here - from a beta user:

>is there any way to hide/remove the top 2 arrivals (e.g. Route 24 and D Line in the screenshot above)? While the new UI looks much prettier, I found it a little bit overwhelming. Perhaps I’m just too used to the old interface :P
>...
>It would be great if users can hide the top 2 arrivals to get more real estate, and to avoid duplicated info (especially when sorting by arrival).

Maybe we can find a way to collapse the header in `ArrivalsListActivity` so it shows only the stop name and star - this would be close to the original presentation in this view in v1.x.

**Comment by barbeau** [comment]
We should also add analytics to this so we know how many users don't want to see the arrivals in the header.

**Comment by barbeau** [comment]
After implementing this, I think it's actually better to have the header arrivals hidden by default in the `ArrivalsListActivity`.  It's much easier to read at a glance and immediately understand what's going on, and its very similar to the original presentation of arrivals in this view for v1.x.  The header arrivals are useful for the ability to star routes and pin them to the header, but that's more advanced functionality that's only useful at stops with a large number of arrivals.  We can add another tutorial screen so the user knows these can be enabled, but for users new to v2.0 of the app, and especially those used to v1.x, hiding the header arrivals is much more gentle introduction to this screen.

**Comment by barbeau** [comment]
For reference, here are the two versions side-by-side:

![image](https://cloud.githubusercontent.com/assets/928045/13410511/364364c8-df06-11e5-93fe-a288c97ba105.png)

**Comment by bbodenmiller** [comment]
In the example shown on the left, how do favorited stops/routes appear? At the top of the list?

**Comment by barbeau** [comment]
The left is basically a collapsed version of the right, and you can switch back and forth using an option in the context menu (3 dots in upper right) or via Settings preference.  When the header is collapsed you just get the normal list of arrivals, sorted by route or ETA.  Starred routes are hidden in the header in this view.  If you looks at the screenshots on Google Play it's very close to the v1.X production release.

I could potentially be convinced to leave the right as the default when viewing starred stops if there is a strong desire from others to do so.  At the moment though I'm erring more on the side of simplicity first based on other user feedback.

**Comment by bbodenmiller** [comment]
I like the left view without the headset best however I'd like my starred stops and routes to appear at the top of the list. I think by default would be best but I could settle for it only being applied if that's the sort option I've selected.
