### ISSUE TITLE
Custom Colors on arrival header for "on time"

### ISSUE THREAD

**Issue by themonki** [OneBusAway/onebusaway-android#429]
I see on [colors.xml#L53](https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/res/values/colors.xml#L53) the **stop_info_ontime** key is using the theme color.

If for example I create a new "brand" and I want to change that value, for example to green (because the theme color is blue dark or red or another), the header show the theme color over **stop_info_ontime** key:

![img_20160229_120440](https://cloud.githubusercontent.com/assets/1817333/13402295/a07fe588-dedd-11e5-886c-42b515d6024a.JPG)

And i see on [ArrivalsListHeader.java#L644](https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/java/org/onebusaway/android/ui/ArrivalsListHeader.java#L644) there is a condition for the header always use the theme color for **on time**:

```java
                if (c1 != R.color.stop_info_ontime) {
                    // Show early/late/scheduled color
                    d1.setColor(mResources.getColor(c1));
                } else {
                    // For on-time, use header default color
                    d1.setColor(mResources.getColor(R.color.theme_primary));
                }
```

I think it makes no sense to have this condition if the color can be customized and by default that is already using the main theme. I don't know if this can be change and it is the only change to do.

Best regards.

**Comment by barbeau** [comment]
@themonki Just to clarify - you'd like to be able to customize both the "on-time" color in the list and in the header, right?

If so I can tweak the resources to allow this.  I initially made the assumption that the "on-time" color in the header would match the header background color (i.e., everything is ok, and its running on time), but I can see how you may need to customize this.

**Comment by themonki** [comment]
@barbeau  I see it is a good proposal that use the background color to indicate the "on time" but I think if another color is used in the **arrivals list** can confuse.

I think the colors should have a meaning like a **semaphore** and if any other transit agency wants to change colors according to those used in their own ETA system.

I propose two scenarios:

1. Remove the stop_info_ontime value and instead use the theme_primary value. This maintains the consistency of your assumption.
2. Use the "stop_info_ontime value" for the header. This allows better customization. It even allows use option 1 to customize because by default uses the theme color.

I like both ideas :). 

Some screenshot using the option 2:

![screenshot_2016-02-29-12-50-14](https://cloud.githubusercontent.com/assets/1817333/13439450/a71f92a6-dfbb-11e5-9b2c-7d3d1d9034b4.png)

![screenshot_2016-02-29-12-51-31](https://cloud.githubusercontent.com/assets/1817333/13439457/b07f201e-dfbb-11e5-8b0d-52ccc469ad98.png)

![screenshot_2016-03-01-14-36-33](https://cloud.githubusercontent.com/assets/1817333/13439475/bdf476d6-dfbb-11e5-86b8-9b916e1b2d40.png)

![screenshot_2016-03-01-14-36-42](https://cloud.githubusercontent.com/assets/1817333/13439478/c4992a54-dfbb-11e5-9685-bb7feaaf5590.png)

What do you think?

**Comment by barbeau** [comment]
@themonki Makes sense - I was thinking something like 2, but actually defining a separate color in colors.xml for the arrival header on time color, which would give you more flexibility.  In this case you could actually set the on time color for the header different from the list if you wanted (or could set them to the same).  I'll work on fixing this.

**Comment by barbeau** [comment]
@themonki Just pushed a fix for this to master branch.  There is now a new color `header_stop_info_ontime` in `colors.xml` that you can override in build variants to customize the header on time color to whatever you want.

For example, if you wanted to simply make is the same color as the on time color used in the list, you'd set it to:
`<color name="header_stop_info_ontime">@color/stop_info_ontime</color>`

**Comment by themonki** [comment]
Cool @barbeau :+1:
