### ISSUE TITLE
Show only departures at first/last stop for loop routes

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#436]
Related to https://github.com/OneBusAway/onebusaway-android/issues/287, but this issue is specifically for loop routes.

Same issue on OBA iOS at https://github.com/OneBusAway/onebusaway-iphone/issues/562.

For the first/last stop on loop routes, we currently show both the arrival and the departure, which is confusing.  For example:

![image](https://cloud.githubusercontent.com/assets/928045/13612857/9787cbc0-e537-11e5-9db4-d59a6077b531.png)

The 32 is arriving in 3 minutes, and departing in 8 minutes.  So, same vehicle, it just has a 5 minute layover.

Via https://github.com/OneBusAway/onebusaway-application-modules/issues/148 and PR https://github.com/OneBusAway/onebusaway-application-modules/pull/149, we now have access to a new API parameter `totalStopsInTrip` on some OBA installations that should help with this.

>* totalStopsInTrip - the total number of stops visited on the trip for this arrival.  If the same stop is visited more than once in this trip, each visitation is counted towards the total.
* stopSequence - the index of the stop into the sequence of stops that make up the trip for this arrival.  This value is 0-indexed, and is generated internally by OneBusAway (it is **not** the GTFS `stop_sequence`).  The first stop in the trip will always have `stopSequence = 0`, while the last stop in the trip will always have `stopSequence = totalStopsInTrip - 1`.

Here is a request for the above stop - you can see the `totalStopsInTrip` field in the response:

http://app1.staging.obahart.org/api/where/arrivals-and-departures-for-stop/PSTA_1767.json?minutesAfter=65&key=TEST

A possible rule to help with this display issue may be to only show departures (and not arrivals) for trips that are in the same block with sequential `blockTripSequence` with the same headsign.  In this case, the top 32 arrival in 3 min would be hidden, while the departure in 8 min would be shown.

**Comment by bbodenmiller** [comment]
Rather than hide the arrival time I think it'd be more valuable to find a way to label them appropriately. Sometimes you want to be able to see the arrival time, such as when you are trying to make a connection and want to see if you can actually make it.

**Comment by barbeau** [comment]
@bbodenmiller Better labeling could definitely help when there is a layover - we'd certainly need this in the unfiltered view anyway (if we choose to automatically filter).

However, I think in the case when there isn't a layover we shouldn't show two different entries in the arrivals list.  A trip without a layover currently appears as two duplicate entries, with same time/delay/ETA.

**Comment by barbeau** [comment]
So after looking at the implementation in #287, I think I've changed my mind on this.

The labeling seems to be enough on loop routes to distinguish back to back arrivals/departures:

![image](https://cloud.githubusercontent.com/assets/928045/14091291/66390012-f50d-11e5-9bdc-1185d9e10acf.png)

Bus was scheduled to arrive at 5:55pm and have a 5 min layover, and depart at 6pm. It's running 6 min late, which means it will eat up the layover time and still depart 1 min late.  This is also an example of an identical arrival/departure time resulting from a delay, even when a layover is scheduled.

So, I'm going to close this as being fixed by #287 for now - if we get a lot of user feedback that they need more clarity on loop routes we can re-open.
