### ISSUE TITLE
Add legend for arrival time colors

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#458]
This has been requested numerous times before, and I'd like to add it along side the work we're doing for issue reporting (https://github.com/OneBusAway/onebusaway-android/pull/392).

We should add a Legend option under "Help", that looks something like this (but obviously much prettier):

![image](https://cloud.githubusercontent.com/assets/928045/14440153/a74627ca-fffc-11e5-9e6c-a7cfe892f5c5.png)

Top circle is the animating real-time indicator we use next to the real-time arrival estimate.

@cagryInside Could you please work on this?  We can get https://github.com/OneBusAway/onebusaway-android/pull/392 merged and released, and then add this after the fact.  So, lower priority than https://github.com/OneBusAway/onebusaway-android/pull/392, but I'd like to get it in the public v2.0 release.

**Comment by barbeau** [comment]
After talking with @cagryInside further, it would be good to show this a little more in context to how users see the colors and animating real-time indicator within the app.

Here's a mockup that's more like what the users see in the app:

![image](https://cloud.githubusercontent.com/assets/928045/14475856/473944da-00d2-11e6-9cfc-9297ede5cc5a.png)

This is also similar in language to [the brochure HART distributed to riders](http://developer.onebusaway.org/tmp/hart/using_oba_phone.pdf) indicating what the colors meant.

**Comment by barbeau** [comment]
Powerpoint file that contains these mockups is [here](https://www.dropbox.com/s/4vexs40ikr05xha/OBA%20Legend.pptx?dl=0)

**Comment by bbodenmiller** [comment]
Shouldn't the gray one not have the dot? Also I vote they be styled exactly the same as the app (no border, same font & size, animated dot, etc.)

**Comment by barbeau** [comment]
@bbodenmiller Whoops, yes, good catch.  I'll fix that.  Yes, these would be styled exactly as they appear in the app - likely the exact same layout.

**Comment by cagryInside** [comment]
@barbeau This is the screenshots of the first implementation:

![device-2016-04-14-122822](https://cloud.githubusercontent.com/assets/2777974/14535636/b81183be-023c-11e6-896a-3dadb1c830dc.png)

What do you think about the layout? I used a scroll layout, because it is a little bit long for horizontal orientation. Also, any comments on text style, maybe non-bold, black color?
![device-2016-04-14-122906](https://cloud.githubusercontent.com/assets/2777974/14535640/bda89254-023c-11e6-9c00-1c4c7cca32ed.png)

**Comment by barbeau** [comment]
Let's put the "Legend" option just below the "Tutorial" option - I'd like to keep the "self-service" options grouped near the top.  Related to this - let's use the following order:

* Show Tutorial
* Legend
* What's New?
* Supported Agencies
* Twitter Feed
* Contact Us

Layout is looking good!  We just need to make sure it looks good on smaller screens and can scroll if needed (and "Close" button is always accessible).  I'd probably need to see at full resolution, but current text color actually looks good to me.

A few comments:

* There is a missing ")" at the end of the scheduled arrival description.
* Maybe a little more padding between arrival time and text?
* Let's change the "10" to "5" - a single digit takes up less horizontal room.
