### ISSUE TITLE
Improve reminder notification implementation

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#493]
**Summary:** 

The reminder notification implementation could use a re-write.  From https://github.com/OneBusAway/onebusaway-android/pull/479#discussion_r62705038 and https://github.com/OneBusAway/onebusaway-android/pull/479#discussion_r62736914, here's a description of the current implementation:

> `TripService` acts as a container service for a thread pool.  The thread pool can contain executing threads for various tasks related to the reminders feature - the `SchedulerTask` (executed when a new reminder is saved, or after boot (via `BootstrapService`) to register all reminders saved in the database with the Android platform), the `PollerTask` (triggered by the platform via `AlarmReceiver` to begin polling the server 30 min ahead of the scheduled time of the arrival for which the reminder is set), the `NotifierTask` (triggered by OBA Android when we should fire a notification for a reminder), or the `CancelNotifyTask` (for when a notification is canceled)....the `PollerTask` actually reschedules itself each time it polls (in `poll1()` line 108), so the `TripService` service could shut down in between polling events.

We seem to synchronize shutting down the service on the `mNotifications` object, which is a `ConcurrentHashMap` in the `TripService`:

> we are holding a reference to current notifications in `mNotifications`...If this HashMap still contains at least one Notification object, it prevents the Service from shutting down if other tasks (e.g., `SchedulerTask`) are still running in Threads in the same service.

This ends up being a fairly complex implementation, with us keeping a Service running and trying to maintain our own Thread pool, and manually shutting down the Service IFF all Threads stop executing.  If there is an error in this implementation and one of the Threads accidentally requests that the Service shut down while other Threads are still running, those Threads would be terminated prior to completing their execution.

It seems like a simpler design for this that is less prone to multi-threading and synchronization issues is to have each of the above tasks run in their own [`IntentService`](http://developer.android.com/reference/android/app/IntentService.html).  The `IntentService` should automatically shut itself down when the thread completes its task.  However, we need to look closely at the shared data requirements between the tasks - if they share data in memory (beyond just synchronizing when to shut down the Service on the `mNotifications` object), then we'd need to look at another solution that allows this.

**EDIT Nov 2018** - With Android 8.0 background execution limits, [`JobIntentServices`](https://developer.android.com/reference/android/support/v4/app/JobIntentService) are now recommended instead of `IntentService`.  See comment below.

Would also be great to have some unit tests in place before we do a new implementation, so we can verify whether or not the current implementation is always behaving correctly, and to verify that our new implementation also behaves correctly.

**Steps to reproduce:** 

Set a notification for an arrival time.

**Expected behavior:** 

Notifications always behave correctly.

**Observed behavior:** 

We really don't know if the current implementation always works correctly - no complaints from users to date to my knowledge, but it may not always be obvious that something is failing (e.g., if a Scheduling task prevents a Polling or Notification task from fully executing in an iteration, but the next iteration succeeds).

**Device and Android version:** 

N/A

**Comment by barbeau** [comment]
In our `AlarmReceiver`, we should be extending the support library version of `WakefulBroadcastReceiver` and starting the service using `startWakefulService()`, instead of a normal `BroadcastReceiver` and managing the WakeLock ourselves.  See https://developer.android.com/training/scheduling/wakelock.html under *Using WakefulBroadcastReceiver* for details.

**Comment by barbeau** [comment]
In the Android 8.0 ["Background Execution Limits"](https://developer.android.com/about/versions/oreo/background), it now says:

>Note: IntentService is a service, and is therefore subject to the new restrictions on background services. As a result, many apps that rely on IntentService do not work properly when targeting Android 8.0 or higher. For this reason, Android Support Library 26.0.0 introduces a new JobIntentService class, which provides the same functionality as IntentService but uses jobs instead of services when running on Android 8.0 or higher.

So we shouldn't use IntentService, but use JobIntentService instead.

**Comment by barbeau** [comment]
It seems like JobIntentService may not be good for our purposes.  The docs:
https://developer.android.com/reference/android/support/v4/app/JobIntentService

say:

>When running as a pre-O service, the act of enqueueing work will generally start the service immediately, regardless of whether the device is dozing or in other conditions. When running as a Job, it will be subject to standard JobScheduler policies for a Job with a setOverrideDeadline(long) of 0: the job will not run while the device is dozing, it may get delayed more than a service if the device is under strong memory pressure with lots of demand to run jobs.

If it doesn't start immediately, we can't guarantee that we can check arrival times and notify the user in a timely manner after the AlarmManager triggers.  So maybe our existing Service, being in the foreground now, is the best solution...

**Comment by amrhossamdev** [comment]
Fixed: #1258
