### ISSUE TITLE
Update Spanish translation - arrays.xml

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#507]
@themonki Sorry!  I completely missed the changes to `arrays.xml` in the last issue I opened.

If you have a chance soon, here are the strings we'd need to translate:

`arrays.xml`

~~~
    <string-array name="main_help_options">
        <item>Show Tutorial</item>
        <item>Legend</item>
        <item>What\'s New?</item>
        <item>Supported Agencies</item>
        <item>Twitter Feed</item>
        <item>Contact Us</item>
    </string-array>

    <string-array name="main_help_options_no_contact_us">
        <item>Show Tutorial</item>
        <item>Legend</item>
        <item>What\'s New?</item>
        <item>Supported Agencies</item>
        <item>Twitter Feed</item>
    </string-array>

    <string-array name="report_stop_problem_code">
        <item>Choose a problem</item>
        <item>Stop name is wrong</item>
        <item>Stop number is wrong</item>
        <item>Location is wrong</item>
        <item>Route or trip is missing</item>
        <item>Something else</item>
    </string-array>
    <string-array name="report_trip_problem_code_bus">
        <item>Choose a problem</item>
        <item>The bus never came</item>
        <item>It came earlier than predicted</item>
        <item>It came later than predicted</item>
        <item>Wrong destination shown</item>
        <item>The bus doesn\'t stop here</item>
        <item>Something else</item>
    </string-array>

  <!-- Issue reporting -->
    <string-array name="report_types">
        <item>@string/rt_customer_service</item>
        <item>@string/rt_infrastructure_problem</item>
        <item>@string/rt_arrival_problem</item>
        <item>@string/rt_app_feedback</item>
        <item>@string/rt_ideas</item>
    </string-array>
    <string-array name="report_types_desc">
        <item>@string/rt_message_customer_service</item>
        <item>@string/rt_message_infrastructure_problem</item>
        <item>@string/rt_message_arrival_problem</item>
        <item>@string/rt_message_app_feedback</item>
        <item>@string/rt_message_ideas</item>
    </string-array>

    <array name="report_types_icons">
        <item>@drawable/ic_customer_service</item>
        <item>@drawable/ri_flag_triangle</item>
        <item>@drawable/ic_arrival_time</item>
        <item>@drawable/ic_app_feedback</item>
        <item>@drawable/ic_light_bulb</item>
    </array>

    <string-array name="report_types_without_open311">
        <item>@string/rt_customer_service</item>
        <item>@string/rt_stop_problem</item>
        <item>@string/rt_arrival_problem</item>
        <item>@string/rt_app_feedback</item>
        <item>@string/rt_ideas</item>
    </string-array>

    <string-array name="report_types_desc_without_open311">
        <item>@string/rt_message_customer_service</item>
        <item>@string/rt_message_stop_problem</item>
        <item>@string/rt_message_arrival_problem</item>
        <item>@string/rt_message_app_feedback</item>
        <item>@string/rt_message_ideas</item>
    </string-array>

    <array name="report_types_icons_without_open311">
        <item>@drawable/ic_customer_service</item>
        <item>@drawable/ri_flag_triangle</item>
        <item>@drawable/ic_arrival_time</item>
        <item>@drawable/ic_app_feedback</item>
        <item>@drawable/ic_light_bulb</item>
    </array>

    <string-array name="report_stop_issue_tutorial_desc">
        <item>Click on the bus stop, that you want to report.</item>
        <item>Then select report problem section from options.</item>
        <item>Submit your bus stop related problem.</item>
    </string-array>

    <string-array name="report_stop_transit_category_keywords">
        <item>transit</item>
        <item>bus</item>
        <item>stop</item>
    </string-array>

    <string-array name="report_trip_transit_category_keywords">
        <item>trip</item>
        <item>arrival</item>
        <item>schedule</item>
    </string-array>

    <string-array name="report_stop_id_field_keywords">
        <item>stop</item>
        <item>id</item>
        <item>bus</item>
    </string-array>
~~~

**Comment by barbeau** [comment]
Actually, I'm not entirely sure that the string arrays with `keywords` in the name should be translated.

@cagryInside With the Open311 implementation, does the user's locale affect what language is returned to them?  I don't believe it does.  If English is always going be returned, we should probably move these string arrays to `donottranslate.xml`.  Please take a look and let me know what you think.

**Comment by cagryInside** [comment]
> Actually, I'm not entirely sure that the string arrays with keywords in the name should be translated.
> 
> @cagryInside With the Open311 implementation, does the user's locale affect what language is returned to them? I don't believe it does. If English is always going be returned, we should probably move these string arrays to donottranslate.xml. Please take a look and let me know what you think.

@barbeau I think we should leave them in the `arrays`. We are comparing `report_stop_transit_category_keywords` and `report_trip_transit_category_keywords` with the actual service name or category name (which are UI elements). For example, in Spain if they add an open311 endpoint for their agency, it is expected to have a Spanish service names.

**Comment by barbeau** [comment]
@cagryInside Yeah, that's a good point.  I was thinking that if someone was using a foreign locale in the U.S. then the Spanish translation would never match the English response returned from the Open311 API (e.g., SeeClickFix in Pinellas County).  I guess we can only support one of the two scenarios at this point - I agree that between the two scenarios, we should probably leave them in `arrays.xml`.

Open311 spec doesn't currently seem to have any concept of translations - section on internationalization and enconding only defines date/time format and UTF-8 requirement:
http://wiki.open311.org/GeoReport_v2/#internationalization-and-encoding

Here's an old discussion re: translation support, but from a quick skim it doesn't seem like they came to any conclusion:
http://lists.open311.org/groups/discuss/messages/topic/4DB0mXIAUNXMWSrqcbaKE2

@themonki Ok, let's go ahead and translate everything at the top of this issue, including the string arrays with `keyword` in the name.

**Comment by themonki** [comment]
@barbeau currently [array.xml](https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/res/values-es/arrays.xml) was translated a part on spanish.

About the string 'keyword' you say translate the item values? for example:
```xml
    <string-array name="report_stop_transit_category_keywords">
        <item>transit</item>  ---> translate
        <item>bus</item> ---> translate
        <item>stop</item> ---> translate
    </string-array>
```

And not translate anything here (for example):

```xml
    <string-array name="report_types">
        <item>@string/rt_customer_service</item>
        <item>@string/rt_infrastructure_problem</item>
        <item>@string/rt_arrival_problem</item>
        <item>@string/rt_app_feedback</item>
        <item>@string/rt_ideas</item>
    </string-array>
```

**Comment by barbeau** [comment]
@themonki Yes, the "keyword" strings should be translated:

~~~xml
<string-array name="report_stop_transit_category_keywords">
        <item>transit</item>  ---> translate
        <item>bus</item> ---> translate
        <item>stop</item> ---> translate
</string-array>
~~~

And yes, the strings that reference other strings should just be copied into `values-es/arrays.xml`, without any changes/translation:

```xml
    <string-array name="report_types">
        <item>@string/rt_customer_service</item>
        <item>@string/rt_infrastructure_problem</item>
        <item>@string/rt_arrival_problem</item>
        <item>@string/rt_app_feedback</item>
        <item>@string/rt_ideas</item>
    </string-array>
```
