### ISSUE TITLE
"Send feedback" screen text needs more padding for longer languages

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#512]
**Summary:** 

When tapping on "Send feedback" in the main navigation drawer, the activity that shows all the different categories for feedback is very cramped for languages with longer strings (e.g., Spanish).

**Steps to reproduce:** 

1. Change your Android settings to Spanish via "Settings->Language & keyboard->Espanol (United States)"
1. In OBA in main navigation drawer, tap on "Send feedback" (or "Enviar comentarios" for Spanish)

**Expected behavior:** 

A list of feedback categories with sufficient padding surrounding the text should be shown, as is shown in the English version:

![image](https://cloud.githubusercontent.com/assets/928045/15549475/b1e462dc-227a-11e6-83e8-755d2a5e0d79.png)

**Observed behavior:** 

The list of feedback is cramped without sufficient padding around some of the text, as is shown in the Spanish version:

![image](https://cloud.githubusercontent.com/assets/928045/15549614/7112a6c8-227b-11e6-9fca-f1b91e416087.png)

**Device and Android version:** 

Stock LG G4 w/ Android 6.0

**Screenshots:** 

See above.

**Comment by cagryInside** [comment]
@barbeau I will tackle this.

**Comment by barbeau** [comment]
@cagryInside Awesome, thanks!

**Comment by themonki** [comment]
Need to change [here](https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/res/values-es/strings.xml#L589)

* <string name="rt_customer_service">Contactar con el Servicio de **Atneción** al Cliente</string>

for

* <string name="rt_customer_service">Contactar con el Servicio de **Atención** al Cliente</string>

**Comment by barbeau** [comment]
@themonki Thanks!  Just fixed that type in https://github.com/OneBusAway/onebusaway-android/commit/ccd07ee345d720d85f137d25d029c628d2576b33.
