### ISSUE TITLE
Main navigation panel can not scroll in landscape orientation

### ISSUE THREAD

**Issue by themonki** [OneBusAway/onebusaway-android#520]
**Summary:** 

When I change my device on horizontal view the menu look cut and I can't scroll down to see all options on the menu.

**Steps to reproduce:** 

1. Open onebusaway 
2. Change the position of my device to horizontal 
3. Open the principal menu 

**Expected behavior:** 

Scroll down and see all options on the menu 

**Observed behavior:** 

The menu look cut and can not scroll down to see all options 

**Device and Android version:** 

Xperia Z3 Compact (D5803)
Manufacturer Sony 
Android version Android 6.0.1
RAM (MB) 2048 
Screen size 720 × 1280 
Screen density (dpi) 320 
OpenGL ES version 3.0 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model MSM8974AC
Google Play Services 9.0.83
**EDIT** Onebusaway Android version 2.0.11

**Screenshots:** 

![screenshot_20160526-201507](https://cloud.githubusercontent.com/assets/1817333/15594860/53211c76-237f-11e6-954b-73904d1c6f27.png)

![screenshot_20160526-201512](https://cloud.githubusercontent.com/assets/1817333/15594866/5cb1e4b4-237f-11e6-856f-a4571863cf41.png)

**Comment by barbeau** [comment]
@themonki Thanks for the report!  I agree that we need to fix this.

**Comment by cagryInside** [comment]
I am working on this issue.
