### ISSUE TITLE
Add route icon

### ISSUE THREAD

**Issue by cagryInside** [OneBusAway/onebusaway-android#539]
**Summary:** 

We want to add a specific route icon in `Issue reporting` and `Recent stops/routes` screens.

**Screenshots:** 
Currently we are using generic icons to indicate routes:

`Issue Reporting`:

![device-2016-06-14-100259](https://cloud.githubusercontent.com/assets/2777974/16045713/b50c70b0-3217-11e6-945f-a0d20e38775b.png)

`Recent stops/routes`:

![device-2016-06-14-100330](https://cloud.githubusercontent.com/assets/2777974/16045729/c159cd0e-3217-11e6-8f39-81a905b4adc9.png)

**Comment by cagryInside** [comment]
A material design icon:

1)
![routes](https://cloud.githubusercontent.com/assets/2777974/16046190/894f5292-3219-11e6-8bfd-dbb9b5610d9c.png)

Or, non-material design icons, I think we can materialize them using http://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.space.trim=1&foreground.space.pad=0&foreColor=607d8b%2C0&crop=0&backgroundShape=square&backColor=ffffff%2C100&effects=none

2)
![noun_14382](https://cloud.githubusercontent.com/assets/2777974/16046270/d676a282-3219-11e6-9ad3-aded75ff8748.png)

3)

![noun_41139_cc](https://cloud.githubusercontent.com/assets/2777974/16046430/753d48f8-321a-11e6-8c3a-ecd6476a921b.png)

4)
![noun_50531](https://cloud.githubusercontent.com/assets/2777974/16046438/7a40846e-321a-11e6-868b-0d92721c7514.png)

5)
![noun_106553_cc](https://cloud.githubusercontent.com/assets/2777974/16046456/8914fd6c-321a-11e6-85ba-dceb85be090c.png)

I would prefer the first one, it is more compact

**Comment by barbeau** [comment]
Conceptually I've always thought that this should be something like a curved S, closer to number 4 above, but a much more compact representation.

I think 1) is good but too close to the icon we're already using for stops:
![image](https://cloud.githubusercontent.com/assets/928045/16052733/7ce26a48-3233-11e6-858d-9f1ea335f1f2.png)

An easy solution would be to just re-use the icon we are currently using for "Show trip status":

![image](https://cloud.githubusercontent.com/assets/928045/16052755/9c6e1484-3233-11e6-96e2-e4c89c476dfa.png)

...or a horizontal version of that same line.  I had to create that icon from scratch as I couldn't find anything like it.

**Comment by cagryInside** [comment]
I re-used the icon we are currently using for "Show trip status":
@barbeau what is your thoughts?
 
![device-2016-06-16-130449](https://cloud.githubusercontent.com/assets/2777974/16126273/6af9048e-33c5-11e6-9c6d-e85160ff23be.png)
![device-2016-06-16-132202](https://cloud.githubusercontent.com/assets/2777974/16126274/6afdbfe2-33c5-11e6-89bf-b5c6b8732c06.png)

**Comment by barbeau** [comment]
:+1: Works for me :).  We can revisit this later if we need another route icon and the trip status one doesn't work in that use case.
