### ISSUE TITLE
Improve Trip Status vehicle icon

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#548]
The vehicle icon in `TripDetailsListFragment` (accessible by tapping on vehicle marker balloon, or tapping on an arrival time and then "Show trip status") currently looks like this:

![image](https://cloud.githubusercontent.com/assets/928045/16156326/b58c1e98-3481-11e6-85ef-43abe1f18d2f.png)

I'd like to change it to be a white bus icon inside of a colored circle, similar to the vehicle map markers:

![image](https://cloud.githubusercontent.com/assets/928045/16156361/e33b8716-3481-11e6-8936-73b92e293138.png)

I suppose the animating dot would remain above the circle, unless it fits in between the top of the bus and top of the circle.

IIRC I originally started trying to implement this using XML `<layer-lists>`, but ran into some problems getting the layout to work correctly, and dynamically re-coloring the circle, although I didn't spend a lot of time on it.  If we can't do this in XML, we can use the same process as the vehicle map markers - we generated markers in black with white buses, and then dynamically recolor the black part of the bitmap.  See `VehicleOverlay.getVehicleIcon()` and `UIUtils.colorBitmap()` for that implementation.

SVG files for the vehicle marker icons are in this repo, in the `/icons/vehicle_markers` folder.  We can use these to create an SVG file with the circles and bus icon inside, and then translate those SVGs to the PNGs for the app using [Android Icon Generator](https://romannurik.github.io/AndroidAssetStudio/icons-generic.html#source.space.trim=1&source.space.pad=0&size=24&padding=0&color=000%2C100&name=ic_example).

**Comment by Pokechu22** [comment]
I'm interested in trying to implement this (along with using the proper icons for the mods of transport &rarr; right now it's always the bus icon).  I've done a basic implementation using the existing markers and `UIUtils.colorBitmap`, but ![that image really doesn't fit well](https://user-images.githubusercontent.com/8334194/46511728-19eaa580-c805-11e8-82a7-3a2319f0d07f.png).  I'm guessing that I'd want to create proper circle icons instead, but I'm not 100% sure how to go about doing that -- where are the templates that were used originally?

**Comment by barbeau** [comment]
@Pokechu22 Thanks for working on this!  SVG files for the vehicle marker map icons are in this repo, in the /icons/vehicle_markers folder.

The current bus icon used on the status screen I believe was a direct export from Android Asset Studio to PNGs:
https://romannurik.github.io/AndroidAssetStudio/icons-generic.html#source.type=clipart&source.clipart=directions_bus&source.space.trim=1&source.space.pad=0&size=32&padding=4&color=rgb(0%2C%200%2C%200)&name=ic_directions_bus

You can get SVGs for the bus and other icon modes from the Material Design site:
https://material.io/tools/icons/?search=directions&style=baseline

I was hoping, though, we could avoid importing another set of PNGs for the vehicle icon overlaid on circles, and just use the existing PNGs in the project like `ic_maps_directions_bus` (see `DirectorsGenerator.getModeIcon()` for the other mode plain black PNGs that are already in the project) and use an XML or vector drawable to overlay the vehicle image on a circle.  This way we aren't going crazy adding more PNGs for every presentation of the icon in the app, which quickly adds to the app size.
