### ISSUE TITLE
Map doesn't automatically recenter on last map position on fresh startup

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#551]
**Summary:** 

First reported in #525:

>Without location on, this app seems to think I'm in the middle of Africa. It also seems to glitch out and lose my spot every time I open it and while I'm actively using it.

Also reported by another user:

>every time I start the app it puts my location on the equator somewhere near Nigeria. (I assume that it's 0 lat, 0 long.)

>I'm in the Puget Sound region and the app remembers that so it asks if I want to move there or stay in the middle of the Atlantic Ocean. I take the offer to move and I then see the entire Puget Sound region and have to zoom in to find Seattle. Why can't it just remember my last location like the last version?

>I keep GPS turned off because a) it drains my battery, b) doesn't work in my office building anyway, c) I don't need to be tracked everywhere.
>I see the new 'starred stops' option, which is great, so I'm using that but simply remembering my last view in the app is more likely to be useful than 'somewhere off the coast of Africa'.  I think that your assumption that everyone has GPS or has it always turned on is OK but when it's not turned on you need a better fallback.

I think the behavior reported above is a bug, but I'm not yet sure if it's with OBA Android or Maps API v2.  It may be that we didn't sufficient test with location services off in the situation where the app completely gets killed by the user or platform.

So, separate from the enter being able to enter a home zip code to set their position, we should revert to the same map position as the user last saw in the app when they do a fresh start up of the app.

cc @azizmb9494 as he's been working on the implementation of #525 in PR #527.  I think the behavior we probably want in #527 is that if the user enters a zip code and hits the "My location" button, we re-center over the zip code.  If the user doesn't hit "My location," then we want to duplicate their previous view of the map when they last closed the app.

**Steps to reproduce:** 

Not certain, but I assume:

1. Kill the app completely
1. Turn off location services on the phone
1. Start up the app

**Expected behavior:** 

Map should center on the most recent map position, with the previous zoom level - this was the behavior of v1.x.

**Observed behavior:** 

Map re-centers on lat/long (0,0) with a world-level zoom level

**Device and Android version:** 

* Device Galaxy Note4 (trltetmo), App version 62 (2.0.12), OS Android 5.1
* App Version: 2.0.13, Model: SM-G386T, OS Version: 4.4.2 / 19

**Comment by azizmb9494** [comment]
Would simply storing the lat & lng of the last location in shared preferences then pulling when needed suffice?

**Comment by barbeau** [comment]
I think so.  We'll need to test this carefully because I believe Google
Maps does retain its own state information, and we don't want to be
fighting their implementation or moving the camera/zoom unnecessarily.

**Comment by barbeau** [comment]
I'm taking a shot at fixing this, should have a WIP PR soon.

**Comment by barbeau** [comment]
WIP PR at https://github.com/OneBusAway/onebusaway-android/pull/557.

**Comment by barbeau** [comment]
Reported by another user on Google Play:

>The new update continues to say I am out of range even when I have location set on. It keeps thinking I am in the middle of Africa and have answer dialogue box each time I got into app even though my region is set in app. Please fix.

**Comment by barbeau** [comment]
Reported by another user via email:

>I hate that the app update has changed such that it no longer stays in the map area that I was last viewing.  This means that I have to pick Puget sound region every time and zoom into my area.  I do not want to have to have my phone's GPS on constantly because it eats battery and data!  Can there be a setting for staying in a region without having to confirm every time?
