### ISSUE TITLE
Improve discovery of the "vehicles on map" feature

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#553]
**Summary:** 

I've gotten feedback from several users using v2.0.13 that they'd like to see buses on the map - for example:

> As an aside, I'd love to see a real time bus tracker similar to watching an uber car arrive. It would be nice to see an approximation of where the arriving bus is at any given moment.

This feature already exists - you can see it currently by tapping on the arrival time, and selecting "Show route on map".  However, some users definitely aren't discovering this on their own.

We have a few options for helping with this:
1. **Rename the current option from "Show _route_ on map" to "Show _vehicles_ on map"** - This is the simplest change, and if users are tapping on arrival times, probably the most obvious.  We kept the original text from v1.x, and users may be assuming no change in functionality.
2. **Add another tutorial screen** - We originally had a tutorial screen via ShowcaseView for this feature, but pulled it as part of the effort to scale back tutorials based on user feedback (https://github.com/OneBusAway/onebusaway-android/issues/526).  Maybe it would be worth adding the tutorial screen for this back in.

I've been waiting to update the app screenshots on Google Play until we get past the 50% rollout mark, so highlighting an image there showing vehicle markers on the map should make it more obvious that this feature exists as well.

**Comment by bendu** [comment]
There used to be this app called BusDrone (don't know if it still exists/works), that showed all of the buses on a map. It would be cool to have a layer which could be toggled to show all of the buses at once, not just a particular route.

**Comment by barbeau** [comment]
@bendu Yes, showing all buses would be nice.  Main limitations here are that a) it would require multiple API calls - basically number of routes in viewport + 1 (call routes-for-location with viewport bounds, and then trips-for-route for each route returned - unless there is another way I'm forgetting), and b) a potentially large number of markers on the map, especially if we add the vehicle markers on top of the stop markers we already show.  Performance of Google Maps with a large number of markers seems to me to have gotten worse over time, although I don't have any data to prove that.  a) and b) together could significantly degrade UX, so we'd need to be sure to test on lower-end devices on 3G connections to make sure we aren't completely killing the experience.
