### ISSUE TITLE
Allow for changing the sort order for stops and routes

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#6]
Either that or just change it to be alphabetical -- I'm not sure if anyone actually gets the current sorting mechanism.

**Comment by barbeau** [comment]
Fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/commit/9a221082bcaae85f710265c5b8c25c2eef21e495.

**Comment by barbeau** [comment]
Will open another issue specific to routes
