### ISSUE TITLE
UI freezes for a few seconds when loading About screen

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#600]
**Summary:** 

Google must have added a lot of text to the mandatory license display information, as now when we start up the AboutActivity it freezes for a few seconds while this text is loaded into the TextView.

For a workaround we can show a progress dialog while the text is being loaded.

**Steps to reproduce:** 
1. Tap main navigation menu
2. Tap Settings
3. Tap About (near bottom)

**Expected behavior:** 

Load the About text, and either be immediately scrollable or show me a progress indicator that something is being loaded

**Observed behavior:** 

UI freezes for a few seconds while the Google OSS license information is loaded

**Device and Android version:** 

I repro'd on stock LG G4 w/ Android 6.0, but this likely happens on any device with Google Play Services installed.

**Comment by therajanmaurya** [comment]
I googled about the slow loading of Google Licence and find we have to load the Licence in Asynctask.
Reference : http://stackoverflow.com/a/28730299/3176277

**Comment by barbeau** [comment]
AsyncTask would work as long as we show a progress bar.  I tried putting it in a handler with postdelayed(), (to avoid blocking onCreate()) but that didnt help.  Latency seems to come from  TextView.setText().

**Comment by barbeau** [comment]
Turns out an AsyncTask doesn't work here either, because you can't modify the UI from a background thread, so you must do TextView.setText() on the UI thread, which always results in freezing.

There is an open issue about the amount of text that `getOpenSourceSoftwareLicenseInfo()` returns here:
https://code.google.com/p/gmaps-api-issues/issues/detail?id=8660

**Comment by barbeau** [comment]
Implementation here using AyncTask - https://github.com/CUTR-at-USF/onebusaway-android/tree/600-AboutActivity.

**Comment by barbeau** [comment]
I commented on the above maps-api issue as well, offering OBA as code to reproduce the problem:
https://code.google.com/p/gmaps-api-issues/issues/detail?id=8660#c5

**Comment by barbeau** [comment]
I'm closing this as "Won't fix" for now, and if there are any updates on the maps-api issue that could enable action on our part I'll re-open.  I don't know of a way to fix this in our application - if anyone does, or has a better idea, please let me know.

**Comment by barbeau** [comment]
Re-opening - according to comment #9 by Google at https://issuetracker.google.com/issues/35827189, we are no longer required to call the license method:

>Thanks for the reports of this issue. Good news. Users can now see all of the license information for Google Play Services by going to Android Settings > Google > Overflow menu > Open Source Licenses on their device. Since that is the case we have removed the attribution requirements for developers using the Google Maps Android API. You no longer have to call GoogleApiAvailability.getInstance().getOpenSourceSoftwareLicenseInfo() and show that text in your app.

So we can just remove this code, which should fix the freeze in the About screen.
