### ISSUE TITLE
Allow changes to "My reminders" notification sound, volume, and vibration

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#609]
**Summary:** 

Feedback from a user:

> Ideally, I would like to set a custom alert sound and volume. I would expect these options to be either in Settings (best) or at top right menu on set notification page.

I believe we currently just use the default system setting for generic notifications.

We should also allow activation/disabling of vibration - IIRC we have a permission for vibration in the manifest, but the code is currently commented out (not sure why?).

**Steps to reproduce:** 
1. Tap on "My reminders" option in navigation panel
2. Tap on a reminder

**Expected behavior:** 

Allow me to change the reminder notification settings

**Observed behavior:** 

You can't change the reminder notification settings

**Device and Android version:** 

N/A

**Comment by barbeau** [comment]
Another user request for this, via Ideascale - http://onebusaway.ideascale.com/a/dtd/Notifications/537373-8715:

>I like the "set alarm" notification, but an additional customization option would be nice so that I can hear the notification. My default tone is not very loud (on purpose), I would set this app to have a louder notification tone - if I could set that.

**Comment by bridgette** [comment]
I also noticed that we had some old commented-out vibration code 🤔
I'll take a look

**Comment by barbeau** [comment]
I moved the custom volume notification request to https://github.com/OneBusAway/onebusaway-android/issues/802 as that's not covered in https://github.com/OneBusAway/onebusaway-android/pull/801.
