### ISSUE TITLE
Trip planner notification loop

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#617]
**Summary:** 

When planning a trip and just letting my phone sit on the trip planning screen, it ended up notifying me continuously that my trip was no longer recommended, even after I tapped on the notification.

**Steps to reproduce:** 

Using `master` branch:
1. Plan a trip
2. Leave the screen on and wait until you get a notification that this trip is no longer recommended
3. Tap on the notification

**Expected behavior:** 

I would expect the trip plans to refresh and give me the newly recommended trip as my highlighted choice in the tabs.

**Observed behavior:** 

It doesn't seem to do anything, and triggers the the notification again.  This results in an infinite loop, as every time I'd tap on the notification it would generate another one.  The only way to stop the notification is to swipe it away to ignore.

As a user it's not clear to me what exactly is happening when I either tap on the notification or swipe it away.

**Device and Android version:** 

Stock LG G4 w/ Android 6.0

@sdjacobs Could you please take a look at this?

**Comment by sdjacobs** [comment]
As currently implemented, all that tapping on the notification will do is open up TripPlanActivity. So I think you're seeing intended behavior, not a bug, though you've convinced me that the current behavior is unintuitive. 

What do you think tapping should do? I agree that it should cancel the notifications. I'm not sure about replanning the trip - I might be confused as a user if when I went back to the results page, the results had changed without me explicitly doing anything. Also, replanning the same trip requires a few assumptions about the user's behavior. They might want to change the time (if they haven't left yet) or the location (if they have). The notifications are based on querying OTP with the exact same parameters.

**Comment by sdjacobs** [comment]
Oh, I see the bug you're talking about now. Hadn't noticed that. It's very odd: if I wait for the notification to go to the background, then look at it again and press it, I don't see the looping behavior - it's only if I press the notification immediately. I'll poke at this some more.

**Comment by barbeau** [comment]
>What do you think tapping should do

IMHO, the problem with the notification is that we tell the user "Your current trip is no longer recommended", but we don't tell them why, and we don't show them an alternative that is recommended.  I think we should do at least one of the two, and for the 2nd, we can say what changed (e.g., "We've updated your trip plan with the current time"), or something similar.  Or in the notification we could say "Tap here to see a new trip plan based on the current time."

I think a notification based on change in schedule deviation is much easier to explain to the user - for example, "Your bus changed from being on-time to 10 minutes behind schedule.  Tap here to see new trip options."

**Comment by sdjacobs** [comment]
Currently there are two types of notifications that users get:

1) If an itinerary's end time has changed by two minutes: "Your trip is delayed / Your trip is early." (Note this means early or late with respect to the original time of the itinerary, not wrt scheduled time).

2) If an itinerary does not appear in the list of returned itineraries: "Your trip is no longer recommended for this route."

Based on your comments above, I could
- add text in both notifications "Tap here to see a new trip plan", and show the new results
- set the parameter "numItineraries" in the repeating OTP requests, in the hopes of reducing case 2. (Unfortunately when case 2 happens, we won't know why OTP did that.)
- maybe change the notifications text to be more clear?

Thoughts?

**Comment by barbeau** [comment]
For Notification type 1), I'd like to see us explain exactly what changed to the user.  So something like "Route 5 changed from being 5 min late to 10 min late.  Tap here to see a new trip plan".

>add text in both notifications "Tap here to see a new trip plan", and show the new results

Yes, I think that's a good idea.

>(Unfortunately when case 2 happens, we won't know why OTP did that.)

I think this gets to the root one of my main issues with this type of notification - if we don't know why something changed and this route is no longer recommended, how can we expect users to make sense of our notification or new trip plans that we show them?  We can see what users say, but my feeling is that this notification is going to cause a lot of confusion.

With that being said, I think you're proposing that we just check to make sure that the trip plan that was originally planned is still valid - in other words, you could still follow the original directions and still get to your destination?

**Comment by sdjacobs** [comment]
> For Notification type 1), I'd like to see us explain exactly what changed to the user. So something like "Route 5 changed from being 5 min late to 10 min late. Tap here to see a new trip plan".

Makes sense. This is a little different than the meaning of delayed/early as currently implemented, which is just the final end time of the itinerary (since you may be taking one transit leg that's late, then the next one is early, then the next one is on time...). But we can just go through the transit legs and notify on the first one that has changed more than 2 minutes.

> I think this gets to the root of one of my main issues with this type of notification - if we don't know why something changed and this route is no longer recommended, how can we expect users to make sense of our notification or new trip plans that we show them? We can see what users say, but my feeling is that this notification is going to cause a lot of confusion.

Yes, this is a good point. I just don't know what the alternative is if OTP does not return your selected itinerary. Just cancel out the updates without notifying the user? Keep requerying and hope it shows up again? Perhaps a more detailed error message to explain this better to the user? Or, perhaps this case is more predictable than we think and we just need to understand OTP better.

> With that being said, I think you're proposing that we just check to make sure that the trip plan that was originally planned is still valid - in other words, you could still follow the original directions and still get to your destination?

I didn't propose this, but it's an interesting idea. How would you envision it working? I just proposed that for the requerying, we increase the numItineraries parameter (number of itineraries that OTP returns), which defaults to 3 - in the hopes that this will increase the chances it will return the selected itinerary.

**Comment by barbeau** [comment]
>Or, perhaps this case is more predictable than we think and we just need to understand OTP better.

I'm hoping that this is the case.  Maybe we could be more intelligent in terms of how we analyze the itineraries?  For example, I think one key worry is that a rider would miss a connection due to delays.  Maybe we specifically look at the trips and their connections - for example, if the same trip_id is used as the first leg, but the 2nd leg changes, we should notify the user they may miss their 2nd leg.  Or something...

But yes, at a minimum I think we need to be clearer in the message to the user.  Maybe the first time the user taps on the notification we go to the trip planning activity and trigger one of the tutorial screens to explain why a trip *could* no longer be recommended.  At least this would give users something to look for in the before/after.

>I didn't propose this, but it's an interesting idea. How would you envision it working? I just proposed that for the requerying, we increase the numItineraries parameter (number of itineraries that OTP returns), which defaults to 3 - in the hopes that this will increase the chances it will return the selected itinerary.

Ah, gotcha.  Sorry, I misread your response.  So yes, I think increase the `numItineraries` would potentially help avoid pushing the original trip option off the list.

Not sure how exactly we could verify that a single trip is still valid, other than what we're currently doing with the `plan` endpoing, and increasing the `numItineraries`.  You're verifying that an itinerary doesn't appear in the list by looking at the tripIds of the legs of the trip, and confirming that they are different?

**Comment by sdjacobs** [comment]
> You're verifying that an itinerary doesn't appear in the list by looking at the tripIds of the legs of the trip, and confirming that they are different?

Yep. This is also essentially how OTP decides whether itineraries are different ([here](https://github.com/opentripplanner/OpenTripPlanner/blob/257ac13150b40942fdae4812007545a66546d7da/src/main/java/org/opentripplanner/routing/spt/GraphPath.java#L168)).

**Comment by barbeau** [comment]
Cool - so what value of `numItineraries` do you think we should use?  And do you have any idea if there is a significant performance hit for the server as we increase?  Although, thinking more, server-side performance hits shouldn't impact the UX, as all these queries are in the background on a Service.

**Comment by barbeau** [comment]
I believe the original issue in this thread is resolved, so I'm going to close this.  I've moved some of the discussion of improving the trip plan notificatoin text to https://github.com/OneBusAway/onebusaway-android/issues/758 (and I made some simple improvements in https://github.com/OneBusAway/onebusaway-android/commit/fe277b3be0d68e826a3a4e369583fdd1aaef8462).
