### ISSUE TITLE
Add a custom trip planning API URL setting

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#622]
**Summary:** 

For other regions that have OneBusAway deployed, it would be nice if there was a way they could test an OTP server with their region, without us updating the Regions API in production.  For example, Puget Sound has an OTP server, but currently there isn't a good way of anyone in Puget Sound testing the system without going straight to their OTP URL in production or forking the app.  This would also allow regions to test new OTP server configurations (e.g., addition of real-time data or upgrades) before going to production.  

This setting is similar to the current "Custom OBA Server API" setting that we have, but for OTP.  I imagine this would also go under the "Advanced" preference category.

**Comment by sdjacobs** [comment]
One thing to be aware of here. Currently, the OTP url is decomposed into parts. By that I mean otpBaseUrl is something like "http://otp-fl.camsys-apps.com:8080/otp" and then TripRequest adds "/routers/default/plan" to get the plan endpoint. /routers/default/plan is the correct path for all versions of OTP I've seen; however, it's possible that a request could be forwarded from somewhere else, ie an agency could expose http://www.myagency.com/tripplanner/plan and internally proxy to an OTP server.

**Comment by barbeau** [comment]
@sdjacobs Good point - TriMet is actually one of these.  They changed their base URL after OTP Android was already built, and their current format broke OTP Android support there:

http://rtp.trimet.org/prod?maxTransfers=3&_dc=1469475638406&from=&to=&arriveBy=false&time=3%3A40%20pm&ui_date=7%2F25%2F2016&mode=TRANSIT%2CWALK&optimize=QUICK&maxWalkDistance=840&date=2016-07-25&toPlace=45.512534%2C-122.672662&fromPlace=45.536347%2C-122.693262

We'll need to strike a balance between supporting multiple API endpoints in OTP (including bikeshare, which we also want to support), and providing flexibility for all the various URL configurations that could take place.  I'd vote for a simple implementation at first assuming that we can append `/routers/default/plan` to all base URLs, and we can tackle more advanced configurations later.

**Comment by barbeau** [comment]
Something else to consider is the possibility of requiring an API key.  Stock OTP instances don't require API keys, but TriMet does - http://developer.trimet.org/why_an_appid.shtml.

**Comment by barbeau** [comment]
Just talked to TriMet - different URL format is artifact of old OTP version, so they plan to move to the more standard "/routers/default/plan" format as they update to new OTP versoin.

It does sound like we would need to include another field in the Regions API for an OTP API key for them, as they need to generate key internally (they can't accept a previously generated key from somewhere else, similar to what we do for multi-region API keys with OBA).  There is also the question of what the API key parameter is called - for TriMet, it's currently `appid`, although I've asked if they would consider accepting `key` as well.  Will update when I hear back.

**Comment by barbeau** [comment]
Documentation on custom server APIs is now added via https://github.com/OneBusAway/onebusaway-android/issues/676, at https://github.com/OneBusAway/onebusaway-android/blob/master/CUSTOM_SERVERS.md.
