### ISSUE TITLE
Failing trip plans

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#646]
**Summary:** 

I'm going to start collecting failing trip plan URLs here that I encounter during testing, so they can be examined server-side to see if there is anything we can do to make them work.

cc @sdjacobs 

* http://otp-fl.camsys-apps.com:8080/otp/routers/default/plan?wheelchair=false&showIntermediateStops=true&toPlace=27.9835,-82.5371&time=12:28PM&fromPlace=28.0587,-82.4165&date=06-24-2016&optimize=QUICK&arriveBy=false
* http://otp-fl.camsys-apps.com:8080/otp/routers/default/plan?wheelchair=false&showIntermediateStops=true&toPlace=28.0286,-82.3930&time=03:02PM&fromPlace=28.0788,-82.4106&date=07-18-2016&optimize=QUICK&arriveBy=false

**Comment by sdjacobs** [comment]
Two related posts on OTP-dev:

https://groups.google.com/forum/#!searchin/opentripplanner-dev/osm$20closest$20point|sort:relevance/opentripplanner-dev/ptdGhGHdOUc/Y9gGuT6PT3IJ
https://groups.google.com/forum/#!searchin/opentripplanner-dev/osm$20closest$20point|sort:relevance/opentripplanner-dev/Ke9_pfP9FIs/JcAXTku4pBoJ

Describes a situation where the closest walkable OSM segment is not connected to the rest of the road network, which results in a "trip not possible" error.

**Comment by barbeau** [comment]
Reported by user:
* http://otp-hart.camsys-apps.com:8080/otp/routers/default/plan?wheelchair=false&showIntermediateStops=true&toPlace=28.0565,-82.5287&time=03:00PM&fromPlace=27.7198,-97.3703&date=08-12-2016&optimize=QUICK&arriveBy=false

**Comment by sdjacobs** [comment]
The origin 27.7198,-97.3703 is in Corpus Christi, Texas. I think the error reported by the app is correct in this case.

**Comment by barbeau** [comment]
Reported by user:

*http://otp-hart.camsys-apps.com:8080/otp/routers/default/plan?optimize=QUICK&showIntermediateStops=true&time=09:00AM&arriveBy=false&wheelchair=false&fromPlace=38.0000,-117.000&toPlace=38.0000,-117.000&date=08-24-2016

Origin/destination are in Nevada, so seems something went wrong in the geocoding, either user error or Google Places widget problem.

**Comment by barbeau** [comment]
To clean up our issue tracker I'm going to close this as "Won't fix", as I don't think there is anything we should be doing client-side for this.  But, I'll continue to log failling trip plans here so someone can investigate server-side.

@sdjacobs Please let me know if there is a better place to document these.
