### ISSUE TITLE
Trip plan activity is potentially referenced outside its lifecycle

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#653]
**Summary:** 

I found this when fixing https://github.com/OneBusAway/onebusaway-android/issues/652.

When a user plans a trip, we poll the server for a period to check if there are any real-time changes that might impact the trip (see https://github.com/OneBusAway/onebusaway-android/issues/617#issuecomment-234952817 for details).  If there are changes, we notify the user.

In `RealtimeServiceImpl.showNotification()`, `mActivity` is referenced to get the Class to register with the notification, so when the user taps on the notification they are brought to the trip planning activity.

The issue here is that `showNotification()` is called from the `BroadcastReceiver.onReceive()` within `RealtimeServiceImpl`, which continues to poll the server after a trip is planned.  So, the activity may have been killed by the time the `BroadcastReceiver` attempts to notify the user.  This would then result in an NPE when trying to access `mActivity`.

There is no other use of `mActivity` in `RealtimeServiceImpl`, so I believe an easy fix for this is to pass in the `Class` instead of the `Activity` in the `RealtimeServiceImpl` constructor.  I'll put together a PR for this.

cc @sdjacobs 

**Steps to reproduce:** 

I haven't actually produced an NPE, but looking at the code this should do it:

1.  Plan a trip
1.  Kill the TripPlanActivity
1.  Have the BroadcastReceiver generate a notification for a trip that's no longer recommended

**Expected behavior:** 

Not crash

**Observed behavior:** 

It would crash.

**Device and Android version:** 

N/A.

**Comment by sdjacobs** [comment]
I also couldn't produce the NPE you mention. In fact, notifications don't seem to happen if you kill the activity. I tested by:

1) Changing the code so that a notification is produced every time OTP is requeried
2) Planning a trip
3) Kill TripPlanActivity by pressing back
No notification is produced.

I think this is because the RealtimeServiceImpl object is instantiated inside TripResultsFragment, so when the system kills the fragment object it also destroys the RealtimeServiceImpl object.

I still think this is a good commit because the code could (maybe should?) be refactored later in such a way that the notifications aren't tied to the activity lifecycle. One possibility is a [service](https://developer.android.com/guide/components/services.html). Also worth considering - if a user presses back whether they would expect to get notifications.

**Comment by barbeau** [comment]
It looks like all background updates are currently killed when the user leaves the `TripResultsFragment`, in `TripResultsFragment.onDestroy()` via `mRealtimeService.disableListenForTripUpdates();`.  So this would explain why an NPE doesn't currently happen, as the alarm manager and broadcast receiver are torn down before the Fragments/Activity are.

After more debugging using code prior to https://github.com/OneBusAway/onebusaway-android/pull/654, when commenting out `mRealtimeService.disableListenForTripUpdates();` in `TripResultsFragment.onDestroy()`, it looks like the NPE still doesn't happen, but it's because Android is still hanging onto a reference to the Activity after the Activity lifecyles ends.  So it looks like we're unnecessarily leaking an Activity for the duration that the BroadcastReceiver is alive.  Android should be able to garbage collect that Activity object after `onDestroy()`, but it can't because we're still holding a reference to it.  If at some point Android decided to force garbage collection to reclaim this memory, then the NPE would occur.

You can see this with the following steps:

1. Changing the code so that a notification is produced every time OTP is requeried
1. Putting breakpoints in `TripResultsFragment.onDestroy()` and `TripPlanActivity.onDestroy()`, and `RealtimeServiceImpl.mBroadcastReceiver.onReceive()`.
1. Planning a trip 
1. Kill TripPlanActivity by pressing back

(I also had the system Developer Option "Don't keep activities" checked, although I'm not sure that is necessary).

You can see that `onDestroy()` is executed for the fragment and activity, but the `BroadcastReceiver.onReceive()` still executes after this, and when it does, it still contains a live reference to `TripPlanActivity` via `mActivity`:

![image](https://cloud.githubusercontent.com/assets/928045/17523869/25c03858-5e2a-11e6-91ca-ebafe2ef5dd7.png)

https://github.com/OneBusAway/onebusaway-android/pull/654 should allow Android to garbage collect that Activity after `onDestroy()`.

This brings up the larger issue, though, that the notifications *should* still be happening after the fragment and activity are destroyed - that's the behavior that HART wanted.  I'll open a separate issue for this.
