### ISSUE TITLE
User isn't notified of trip plan changes when app is backgrounded

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#655]
**Summary:** 

Originally discussed in https://github.com/OneBusAway/onebusaway-android/issues/653#issuecomment-238552482.

When a user plans a trip, we poll the server for a period to check if there are any real-time changes that might impact the trip (see https://github.com/OneBusAway/onebusaway-android/issues/617#issuecomment-234952817 for details).  If there are changes, we notify the user.

However, currently these notifications only occur if `TripResultsFragment` is in the foreground.  From https://github.com/OneBusAway/onebusaway-android/issues/653#issuecomment-238606127:

> It looks like all background updates are currently killed when the user leaves the `TripResultsFragment`, in `TripResultsFragment.onDestroy()` via `mRealtimeService.disableListenForTripUpdates();`.

HART wanted this reminder to be available after the user planned the trip and changed to a different screen, so they could be notified if a delay or other issue caused problems at any point after planning a trip (e.g., en-route).

We will need to be sure that the new implementation properly stops notifications to the user after a certain threshold of time or when the user dismisses the notification.

@sdjacobs Could you please take a look at this?  

Most of this code may already be in place - I haven't looked closely.  The currently implementation may work but leak the `TripResultsFragment` after its lifecycle ends, similar to the issue I discussed with `TripPlanActivity` in https://github.com/OneBusAway/onebusaway-android/issues/653#issuecomment-238606127.  I think a good approach that probably wouldn't require much modification is to register an `IntentService` to receive the alarm from the AlarmManager, instead of using the locally declared BroadcastReceiver.  This would allow the code that executes the request to the OTP server and creates the notification to run in it's own service just for the duration that's required, and then it shuts down.  Here's an example of registering an `IntentService` with the `AlarmManager`:
http://stackoverflow.com/questions/22394615/intentservice-wont-start-using-alarmmanager

**Steps to reproduce:** 
1. Change the code so that a notification is produced every time OTP is requeried
2. Put debugging breakpoints in `TripResultsFragment.onDestroy()` and `TripPlanActivity.onDestroy()`, and `RealtimeServiceImpl.mBroadcastReceiver.onReceive()`.
3. Planning a trip 
4. Kill TripPlanActivity by pressing back

**Expected behavior:** 

Notifications should continue to occur (e.g., `RealtimeServiceImpl.mBroadcastReceiver.onReceive()` should still be called) following `TripResultsFragment.onDestroy()` and `TripPlanActivity.onDestroy()`.

**Observed behavior:** 

No notifications occur after `TripResultsFragment.onDestroy()` and `TripPlanActivity.onDestroy()` (e.g., `RealtimeServiceImpl.mBroadcastReceiver.onReceive()` is never called).  This is because all background updates are currently killed when the user leaves the `TripResultsFragment`, in `TripResultsFragment.onDestroy()` via `mRealtimeService.disableListenForTripUpdates();`

**Device and Android version:** 

Stock LG G4 w/ Android 6.0

**Comment by barbeau** [comment]
Actually, because the background execution involves a call to a server that could take a while to finish, especially on slower wireless connections, we should use the support library version of `WakefulBroadcastReceiver` and start the `IntentService` using `startWakefulService()`, instead of a normal `BroadcastReceiver`.  See https://developer.android.com/training/scheduling/wakelock.html under *Using WakefulBroadcastReceiver* for details - it says:

>A WakefulBroadcastReceiver is a special type of broadcast receiver that takes care of creating and managing a PARTIAL_WAKE_LOCK for your app. A WakefulBroadcastReceiver passes off the work to a Service (typically an IntentService), while ensuring that the device does not go back to sleep in the transition. If you don't hold a wake lock while transitioning the work to a service, you are effectively allowing the device to go back to sleep before the work completes. The net result is that the app might not finish doing the work until some arbitrary point in the future, which is not what you want.

The `WakefulBroadcastReceiver` should be moved outside of `RealtimeServiceImpl` and declared in the manifest.  This guarantees that the platform won't go to sleep and kill the service in the middle of trying to fetch OTP responses.

**Comment by barbeau** [comment]
@sdjacobs Would you be able to work on this?  I know this was a feature that the HART CEO wanted, and I'd like to head off this bug before it surfaces via a user report.

**Comment by sdjacobs** [comment]
I can take a look at this.

I'm a bit worried about the UX implications of keeping the re-query service running after a user presses 'back' to kill TripPlanActivity. If a user plans a trip for far in the future and it happens to have realtime information, the trip will be continually replanned for a long time, without any mechanism for viewing the results of the queries or for stopping the queries (unless the results change). Is this behavior OK? I was thinking that a user presses 'back' because they're no longer interested in this itinerary.

**Comment by barbeau** [comment]
Ok, great!  The primary use case for this feature is for a user to plan a trip, start going about their business, and then be alerted if something changes that would affect their travel.  So there is an expectation that we will be looking into the future and querying in the background, and I think killing these updates when the user presses back prevents the feature from meeting the primary use case.  

I would expect that if the user unchecks the notification option in setting, then all pending notifications are canceled, and none are set for future plans.  So, the question is what paramaters we need to put to avoid cases like the user planning a trip a month in advanced, and the app querying in the background every minute for one month (which we obviously won't want).

For reference, here's a lot of similar discussion in OTP Android for this feature (up and down this thread, although I believe most of the real-time notification discussion starts at this comment):
https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/issues/21#issuecomment-50652181

Re-reading that thread, the final determination was to always schedule the updates to start one hour prior to the trip time, and stop them at the trip departure time.  So if it's Sept 1st and the user plans a trip to start Oct 1st at 10am, the first update to query the server would be scheduled at Oct 1st at 9am, and would stop at 10am.  I believe HART wanted the rider to be notified even during their trip, so maybe for OBA Android we change the stop time to when the trip is supposed to end.

If these server checks are scheduled with a stand-alone WakefulBroadcastReceiver (i,.e., registered in the manifest and in it's own class file), then nothing is actually running in the background until the first time at which the AlarmManager is scheduled to do something.  So in the above example, the application isn't actually running in the background between Sept 1st and Oct 1st at 9am.  The Android platform has the information needed to wake the application up via an Intent on Oct 1st at 9am and start querying the server then.

**Comment by barbeau** [comment]
Also, see above comment for details on implementation of WakefulBroadcastReceiver and IntentService.
