### ISSUE TITLE
Add GA event for trip plan requests sent to a server

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#656]
**Summary:** 

We should add a Google Analytics event that fires when a trip plan request is sent to an OTP server.  The "Clicked Trip Plan link" event currently fires when a user taps on the "Plan a trip" icon in the main navigation drawer, but we'd also like to capture how many times a trip is planned once they are looking at the `TripPlanActivity`.

**Steps to reproduce:** 

1. Plan a trip

**Expected behavior:** 

For each trip request sent to the server, a GA event should be recorded

**Observed behavior:** 

No GA event is recorded for trip requests sent to the server.

**Device and Android version:** 

N/A

**Comment by barbeau** [comment]
cc @sdjacobs

**Comment by cagryInside** [comment]
I am tackling with this.
