### ISSUE TITLE
GPX files won't load in emulator

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#659]
**Summary:** 

I added GPX files to the project in `/gpx_files` (via https://github.com/OneBusAway/onebusaway-android/commit/8188ef7aca5f3291d7e62bb43b6f15979422c0d7) so we can load them into the emulator.  However, when trying to load them into the emulator, I get the error message "The table contains errors.  No locations were sent".

**Steps to reproduce:** 

1. Open emulator
1. Tap on three dots in right vertical strip
1. In "Extended controls" popup under the "Location" tab, click "LOAD GPX/KML" and select a GPX file
1. Click "Play" button

**Expected behavior:** 

Location should be sent to the emulator

**Observed behavior:** 

Error message "The table contains errors.  No locations were sent":

![image](https://cloud.githubusercontent.com/assets/928045/17559171/28619590-5eeb-11e6-8594-e29cb0991489.png)

**Device and Android version:** 

Nexus 5X API Level 23 (Google APIs), 1080 x 1920; 420 dpi, Android 6.0 (Google APIs), x86, 1GB

**Screenshots:** 

See above

**Comment by barbeau** [comment]
It looks like the emulator does not support the GPX waypoint format:

~~~
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gpx
xmlns="http://www.topografix.com/GPX/1/1"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd"
version="1.1"
creator="gpx-poi.com">
   <wpt lat="28.0587" lon="-82.4139">
      <time>2015-12-01T03:01:44Z</time>
   </wpt>
</gpx>
~~~

However, it does support the GPX track format:

~~~
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gpx
xmlns="http://www.topografix.com/GPX/1/1"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd"
version="1.1"
creator="gpx-poi.com">
   <trk>
      <name />
      <cmt />
      <trkseg>
        <trkpt lat="28.0587" lon="-82.4139">
          <ele>0</ele>
          <time>2015-12-01T03:01:44Z</time>
        </trkpt>
      </trkseg>
   </trk>
</gpx>
~~~

I'll push a fix for this shortly, which changes the GPX files from the waypoint format to the track format.

**Comment by cagryInside** [comment]
@barbeau I tried with the same emulator in Mac OS X and have the same error.

**Comment by barbeau** [comment]
@cagryInside Thanks good to know.

**Comment by cagryInside** [comment]
> @cagryInside Just pushed newly formatted GPX files that work on Windows emulator to the master branch via 0ea0846 - could you try these on Mac OS X and see if they work?

@barbeau now it works!

**Comment by barbeau** [comment]
Great, thanks!  I posted a Q&A StackOverflow post (answered my own question) about this as well, as surprisingly it doesn't seem to be documented anywhere I could find:
http://stackoverflow.com/questions/38877870/gpx-files-wont-load-in-android-emulator

**Comment by barbeau** [comment]
I also opened an AOSP feature request for supporting GPX waypoint format, or at least giving a better error message, here:
https://code.google.com/p/android/issues/detail?id=219730
