### ISSUE TITLE
Bus departing ~1,440 minutes early

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#681]
**Summary:** 

Users have occasionally reported that they see a bus running 1,440 minutes early or late, which happens to be roughly the number of minutes in one day (24 * 60).

Same issue on OBA iOS - https://github.com/OneBusAway/onebusaway-iphone/issues/661.

From https://github.com/OneBusAway/onebusaway-iphone/issues/661#issuecomment-242153738:

>Alright, after looking at `1_11190.json` in the zip file that aaronbrethorst attached to this issue in the initial post (captured at `1472055140749` - Wednesday August 24, 2016 09:12:21 am - PDT), it looks like it's a real-time prediction error in Puget Sound...

Just wanted to document this so we have a record in OBA Android as well.

**Steps to reproduce:** 

Unknown (seems to be server-side problem)

**Expected behavior:** 

Show a predicted time today

**Observed behavior:** 

A predicted time for yesterday or tomorrow

**Device and Android version:** 

N/A

**Comment by barbeau** [comment]
This appears to be a server-side issue (see https://github.com/OneBusAway/onebusaway-iphone/issues/661#issuecomment-242159716), so I'm closing as "Won't fix" here.

**Comment by barbeau** [comment]
Reported by another user:

>App Version: 2.1.3
Model: SAMSUNG-SM-G935A
OS Version: 6.0.1 / 23
Google Play Services App: 9.6.80 (440-132579434)
Google Play Services Library: 9452000
Region/API: Puget Sound (selected automatically)
Loc: network 

>Bug report:
The attachment is a screen shot of what I've been seeing the past few mornings. The pic is from about 6 min before the bus actually arrived for its 5:24 am scheduled pickup.
If I look ahead for the stop, like just now, it shows the bus is scheduled to arrive on time tomorrow in 1012 min. However, by tomorrow morning, possibly once the GPS for that run time is actually picked up by OBA, the system gets confused and reports as if it is tracking the previous day's run.

![image](https://cloud.githubusercontent.com/assets/928045/18530702/ce3beb02-7aa0-11e6-96d6-bb4d92d1e4f2.png)

**Comment by sheldonabrown** [comment]
Thanks, we have this fixed, but not deployed yet.

It was a combination of bad timestamps from the data feed and a lazy assumption about service date in GTFSRealtimeSource.  The fix is part of a much larger changeset so it might take a while to deploy.
