### ISSUE TITLE
Allow users to dismiss service alerts

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#713]
**Summary:** 

We're beginning to see regions take more advantage of the ability to distribute service alerts via OneBusAway, which is great.  In the past, alerts were usually temporary/transient events such as a real-time service outage or maintenance alert.  

Now, agencies are starting to publish more long running alerts about stops or routes with detours that are weeks long, or to advertise new services.  When these alerts aren't carefully targeted to specific routes or stops, they can quickly add up and take up a large portion of the screen.

For example, here's what the alerts look like for Tampa for every stop as of today:

![image](https://cloud.githubusercontent.com/assets/928045/19833962/daf3badc-9e22-11e6-9b6b-d90657ac77f4.png)

Users are starting to complain:

> I do not want alerts signified by the yellow triangle with an exclamation mark. These alerts are not pertinent for what I need.

WMATA accidentally published around 6 empty service alerts (no text) last week and I also got several complaints about that.  Same with San Diego, which has 2-3 alerts for a decent number of stops:

![image](https://cloud.githubusercontent.com/assets/928045/19833972/2e0d93aa-9e23-11e6-97ce-27b8dd348102.png)

We need a mechanic that allows users to selectively acknowledge that they've read an alert, and dismiss it so it doesn't appear again.  I think a simple "DISMISS" button in the bottom right would do it, similar to how the calendar app looks:

![image](https://cloud.githubusercontent.com/assets/928045/19833982/91791de2-9e23-11e6-90dd-7546b8398ecf.png)

We should probably add a button somewhere (in Settings?) that would allow a user to restore (i.e., undismiss) all active alerts, so they would appear again.

We already have a service alerts table in the local database, although it appears to currently be unused.  There is a `markAsRead` boolean variable when inserting/updating records, which records the read time (current time) to the database.  We should be able to use this table for this feature.

Related to https://github.com/OneBusAway/onebusaway-android/issues/447, although https://github.com/OneBusAway/onebusaway-android/issues/447 is technically considered a bug in how we display a large number of alerts in that they can starve arrivals for space - this issue is for a new mechanic to allow selectively dismissing alerts so they don't take up space.

**Steps to reproduce:** 
1. Go to Tampa region and tap on stop, and slide up panel, or go to starred stop

**Expected behavior:** 

Allow me to get rid of service alerts blocking my view of arrivals

**Observed behavior:** 

I'm stuck looking at alerts from the agency for however long the agency decides to put them there.

**Device and Android version:** 

N/A

**Comment by barbeau** [comment]
A screenshot from a user reporting the problem in San Diego:

![image](https://cloud.githubusercontent.com/assets/928045/19981865/0bbca48e-a1da-11e6-8f00-ff22c5f0fc47.png)

**Comment by barbeau** [comment]
Looking at this more, I think we need to have a separate `dismissed` field in the database, treated differently than `markAsRead`.

**Comment by barbeau** [comment]
A few UI options for the DISMISS button - any votes?

![image](https://cloud.githubusercontent.com/assets/928045/20079897/eb6073b2-a514-11e6-9465-4b0ffe67447a.png)

**Comment by bbodenmiller** [comment]
Middle one but I don't love any of them and I'm having a hard time coming up with better options. Maybe a raised dismiss button.

Also has anyone been communicating with the agencies about how they shouldn't abuse the alerts? Don't overwhelm the user with unnesserary details.

**Comment by barbeau** [comment]
Yeah, I'm not in love either, although the left is the closest to what I've been able to find for existing examples of as dismiss button in popular Android apps.

I've talked to a few regions about not spamming alerts and they are aware of user complaints, but I want to tread lighting on this, as I've been pushing regions in the past to use service alerts more.  The usability on Android will be significantly improved by being able to dismiss alerts after seeing them once, so I want to see how that pans out before going on a campaign to curb alerts.

**Comment by barbeau** [comment]
I settled on a dialog-based UI to provide better context to hiding alerts (vs. "dismissing" them), support a snackbar to allow an UNDO, and avoid the delay involved with launching a new activity to show the service alert info.  Details in PR at https://github.com/OneBusAway/onebusaway-android/pull/716, and final screenshots are also below:

![image](https://cloud.githubusercontent.com/assets/928045/20566691/fa7a7eaa-b163-11e6-8310-8ba2590df5eb.png)
