### ISSUE TITLE
Search cursor is difficult to see

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#718]
**Summary:** 

A user reported that search wasn't working, and said they didn't see anywhere to type the search term.  

The typing cursor is hard to see currently - I recall doing some custom styling to get this to be whiter in initial v2 release of the app, but it appears that something may have broken and the cursor reverted back to a light green that blends in with the action bar.

In the below screenshot, the cursor is just to the left of the "S" in "Search stop..." (circled in red) and it's hard to see:

![image](https://cloud.githubusercontent.com/assets/928045/20441842/2b518088-ad94-11e6-80e4-cb9086020f53.png)

**Steps to reproduce:** 

1. Tap on the magnifying glass in the action bar to open search option in action bar

**Expected behavior:** 

Make the typing cursor clearly visible - more white.

**Observed behavior:** 

Typing cursor is light green and hard to see against green action bar.

**Device and Android version:** 

LG G5 w/ Android 6.0.1, running master branch as of https://github.com/OneBusAway/onebusaway-android/commit/5044958b03e07d90f98e713687a6097668d86c6d.

**Screenshots:** 

See above

**Comment by barbeau** [comment]
Here's the commit where I previously changed the SearchView cursor color to be white:
https://github.com/OneBusAway/onebusaway-android/commit/b937b043dda6904b74a2963399ac271e232a8003

...so, this is definitely a regression.

**Comment by barbeau** [comment]
Here's the StackOverflow post I originally used to fix the issue:
http://stackoverflow.com/questions/27730253/how-to-style-the-cursor-color-of-searchview-under-appcompat

**Comment by Plinzen** [comment]
Hi, 
I saw your comment on SO. I solved the issue by removing the `android` prefix:

```
<item name="autoCompleteTextViewStyle">@style/cursorColor</item>
```

**Comment by barbeau** [comment]
@Plinzen Awesome, thanks for sharing!  That definitely fixes it!

![image](https://user-images.githubusercontent.com/928045/38880688-555d2a4a-4234-11e8-97fe-60a0e54fc271.png)
