### ISSUE TITLE
Travis builds are failing again

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#720]
**Summary:** 

Seems like we should have a perpetual issue for this - example of failed build:
https://travis-ci.org/OneBusAway/onebusaway-android/builds/178311476

This is related to Google renaming the ABIs again - see my past SO post:
http://stackoverflow.com/questions/28751111/invalid-abi-armeabi-v7a-for-the-selected-target-with-google-apis-21

I believe based on my answer http://stackoverflow.com/a/28751112/937715, we need to update things as specified in the **"EDIT Sept 12th, 2016"** section.  This has worked for these two projects:
* https://github.com/barbeau/gpstest
* https://github.com/googlemaps/android-maps-utils

**Comment by barbeau** [comment]
Looks like there isn't an ARM ABI for API 25 (Android 7.1.1) yet:

![image](https://cloud.githubusercontent.com/assets/928045/20687155/55a16842-b589-11e6-8b16-22c9f6282dbd.png)

**Comment by barbeau** [comment]
Looks like ABIs for API Level 24 Google APIs are also missing - output of `android list target`:

~~~
----------
id: 26 or "Google Inc.:Google APIs:24"
     Name: Google APIs
     Type: Add-On
     Vendor: Google Inc.
     Revision: 1
     Description: Android + Google APIs
     Based on Android 7.0 (API level 24)
     Libraries:
      * com.android.future.usb.accessory (usb.jar)
          API for USB Accessories
      * com.google.android.media.effects (effects.jar)
          Collection of video effects
      * com.google.android.maps (maps.jar)
          API for Google Maps
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, W
XGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.  // <-- This should include the ABIs such as `google_apis/armeabi-v7a`, etc.
~~~

**Comment by barbeau** [comment]
So the API Level 22 emulator should work because the ABIs exist, especially when using the `travis_wait` command:
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

However, with this build:
https://travis-ci.org/OneBusAway/onebusaway-android/builds/183263286

...I'm now seeing this error:

~~~
02:55:13 E/SplitApkInstaller: Failed to finalize session : INSTALL_FAILED_DEXOPT: Package couldn't be installed in /data/app/com.joulespersecond.seattlebusbot-1: scanPackageLI
Unable to install /home/travis/build/OneBusAway/onebusaway-android/onebusaway-android/build/outputs/apk/onebusaway-android-oba-google-debug-v2.1.5.apk
com.android.ddmlib.InstallException: Failed to finalize session : INSTALL_FAILED_DEXOPT: Package couldn't be installed in /data/app/com.joulespersecond.seattlebusbot-1: scanPackageLI
	at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:85)
	at com.android.ddmlib.Device.installPackages(Device.java:904)
	at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:137)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:126)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
com.android.builder.testing.ConnectedDevice > runTests[test(AVD) - 5.1.1] FAILED 
	com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to finalize session : INSTALL_FAILED_DEXOPT: Package couldn't be installed in /data/app/com.joulespersecond.seattlebusbot-1: scanPackageLI
		at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:147)
null
com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to finalize session : INSTALL_FAILED_DEXOPT: Package couldn't be installed in /data/app/com.joulespersecond.seattlebusbot-1: scanPackageLI
	at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:147)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:126)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.ddmlib.InstallException: Failed to finalize session : INSTALL_FAILED_DEXOPT: Package couldn't be installed in /data/app/com.joulespersecond.seattlebusbot-1: scanPackageLI
	at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:85)
	at com.android.ddmlib.Device.installPackages(Device.java:904)
	at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:137)
	... 8 more
:onebusaway-android:connectedObaGoogleDebugAndroidTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':onebusaway-android:connectedObaGoogleDebugAndroidTest'.
~~~

**Comment by barbeau** [comment]
Given that Google still doesn't seem to have resolved the issues with API level 23-25 emulators that prevent them from running on Travis, I'm pushing a temporary workaround to the master branch in https://github.com/OneBusAway/onebusaway-android/commit/03e262d2ca17e2b4ea654640b38d9719bb8e9a3d that builds the projects on Travis, but does not run the unit tests.  Builds don't require the emulator, only the unit tests, so this at least gives us the ability to see if builds themselves succeed.

**Comment by barbeau** [comment]
I opened this issue for failing emulator builds on android-map-utils, and I believe it's the best summary of the current problem with the emulators/SDK:
https://github.com/googlemaps/android-maps-utils/issues/371

**Comment by albodelu** [comment]
Hello @barbeau, i'm @ardock, I answered you [here](https://github.com/travis-ci/travis-ci/issues/6122), I would like to know your opinion, I still need to improve it but seems Google fixed it.

The relevant part is to use `-engine classic` (QEMU-1), I'll investigate QEMU-2 issue another day.

**Comment by barbeau** [comment]
@albodelu Thanks for the info!  I'll see if I can test this on my projects soon...

**Comment by barbeau** [comment]
From https://github.com/travis-ci/travis-ci/issues/6122#issuecomment-293202184:

>I posted a related sample in [stackoverflow](https://stackoverflow.com/questions/42731625/travis-ci-failed-because-cannot-accept-license-constrain-layout/42736695#42736695) and tested it in three projects.
>
>The first sample, especially for your Onebusaway :
>* https://travis-ci.org/albodelu/android-maps-utils/builds/220859379
>* https://travis-ci.org/albodelu/Dexter/builds/220847349
>* https://travis-ci.org/albodelu/constraint-layout/builds/220841505
>
>Updated SO answer:
https://stackoverflow.com/questions/45100298/how-to-setup-an-emulator-running-api-25-using-a-build-matrix-on-travis-ci/45177269#45177269

**Comment by barbeau** [comment]
@albodelu I'm just now coming back to setting up Android unit tests on Travis again - is the info in the above links still the most recent configuration you're aware of, or do you have a more recent version that still works as of today?

**Comment by barbeau** [comment]
@albodelu @ardock Friendly ping on this - have you been able to get the emulator running on Travis recently for unit tests?  I'm stumped...

**Comment by barbeau** [comment]
Possible progress reported here on getting emulator tests running:
https://github.com/googlemaps/android-maps-utils/issues/371#issuecomment-429197624

**Comment by barbeau** [comment]
It looks like Butterknife now runs emulator-based tests on Travis:
https://travis-ci.org/JakeWharton/butterknife

Here's the Travis config - maybe this will work for us:
https://github.com/JakeWharton/butterknife/blob/master/.travis.yml

**Comment by barbeau** [comment]
This is working on GPSTest:
https://github.com/barbeau/gpstest/pull/278

**Comment by barbeau** [comment]
A good analysis of speeding up emulator-based Travis builds:
https://medium.com/zendesk-engineering/speeding-up-android-builds-on-travis-ci-1bb4cdbd9c62

**Comment by barbeau** [comment]
Now all builds (even not emulator based) are failing due to a license issue - from https://travis-ci.org/OneBusAway/onebusaway-android/builds/557364172:

~~~
> Configure project :onebusaway-android
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
File /home/travis/.android/repositories.cfg could not be loaded.
Checking the license for package Android SDK Platform 29 in /usr/local/android-sdk/licenses
Warning: License for package Android SDK Platform 29 not accepted.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':onebusaway-android'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-29 Android SDK Platform 29
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 52s
The command "./gradlew assembleObaGoogleDebug assembleObaAmazonDebug assembleYrtGoogleDebug -PdisablePreDex" exited with 1.
~~~

**Comment by barbeau** [comment]
Based on this Travis build comment, it looks like newer build tools broke Travis:
https://travis-ci.org/ankidroid/Anki-Android/builds/516486599

Here's the Travis config that apparently now works:
https://github.com/ankidroid/Anki-Android/blob/master/.travis.yml

**Comment by barbeau** [comment]
With the latest changes based on the above config the emulator does start now and tests run :tada:!

However, the navigation tests are taking too long and the builds time out at 50 minutes.  I'm going to set up just compiling the project in https://github.com/OneBusAway/onebusaway-android/pull/997, and then work on adding the emulator-based testing again.

Here's the statement to run the integration tests on the emulator:

` - ./gradlew test check connectedObaGoogleDebugAndroidTest -x lint --stacktrace`

Hopefully we can just disable the NavigationTest tests on CI and have the rest of the tests run.
