### ISSUE TITLE
Improve lefty experience

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#738]
**Summary:** 

From a user:

>Hi, love your app, but there's just one simple ux/ui design that is really becoming difficult to use  and that is the little button that centers the app to your location is very right handed user centric. The button is very difficult for left handed use.  Could you provide alternate button location use, either In the center bottom of the screen for ambidextrous use. Or provide the option to have the button on the left side. Thanks so much! You'll help prevent Hand cramps, and improve the ux for your left handed clients!

It shouldn't be that hard to include an option to flip the "My location" FAB to the left side.

**Steps to reproduce:** 

Open app in "Nearby" mode

**Expected behavior:** 

Give me an option to make the "My location" FAB "lefty-friendly".

**Observed behavior:** 

"My location" button is locked to right side of screen.

**Device and Android version:** 

N/A

**Comment by bbodenmiller** [comment]
Interesting idea. How does Google Maps handle the issue?

**Comment by barbeau** [comment]
To my knowledge, it doesn't.  I don't recall seeing a left-handed display
option in an other app.  Some devices have a "one-handed operation" mode,
particularly for large screens where it's tough to reach the top or far
side of screen with your thumb, but I don't recall seeing an option to flip
the layout.  I think this would also be generally useful beyond just those
with a dominant left hand.  I carry my phone in my left front pocket, so I
end up using my left hand when I'm carrying something in my right (e.g.,
dragging luggage).

Sean J. Barbeau, Ph.D.
sjbarbeau@gmail.com
http://www.linkedin.com/in/seanbarbeau
