### ISSUE TITLE
Capitalization of Stop Names and Some Headsigns is Incorrect

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-android#742]
Based on San Diego data.

The following single-word headsign is incorrectly turned into title case:
SDSU (no screenshot) to "Sdsu"

In addition stop names are not correctly capitalized.  For example, "SDSU Transit Center" is recapitalized to "Sdsu Transit Center".

Also, in the search results for a route, the route name is incorrectly capitalized:
"Downtown San Diego - UTC via Old Town" turns into "Downtown San Diego - Utc via Old Town"

See annotated screenshots for more information.

![screenshot_20170112-175324](https://cloud.githubusercontent.com/assets/5028299/21920086/c9fbea8e-d913-11e6-9186-fa1d308d07dd.png)
![screenshot_20170112-175403](https://cloud.githubusercontent.com/assets/5028299/21920087/c9fe6d5e-d913-11e6-8022-00ddf5849879.png)
![screenshot_20170112-215931](https://cloud.githubusercontent.com/assets/5028299/21920088/c9ff4cd8-d913-11e6-8db4-3c3b02f4ae2c.png)
![screenshot_20170112-220055](https://cloud.githubusercontent.com/assets/5028299/21920089/ca008bde-d913-11e6-9614-226e01e59faa.png)
![screenshot_20170112-220114](https://cloud.githubusercontent.com/assets/5028299/21920090/ca025f72-d913-11e6-8a1e-fc43b94b2e66.png)

**Comment by bbodenmiller** [comment]
Related to https://github.com/OneBusAway/onebusaway-iphone/issues/934.

**Comment by barbeau** [comment]
Thanks @devinbraun!  I'll get this fixed in the next release.  I'm still normalizing some of the string manipulation functions across the app and obviously a few cases still haven't been resolved.

**Comment by barbeau** [comment]
@devinbraun Ok, I believe this should be fixed in the current master branch now.  I'll see if I can get a new beta out early next week that includes these changes.

**Comment by barbeau** [comment]
@devinbraun I just pushed v2.1.6 to beta (which includes this fix), so it should be available within the next hour or so.  Please give it a look when you have a chance to see if I missed anything.

**Comment by devinbraun** [comment]
@barbeau I can't find any issues with capitalization in the beta version of the app.  I checked all of the typical problem children and they were all perfect.

**Comment by barbeau** [comment]
Awesome, thanks @devinbraun!
