### ISSUE TITLE
NPE when trying to get updated trip plan in the background

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#749]
**Summary:** 

For current `master` branch and v2.1.6 (73) - crash after planning a trip, when the app attempts to check for changes in the itinerary:

~~~
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
	at org.onebusaway.android.directions.realtime.RealtimeService.getItinerary(RealtimeService.java:276)
	at org.onebusaway.android.directions.realtime.RealtimeService.onHandleIntent(RealtimeService.java:76)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
~~~

Very likely caused by https://github.com/OneBusAway/onebusaway-android/pull/678, which was manually merged due to conflicts in https://github.com/OneBusAway/onebusaway-android/commit/7dc279332e0dfc7638233acb1fc50b6f4f3016f9.

I'm not sure this is consistently reproducible for all trips.  I produced it back to-back on the same trip plan, but later couldn't repro it, although I couldn't find a trip with real-time info.

@sdjacobs Would you be able to take a look at this?  I'm halting the public rollout of v2.1.6 until we can figure this out so everyone doesn't encounter this during trip planning in Tampa.  

**Steps to reproduce:** 

1. Plan a trip with real-time info, and wait for the update on the same screen

**Expected behavior:** 

Not crash

**Observed behavior:** 

NPE and crash

**Device and Android version:** 

LG G5 with Android 7.0

**Comment by sdjacobs** [comment]
The stack trace is pretty informative and I'm pretty confident I could fix the problem just based on that info - but unfortunately, I can't reproduce this, and I'd really like to have a reproducible case. Do you have any more information on the conditions causing this? Were you able to reproduce in the emulator, or just on the device?

**Comment by barbeau** [comment]
I just reprod on emulator.  Plan a trip from University Area Transit Center to Marion Transit Center at 2:00pm, make sure real-time info is shown in the trip times (i.e., some times crossed out), and then hit the home button to background the app and wait around 10-15 seconds.

Key seems to be finding trip with real-time info, then hitting home to background app.

Seems that once you reproduce this once, as well, it keeps crashing - at least that's the behavior on the device I've seen.

**Comment by sdjacobs** [comment]
OK I got a reproducible case! Had to use Android 7.0 and not the earlier version I had.

**Comment by barbeau** [comment]
@sdjacobs Excellent!  Thanks for looking at this.
