### ISSUE TITLE
Add custom reminder name to notification

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#769]
**Summary:** 

Currently, you can set a custom reminder name so it shows up in the reminders list, but that name is not shown in the actual reminder notification - we currently just show "Route 5 is arriving in 7 min!".

It would be helpful to add the reminder name to the notification itself so riders can more easily differentiate them.

The reminder notifications could use a UI update in general, too.

**Steps to reproduce:** 

1. Tap on an arrival time
1. Choose "Set a reminder"
1. Set a reminder (if you want to be immediately notified, set it for more than the current ETA)
1. Look at the reminder notification

**Expected behavior:** 

The notification should include the reminder name

**Observed behavior:** 

The notification does not include the reminder name - it just says "Route 5 is arriving in 7 min!".

**Device and Android version:** 

N/A

**Comment by bridgette** [comment]
Hey 👋  
I want to pick this up as my first PR, but I can't assign the issue to myself (or publish a feature branch to repo). @barbeau do you mind making me a collaborator?
thanks!

**Comment by themonki** [comment]
@bridgette you can. Fork the repo, create a branch and pull request!

 See more here https://github.com/OneBusAway/onebusaway-android/blob/master/.github/CONTRIBUTING.md

**Comment by barbeau** [comment]
@bridgette That's great!  Commenting here is enough to call "dibs" on an issue.  Feel free to fork the repo, create a new branch, and create a pull request!
