### ISSUE TITLE
No background map

### ISSUE THREAD

**Issue by sastimac** [OneBusAway/onebusaway-android#772]
**Summary:** 

When OBA loads it shows my location and local bus stops but does not show the background map. The map area is blank with a "Google" shown in the bottom left where, I believe, it is normally.
NOTE: Using Wifi priority mode. 

**Steps to reproduce:** 
This happens every time a start OBA.
Phone: Samsung S7; T-Mobile
OS: Android, v7, just updated today to todays update, but issue existed in prior version

How can we reproduce the issue?
See above.

**Observed behavior:** 
See above

**Device and Android version:** 
See above.

**Screenshots:** 
Not available because I'm reporting this on my Windows computer. I could not find a way to report the but via the application.

**Comment by sastimac** [comment]
added screen shot
![screenshot_20170522-111055 1](https://cloud.githubusercontent.com/assets/15972016/26322397/c736e826-3edf-11e7-8c73-c48ba1c69585.png)

**Comment by sastimac** [comment]
Explain why closed?

**Comment by barbeau** [comment]
Thanks @sastimac! Can you please report this via the app, by tapping on "Send feedback ->Send app feedback"?  That way I'll be able to see what version of Google Play Services you're running.

I’ve gotten a few other reports from users of the map imagery not showing – based on troubleshooting with those users the problem isn’t related to OneBusAway (users are seeing this with the previous app version v2.1.8 too - sounds like your experience is the same), but seems to be related to Google Play Services.  One user ended up moving from a Galaxy S7 to S8, and she didn't see the issue on the S8 (if only we could all solve our problems like this :)).

Could you also please try restarting your device and see if that helps?

You can also try clearing the “Google Play Services” app cache via your System menu (under “Applications”) – see:
http://stackoverflow.com/a/17622163/937715

Neither of these fixes worked for the other users, but it's worth a shot on your device.

**Comment by barbeau** [comment]
So I'm closing this as "Won't fix" for now as there isn't anything I can do to fix it if the issue is in Google Play Services - if I get any more information that it's something I can address I'll reopen.  Feel free to keep posting more info here on the problem - I'll do the same as I gather more info.

**Comment by sastimac** [comment]
FYI - I'm a retired Hardware Test Engineer and taking classes for web design at the local college. I appreciate the issues you have and inter-relationship with other apps. Thanks for the education on what's happening. 
Results - No change. 
Google play services: 10.2.98 (440-146496160)
Google play services f...:1.9- (release 156360073)
I'll try to report using app directly.

Ciao,
Stephen

**Comment by barbeau** [comment]
@sastimac Thanks!  Got it - here's the info from the feedback email:

~~~
App Version: 2.1.9
Model: SM-G930T
OS Version: 7.0 / 24
Google Play Services App: 10.2.98 (440-146496160)
Google Play Services Library: 9452000
Region/API: Puget Sound (selected automatically)
Loc: fused XXXXXX, 4 second(s) ago
~~~

**Comment by barbeau** [comment]
I'm going to add the device info to this issue as well for other users that have reported this too.

Here's the first:

~~~
App Version: 2.1.9
Model: SAMSUNG-SGH-I337
OS Version: 5.0.1 / 21
Google Play Services App: 10.2.98 (238-146496160)
Google Play Services Library: 9452000
Region/API: Puget Sound (selected automatically)
Loc: gps XXXXXXX, 50 second(s) ago
~~~

**Comment by barbeau** [comment]
Another device:

~~~
App Version: 2.1.9
Model: SM-G920P
OS Version: 7.0 / 24
Google Play Services App: 10.2.98 (440-146496160)
Google Play Services Library: 9452000
Region/API: Puget Sound (selected automatically)
Loc: network XXXXXXX, 1 second(s) ago
~~~

**Comment by barbeau** [comment]
And another:

~~~
App Version: 2.1.8
Model: SM-G930V
OS Version: 7.0 / 24
Google Play Services App: 10.2.98 (440-146496160)
Google Play Services Library: 9452000
Region/API: Puget Sound (selected automatically)
Loc: gps XXXXXXXX, 0 second(s) ago
~~~

**Comment by barbeau** [comment]
And the last:

~~~
App Version: 2.1.8
Model: LG-H918
OS Version: 7.0 / 24
Google Play Services App: 10.2.98 (440-146496160)
Google Play Services Library: 9452000
Region/API: Puget Sound (selected automatically)
Loc: gps XXXXX, 1 second(s) ago
~~~

All but this device are Samsung devices (this is an LG), although IIRC Samsung is also the top OEM for OBA installs.  So, it may not be a Samsung issue.  As previously stated my best guess at this point is a Google Play Services issue.

**Comment by barbeau** [comment]
Another user report:

>App Version: 2.1.9
Model: LG-LS997
OS Version: 7.0 / 24
Google Play Services App: 10.2.98 (440-146496160)
Google Play Services Library: 9452000
Region/API: Puget Sound (selected automatically)
Loc: gps 47.61367466,-122.34460076 47.027, 2 second(s) ago
I've some how lost my map in the program.  I can see the stops and where I am except I'm not on a map to see what street I'm on.  How do I get it back.  I've uninstalled the program and went back to Google play store and reinstalled but the street is still gone.

**Comment by barbeau** [comment]
Reported by another user:

>App Version: 2.1.9
Model: VS810PP
OS Version: 5.1.1 / 22
Google Play Services App: 10.2.98 (234-146496160)
Google Play Services Library: 9452000
Region/API: Tampa Bay (selected automatically)
Loc: gps 27.77543357,-82.66328629 10.0, 1 second(s) ago
> 
>Can you tell me what happened to the streets? I have none.

**Comment by sastimac** [comment]
Magically, yesterday the background map appears and is still working today.

 

Stephen Stimac

 <mailto:sastimac@comcast.net> sastimac@comcast.net

**Comment by barbeau** [comment]
Stephen - that's good! Could you please check you Google Play Services App version, or just send another email via in app "Send feedback - - - Send App feedback"? I'm curious if it changed.

**Comment by sastimac** [comment]
I just sent “Feedback” of the latest info.

 

Ciao,

 

Stephen Stimac

 <mailto:sastimac@comcast.net> sastimac@comcast.net

**Comment by barbeau** [comment]
@sastimac Here it is:

>App Version: 2.1.9
Model: SM-G930T
OS Version: 7.0 / 24
Google Play Services App: 11.0.55 (440-156917137)
Google Play Services Library: 9452000
Region/API: Puget Sound (selected automatically)
Loc: gps xxxxxxx, 1 second(s) ago

Looks like you're now running Google Play Services v11.0.55 instead of the old version v10.2.98.  So it looks like this was a bug in v10.2.98.  Thanks for sharing!
