### ISSUE TITLE
Build fails due to missing artifact org.onebusaway.util:comparators:1.0.0 

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#779]
**Summary:** 

Travis builds have started failing with the following error:

~~~
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':onebusaway-android'.
> Could not resolve all dependencies for configuration ':onebusaway-android:_agencyXAmazonDebugApkCopy'.
   > Could not find org.onebusaway.util:comparators:1.0.0.
     Required by:
         project :onebusaway-android
~~~

Example of failed Travis build:
https://travis-ci.org/OneBusAway/onebusaway-android/builds/245560666

The machine hosting the OBA Maven repo recently moved (https://groups.google.com/forum/#!topic/onebusaway-developers/jYZ1odjulPM), so this is the likely culprit.

**Steps to reproduce:** 

Do a fresh clone on a new machine that hasn't previously downloaded the `org.onebusaway.util:comparators:1.0.0` artifact (or delete it from your machine) and build the project with `gradlew assembleObaGoogleDebug`

**Expected behavior:** 

Successfully build

**Observed behavior:** 

Build fails with:

~~~
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':onebusaway-android'.
> Could not resolve all dependencies for configuration ':onebusaway-android:_agencyXAmazonDebugApkCopy'.
   > Could not find org.onebusaway.util:comparators:1.0.0.
     Required by:
         project :onebusaway-android
~~~

**Comment by barbeau** [comment]
From @sheldonabrown:

>I’m able to download the artifact successfully:
>
>http://nexus.onebusaway.org/service/local/repositories/releases/content/org/onebusaway/util/comparators/1.0.0/comparators-1.0.0.jar
>
>or:
>
>http://nexus.onebusaway.org/content/groups/public/org/onebusaway/util/comparators/1.0.0/
>
>Make sure you are using nexus.onebusaway.org instead of developer.onebusaway.org — I’ve re-inforced some of the virtual hostname config so I can potentially split sites if necessary.

**Comment by sheldonabrown** [comment]
Ok Sean,

move it back to the original URL and try it out for me:

"http://nexus.onebusaway.org/nexus/content/repositories/releases"

**Comment by sheldonabrown** [comment]
Found some rules I missed.  Others have reported this as well, but I think I've got it now.

**Comment by barbeau** [comment]
Thanks @sheldonabrown!  I think this is working again so I'm going to close it out.
