### ISSUE TITLE
Improve UX for starring routes vs. stops

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#782]
**Summary:** 

Some users definitely aren't getting the difference between starring routes and stops.  I get occasional feedback saying "Starred stops is broken - I star a stop and it doesn't appear in the list."  It turns out they are starring routes, instead of stops (see https://github.com/OneBusAway/onebusaway-android/blob/master/FAQ.md#im-tapping-on-the-star-next-to-the-route-but-i-dont-see-anything-in-the-starred-stops-list).

Some ideas for improving the UX surrounding this from a user:

>I didn't realize I could star routes...still not sure why one would. I just filter out all the routes I don't care about.
>
>Perhaps a toast or snackbar notification explaining what exactly I just did ("Route 40 Starred" vs "Stop Starred") or a hint on the empty "Starred Stops" ("Not what you were expecting? Make sure you starred the stop and not the route!") would go a long ways here.

Note that the implementation of a "Starred Routes" list (https://github.com/OneBusAway/onebusaway-android/issues/354) would also likely help with this.

**Steps to reproduce:** 

Tap on a star next to a route

**Expected behavior:** 

Reinforce via UX that the user starred a route and not a stop

**Observed behavior:** 

Some users are confusing starred routes with stops

**Comment by amrhossamdev** [comment]
fixed
