### ISSUE TITLE
Won't build in Android Studio 3.0

### ISSUE THREAD

**Issue by nanodeath** [OneBusAway/onebusaway-android#783]
Trying to import the project for the first time. I'm getting this error:

> Error:(261, 0) Cannot set the value of read-only property 'outputFile' for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=agencyXAmazonDebug, filters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOutputImpl.

The line it's complaining about is [build.gradle L260](https://github.com/OneBusAway/onebusaway-android/blob/ede3eca30d174404e1f6abac6d52a8198b4c29a0/onebusaway-android/build.gradle#L260-L261).

It's preventing me from configuring Build Variants, since it's failing the entire Gradle sync.

**Comment by barbeau** [comment]
Thanks for reporting @nanodeath, I haven't tried Android Studio 3.0 with OBA Android yet.

Try taking a at look at https://stackoverflow.com/a/44265374/937715 - seems like that has some solutions for this pulled out of the [Android plugin 3.0 migration guide](https://developer.android.com/studio/preview/features/new-android-plugin-migration.html).

**Comment by nanodeath** [comment]
Ah, yeah that helped. I should have googled it first...

I'm now getting

> Failed to resolve: org.json:json:20141113

but I'm still looking into it. That migration guide is...fairly long.

**Comment by nanodeath** [comment]
Alternatively, if I downgrade the Gradle plugin back to 3.3 (instead of using 4, which Android Studio prompted me for), everything builds, but I see only the `agencyXAmazonDebug` Build Variant in the Build Variants section. There are a slew of `Warning:WARNING: Dependency org.json:json:20141113 is ignored for agencyXAmazonDebug as it may be conflicting with the internal version provided by Android.`-type warnings, though.

**Comment by barbeau** [comment]
IIRC I see `Warning:WARNING: Dependency org.json:json:20141113 is ignored for agencyXAmazonDebug as it may be conflicting with the internal version provided by Android` when building using current `master` branch with Android Studio 2.3.2.

**Comment by barbeau** [comment]
I think if only one build variant is showing up in Android Studio there is still a Gradle sync issue.

**Comment by barbeau** [comment]
WIP PR at https://github.com/OneBusAway/onebusaway-android/pull/835.
