### ISSUE TITLE
Add a preference to disable to GPS warning popup

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#8]
We can add a checkbox for the folks who really don't like this popup.

**Comment by bbodenmiller** [comment]
Which warning are we talking about here?

**Comment by barbeau** [comment]
It looks like this is a duplicate of https://github.com/OneBusAway/onebusaway-android/issues/697, so I'm going to close this issue in favor of https://github.com/OneBusAway/onebusaway-android/issues/697, which has more specific information.
