### ISSUE TITLE
Can't create shortcuts on Android 8.0 Oreo

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#816]
**Summary:** 

If you try to create a starred stop shortcut on an Android 8.0 Oreo device, OBA Android says that the shortcut was created but no shortcut icon appears.

This also applies to other app shortcuts too (Night light, etc.) - anything that uses `Intent.setAction(INSTALL_SHORTCUT)`.

Looks like Google changed the behavior on creating these shortcuts in Android 8.0 so this now fails silently.

https://developer.android.com/about/versions/oreo/android-8.0-changes.html#as says:

>The com.android.launcher.action.INSTALL_SHORTCUT broadcast no longer has any effect on your app, because it is now a private, implicit broadcast. Instead, you should create an app shortcut by using the [requestPinShortcut()](https://developer.android.com/reference/android/content/pm/ShortcutManager.html#requestPinShortcut(android.content.pm.ShortcutInfo, android.content.IntentSender)) method from the [ShortcutManager](https://developer.android.com/reference/android/content/pm/ShortcutManager.html) class.

See https://stackoverflow.com/questions/44744184/how-to-create-shortcuts-on-android-o-when-targetting-less-than-it for details.

**Steps to reproduce:** 

1. Create starred stop
1. Go to Starred Stops fragment
1. Long-press on stop and tap "Create shortcut on home screen"

**Expected behavior:** 

A shortcut to that stop should appear on the home screen

**Observed behavior:** 

Stop shortcut doesn't appear on home screen

**Device and Android version:** 

Samsung Galaxy S8+ w/ Android 8.0 (Samsung beta) and Nexus 5X w/ Android 8.0 (production release)

**Comment by Protocol-X** [comment]
Pages with webapps appear in your app drawer instead of homescreen, even know you chose homescreen

**Comment by barbeau** [comment]
@Protocol-X Could you please open a new issue with exact steps to reproduce, screenshots and your Android device make, model, and Android version?  This will let me troubleshoot the issue you're seeing.

**Comment by Protocol-X** [comment]
Hello,

I was just explaining. This is by design on oreo, not an issue.

**Comment by barbeau** [comment]
Ok, thanks.  Can you explain more what you mean by "pages with webapps"?  I'm still not sure I understand exactly what you're describing.  A screenshot would help.
