### ISSUE TITLE
Remove unused image resources

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#831]
**Summary:** 

We apparently still have unused image resources in the project, likely left over from v1.x.

These are stripped out during the release process so they don't add to the app size, but it would be good hygiene to remove these from the project completely.

Here's the console output during the release process that shows that some unused resources are being removed (reduced from 3480KB to 2949KB, or 15% reduction):

![image](https://user-images.githubusercontent.com/928045/34304382-8e5d6086-e707-11e7-920b-e89555c0f57c.png)

**Steps to reproduce:** 

1. Set up release builds (see [this link](https://github.com/OneBusAway/onebusaway-android#release-builds))
1. Run `gradlew assembleObaGoogleRelease -Dorg.gradle.daemon=false`

**Expected behavior:** 

All unused image resources should be removed from the project

**Observed behavior:** 

15% of resources in the project aren't being used

**Device and Android version:** 

N/A (seen during release build)

**Screenshots:** 

See above

**Comment by sjgllghr** [comment]
I'd be interested in looking into this if no one else is working on it. 

Do you only want to remove images (as opposed to strings or .xml files)?
