### ISSUE TITLE
Performance regression for map after updating to Gradle Plugin v3

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#844]
**Summary:** 

On a Samsung Galaxy S8+ I'm seeing a significant performance regression when scrolling the map after updated to the Android Gradle Plugin v3 in PR https://github.com/OneBusAway/onebusaway-android/pull/835 (commit at https://github.com/OneBusAway/onebusaway-android/commit/1ca2f1c23263db2bc579b05d243aefac013a177b).

When I scroll around the map around USF area in Tampa in v2.3.2, performance is unchanged from previous versions.

Using master branch at https://github.com/OneBusAway/onebusaway-android/commit/0fce5d6c9a27c07069876c9bf50b3f59669e91b5, when I scroll the map around USF area in Tampa I'm seeing significant slowdown and stuttering, and a lot of GC events and frame skipped messages, such as:

~~~
I/zygote64: NativeAllocBackground concurrent copying GC freed 101470(3MB) AllocSpace objects, 36(1992KB) LOS objects, 49% free, 8MB/17MB, paused 238us total 288.102ms
D/StopOverlay: Added 69 markers, total markers = 196
I/Choreographer: Skipped 65 frames!  The application may be doing too much work on its main thread.
~~~

I'm guessing this is related to using `VectorDrawableCompat.create()` instead of `ContextCompat.getDrawable()` for the bikeshare markers:

~~~
Drawable shape = VectorDrawableCompat.create(Application.get().getResources(), R.drawable.bike_marker_small, Application.get().getTheme());
~~~

... and/or adding `vectorDrawables.useSupportLibrary = true` to `build.gradle`:

~~~
android {
    compileSdkVersion 27
    buildToolsVersion "26.0.2"

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 21
        versionCode 86
        versionName "2.3.1"

        vectorDrawables.useSupportLibrary = true
    }
~~~

I recall seeing some warnings that adding `vectorDrawables.useSupportLibrary = true` may have performance penalties - I need to investigate and see what the options may be.

From quick testing I can't seem to reproduce this when looking at Puget Sound region so maybe it's related just to the bikeshare markers (and not stop markers).

**Steps to reproduce:** 

1. Run fresh install of `master` branch
1. Scroll map around USF area in Tampa

**Expected behavior:** 

Perform similarly to v2.3.2 - map scrolling should be smooth

**Observed behavior:** 

Scrolling is now stuttering a lot, with a lot of GC events.  When stuttering the entire UI is locked up.

**Device and Android version:** 

Samsung Galaxy S8+ w/ Android 8.0 beta

**Screenshots:** 

![image](https://user-images.githubusercontent.com/928045/35174696-541d0c80-fd3e-11e7-80b4-2827291e5f1e.png)

**Comment by barbeau** [comment]
@acrown-msft Would you mind trying the current master branch on your devices and see if you notice any regression in performance when panning the map vs. previous versions?

I can't seem to reproduce this anymore, and I'm starting to wonder if it was a bug with the Samsung Galaxy S8+ Oreo beta that I had installed at the time.  I've updated since then and can't seem to reproduce the slowdown on that device or a Nexus 5.

**Comment by barbeau** [comment]
The "Considerations for SVG and PSD files" section [here](https://developer.android.com/studio/write/vector-asset-studio.html#about) says:
>The initial loading of a vector drawable can cost more CPU cycles than the corresponding raster image. Afterward, memory use and performance are similar between the two. We recommend that you limit a vector image to a maximum of 200 x 200 dp; otherwise, it can take too long to draw.

If there is indeed a performance hit, it may be due to the many small bikeshare icons on the map - the Maps API v2 renderer may be loading these vector drawables many times in the background, and the cost of these extra CPU cycles may be what's choking performance.

There is really no reason for the small bikeshare icons to be defined by vectors - we can create them using normal Android XML resource drawable files, similar to how we're creating stop icons from `map_stop_icon.xml`.

**Comment by acrown-msft** [comment]
I see stuttering and can consistently get skipped frames when zooming in and out of USF such that the bike markers need to be redrawn.  I only see an occasional stutter when panning the map.  I tested with a Galaxy S6 edge+ and Nexus 7.

**Comment by barbeau** [comment]
@acrown-msft Thanks for checking!  If you unplug those devices from USB, reboot them, and then restart same version the app (from the icon, without USB cable plugged in), do you still see the same stuttering?

**Comment by acrown-msft** [comment]
I see some stuttering on the Nexus 7 but its hard for me to distinguish between network delay and dropped frames.

**Comment by barbeau** [comment]
New small bike share map icon (blue dots):

![image](https://user-images.githubusercontent.com/928045/35881094-b09f1d3c-0b4d-11e8-88b5-db8766886377.png)
