### ISSUE TITLE
Location FAB covers Google logo in left hand mode

### ISSUE THREAD

**Issue by m-yang** [OneBusAway/onebusaway-android#871]
**Summary:** 

In left hand mode, the Location FAB covers the Google logo. 

**Steps to reproduce:** 

Enable left hand mode in settings. 

**Expected behavior:** 

The Google logo should be completely visible. 

**Observed behavior:** 

See screenshot below. 

**Device and Android version:** 

App Version: 2.3.4
Android Version: 7.0 on Android Studio emulator

**Screenshots:** 

<img src="https://user-images.githubusercontent.com/19160743/39025707-a09dcd8c-43fd-11e8-912b-28b41f530674.png" width="218" height="384">

**Comment by barbeau** [comment]
Thanks @m-yang!

Originally mentioned in https://github.com/OneBusAway/onebusaway-android/pull/867#issuecomment-383114941.  Solution discussed on that thread is to move the Google logo to the opposite corner (lower right) in left hand mode.
