### ISSUE TITLE
"SPLC" is shown as "Splc" in stop names

### ISSUE THREAD

**Issue by Heidebritta** [OneBusAway/onebusaway-android#883]
**Summary:** 

Data displayed is different cases than how it is in GTFS - SPLC is displayed as Splc.  

From the client "It has come to our attention that SPLC with lowercase letters (Splc) is easily mistaken for a racial epithet, according to a Hispanic family"

**Steps to reproduce:** 

This was reported to my by a client and I don't have the app, so bear with me.  

1. Go to Puget Sound region
1. Search/select stop #755005.  See attached screenshot.

**Expected behavior:** 

I would expect to see the data as it is in the GTFS.  In the GTFS trips, the trip headsigns are, for example  “SPLC Parking via 70th”.  In stops.txt the stop is called "SPLC / SR 513".  When I look at the sign interface and the mobile app, I am also seeing SPLC. 
From trips.txt
route_id,service_id,trip_id,trip_headsign,direction_id,block_id,shape_id
863-16,SCH-1805-SCH-Weekday-60,542835-SCH-1805-SCH-Weekday-60,"Hospital via SPLC Parking",0,68791,8630001
863-16,SCH-1805-SCH-Weekday-60,542836-SCH-1805-SCH-Weekday-60,"SPLC Parking via 70th",1,68791,8630002

**Observed behavior:** 

* `SPLC` is displayed as `Splc`.
* `via` displayed as Via 
* `70th` displayed as `70Th`.

**EDIT** - on OBA Android, all of the above is handled correct, except that `Splc` is shown in stop names in the `ArrivalsListFragment`. See following comments

**Device and Android version:** 

unknown

**Screenshots:** 

Screenshot of the app with Splc

![android_splc](https://user-images.githubusercontent.com/30128060/40981250-7d2d75ee-68a8-11e8-9a1c-158da5e628cc.png)

Screenshot of signs with SPLC

![sign_splc](https://user-images.githubusercontent.com/30128060/40981256-81f3bebc-68a8-11e8-9026-8c0fbc64271a.png)

Screenshot of web with SPLC

![web_splc](https://user-images.githubusercontent.com/30128060/40981261-876779ba-68a8-11e8-9011-09052b4e6f0d.png)

**Comment by barbeau** [comment]
@Heidebritta Thanks for reporting this!  We should definitely get this fixed - capitalization in general is difficult to handle because some regions have all of their headsigns capitalized, and so the native apps do some text manipulation to make them easier to read. Obviously this can have unintended side-effects occasionally, and it looks like this is one of those times.

The above screenshot is from OBA iOS, so you'll need to report this at https://github.com/OneBusAway/onebusaway-iphone/issues.

Do you know if this happens on Android too?

**Comment by barbeau** [comment]
Ok, I was able to pull up this stop on OBA Android, and here is how it looks:

![image](https://user-images.githubusercontent.com/928045/40983048-ba637072-68ac-11e8-8df5-d20f42caaf0a.png)

It looks like `SPLC` and `via` are handled properly in the headsign, but it is being changed in the stop name.  I'll see if I can do a quick fix for this  - I was planning on doing a release today anyway, so I'll see if I can bundle this in.

**Comment by barbeau** [comment]
`70th` is being handled properly in both stop name and headsign:

![image](https://user-images.githubusercontent.com/928045/40983321-582cef40-68ad-11e8-9fe3-16ef49b46347.png)

**Comment by Heidebritta** [comment]
Hi Sean,

Thank you, I will report at -iphone ...I was told by a reliable source that
the screenshot was from an Andoid.

I appreciate the quick follow up.
-Heide.

**Comment by barbeau** [comment]
The fix for this issue is in v2.3.6, which is available in the beta channel for Google Play now:
https://github.com/OneBusAway/onebusaway-android/releases/tag/v2.3.6

I'll start rolling it out to production likely starting later this week if there are no reported issues.
