### ISSUE TITLE
Social "Popular" feed is empty

### ISSUE THREAD

**Issue by acrown-msft** [OneBusAway/onebusaway-android#889]
**Summary:** 

The "Popular" topics section of the navigation drawer is always empty.

**Steps to reproduce:** 

Open the popular topics feed from the navigation drawer.

**Expected behavior:** 

Display popular stops and routes.

**Observed behavior:** 

UI displays an empty feed.

Current solution will be to remove this item from the Navigation Drawer until an Embedded Social server-side fix is ready.

**Comment by barbeau** [comment]
A workaround for this issue was just merged in https://github.com/OneBusAway/onebusaway-android/pull/890, and I'm going to keep this issue open until we can re-add "Popular" at a later date.
