### ISSUE TITLE
HOW TO FIX IN FLASH. Your app currently targets API level 21 and must target at least API level 26 to ensure it is built on the latest APIs optimized for security and performance. Change your app's target API level to at least 26

### ISSUE THREAD

**Issue by dakflash** [OneBusAway/onebusaway-android#904]
Try to upload APK published by Adobe Flash CS6. But is rejected by Google play saying the error above. How would one using flash fix this? I heard you could edit something in the app XML file but I am unsure on what to add and or change in the file.
**Steps to reproduce:** 

Try to upload to Google play

**Expected behavior:** 

Upload properly like it did in the past

**Observed behavior:** 

The error above is what google gave me.

**Comment by barbeau** [comment]
@dakflash I'm not sure I understand your comment/question.  Is it related to the onebusaway-android project?

If your question is regarding OBA Android, then check out these issues:
* https://github.com/OneBusAway/onebusaway-android/issues/884
* https://github.com/OneBusAway/onebusaway-android/issues/330

If you have a more general question related to Adobe Flash (which isn't used in this project) then StackOverflow is a better place to ask it:
https://stackoverflow.com/
