### ISSUE TITLE
Add option for arrival reminders based on scheduled time

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#916]
**Summary:** 

From a user:

>Your app needs an option to notify about bussed arrival based in scheduled time and not just estimated time. Eight times now I have missed the bus because it is initially late when I am notified but the bus then makes up the time to arrive as scheduled. I have built in time to my reminders but today was an extreme. I bloodied both knees while trying to run to catch it.  The bus stop is .6 miles from my office so I need to plan ahead to catch it 20 mins is normally enough time to make up for the difference but today it was not.

The underlying issue here is the errors in arrival times, but for users that have to deal with this now we could add a checkbox when creating an arrival reminder "Use real-time information" that would default to checked, but could be unchecked by the user if needed.  So, if real-time isn't reliable, they could still get a reminder based on the schedule which would prevent them from missing the bus.

**Steps to reproduce:** 

1. Tap on an arrival time
1. Tap on "Set a reminder"

**Expected behavior:** 

Give me a way to base the alarm on schedule rather than real-time info

**Observed behavior:** 

All alarms are based on real-time info

**Device and Android version:** 

N/A

**Comment by barbeau** [comment]
I'm no longer involved in OBA development. Cc'ing @amrhossamdev and @aaronbrethorst for their opinions.

**Comment by yoyounik** [comment]
Thank you @barbeau for clarifying. I'll wait for @amrhossamdev  and @aaronbrethorst to gather their inputs.

**Comment by aaronbrethorst** [comment]
We're pursuing a different strategy for addressing this issue.
