### ISSUE TITLE
Spanish translation of "What's New"

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#922]
**Summary:** 

@themonki Would you be able to translate the new "What's new" string today (see below or master branch)?  You can either just comment on this issue or submit a pull request.  I'm trying to get a bug fix out quickly.

Thanks!

~~~
    <string name="main_help_whatsnew">&#8226;\u0020
        <b>Route filter now affects alerts</b>
        - When viewing alerts at a stop, alerts for hidden routes are now hidden.\n&#8226;\u0020
        <b>Bug fixes</b>
        - See http://bit.ly/oba-android-releases
    </string>
~~~

**Comment by themonki** [comment]
Sure, I will do on PR.
