### ISSUE TITLE
Logo Design: OneBusAway

### ISSUE THREAD

**Issue by baranpirincal** [OneBusAway/onebusaway-android#924]
Hey, I am graphic designer and my motivation is make my portfolio better by support open-source projects. I can re-design your logo if you interested. In my opinion we should do it.

I am waiting your comment about it. If you want to see my portfolio, I can send it. 

Have a nice day!

Best Regards
Baran Pirinçal

**Comment by barbeau** [comment]
@baranpirincal Thanks for the offer!  You're certainly welcome to take a shot at a logo re-design, although this would need to take place across all the OneBusAway apps/platforms, including iOS, Alexa, web, etc.  The OBA open-source project would also need to approve it - https://onebusaway.org/the-onebusaway-project/governance/.

I'm going to close this issue, and if you'd like to pursue this further please open an issue on the main OBA repo at https://github.com/OneBusAway/onebusaway.
