### ISSUE TITLE
Data feed issue with (WA) King County C express bus routes

### ISSUE THREAD

**Issue by banshee** [OneBusAway/onebusaway-android#928]
**Summary:** 

Buses on the C line (and other express lines) aren't getting actual realtime arrival times, just scheduled.  It's not 100%; you occasionally do display realtime data.

**Steps to reproduce:** 

Go to the stop labelled 1_19830 in Seattle (at least that's the toast that pops up if I tap on the stop with a build from master).  You'll see most (it's all right now) of the C arrivals in grey.  If you go to the King County Metro web page, they show data for those buses (https://tripplanner.kingcounty.gov/hiwire?.a=iNextBusResults&StopId=19830).

**Expected behavior:** 

See the same bus data in the app as on the website (I'm assuming they come from the same master source).

What did you expect the app to do?

**Device and Android version:** 

A Nexus 5X running the latest production version from the store (sorry, it's my wife's phone, don't have the release number in front of me).

Tried building this release and running on a galaxy S7, same result:

```
commit 212dbac273f620681f4b5897b81145a5a5cc1637 (HEAD -> master, origin/master, origin/HEAD)
Author: Pokechu22 <pokechu022@gmail.com>
Date:   Tue Oct 16 09:29:59 2018 -0700

    Fix #548 - Improve Trip Status vehicle icon (#926)

```

**Comment by banshee** [comment]
Also tried building a slightly older release (```git checkout v2.3.7```) and it has the same issue running on a simulator.  Wanted to see if it was a recent code change causing the problem; I don't think that's the case.

**Comment by barbeau** [comment]
@banshee Thanks for the detailed report!

Could you confirm you see the same behavior on the OBA website as you do in the OBA Android app?

http://pugetsound.onebusaway.org/where/standard/stop.action?id=1_19830

Sounds like this is a data issue for KCM, in that they aren't exporting it correctly.  In that case you'd need to report the above to Open_Transit_Data@soundtransit.org.

**Comment by banshee** [comment]
It's weird - the OBA web page does have one arrival time given for realtime, but the rest are scheduled.  Metro has all of them.

![image](https://user-images.githubusercontent.com/14540/47944522-54556a00-deb9-11e8-853f-c6d2f30c8ce2.png)

![image](https://user-images.githubusercontent.com/14540/47944530-5a4b4b00-deb9-11e8-8b79-3e60bfdb9c78.png)

**Comment by banshee** [comment]
And I sent mail to Open_Transit_Data@soundtransit.org pointing them here.

**Comment by barbeau** [comment]
@banshee Thanks!  I'm going to close this issue for general record-keeping because this issue isn't specific to the OBA Android app, but it will remain here for Sound Transit to review to see if they can resolve the data problem.
