### ISSUE TITLE
Plan a Trip - Light Rail

### ISSUE THREAD

**Issue by bflyth** [OneBusAway/onebusaway-android#942]
**Summary:** 

Plan A Trip (beta) is not offering all services.

**Steps to reproduce:** 

Plan a trip from any light rail station or nearby location to another light rail station or nearby location.

**Expected behavior:** 

Trip planner should offer light rail, times, and possible bus transfer.

**Observed behavior:** 

Trip planner only offered bus lines, which would take far longer especially with transfers.

**Device and Android version:** 

Huawei Mate SE
Android 8.0.0
Google Play 12.7.23-all
1BA 2.3.11(96)

**Screenshots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by barbeau** [comment]
Thanks for the feedback @bflyth!  Yes, unfortunately I don't have any control over the routes the trip planner returns - that's managed by Sound Transit.  So, the best way to submit this type of feedback is from within the OBA Android app and "Report trip plan problem", which sends the trip details (including planned URL) to otp-pugetsound@onebusaway.org.  I'd also suggest copying Open_Transit_Data@soundtransit.org too.

**Comment by bflyth** [comment]
Hey Sean,
I think I might have done that as well as opening the ticket on GitHub. Just tested and ran a couple scenarios, and it appears that SoundTransit already resolved the issue. Light Rail is appearing in Trip Planner searches now.
Cheers! And thank you for the great app.


________________________________

**Comment by barbeau** [comment]
Gald to hear it!
