### ISSUE TITLE
Appearance of "Unable to get your location..." message before user grants permission

### ISSUE THREAD

**Issue by paulnabanita1** [OneBusAway/onebusaway-android#945]
**Summary:**
When performing a fresh install of the OneBusAway app (first-time installation or uninstalling the app and reinstalling it), the "Unable to get your location.  Please give app location permissions via system settings." message appears even before the user can grant runtime permission to allow the app to access the device's location.

**Steps to reproduce:**
1. Uninstall(if previously installed) the existing OneBusAway app.
2. Perform fresh installation.

**Expected behavior:**
The app should display the "Unable to get your location.  Please give app location permissions via system settings." message after the user taps on "Deny" for location access permission.

**Observed behavior:**
The message is appearing before the user accepts/denies location access permission to the device.
However, the user can still tap on "Allow" to allow the app to access the device's location and all the functionalities of the app work as expected.

**Device and Android version:**
The error was observed in a OnePlus 6 device running on OxygenOs version 9.0.2 (customized Android 9, API 28).
![error](https://user-images.githubusercontent.com/42182508/49830504-571c6800-fd5f-11e8-8367-ff0bff3d9484.JPG)

**Comment by barbeau** [comment]
@paulnabanita1 Thanks for opening an issue on this!  That's really bizarre, I'm not sure why it's happening.  It must be a different implementation of the map for whatever OnePlus uses to replace Google Play Services that behaves a little differently from the normal Google official Play Services version.  I'm going to close this issue as "Won't fix" as it doesn't affect the use of the app and is likely only visible on OnePlus devices, but I'm glad we have the issue documented so we can return to it in the future if needed.

**Comment by paulnabanita1** [comment]
@barbeau No problem!
