### ISSUE TITLE
Arrival listing hidden by message

### ISSUE THREAD

**Issue by jerryhall** [OneBusAway/onebusaway-android#966]
The listing of arriving buses or trains beyond the first is blocked by a small banner message with a yellow triangle and a message. I cannot clear it, and therefore cannot see the second listed arrival which is 90% blocked. When clicked I'm taken into a message interface where I'm invited to post a review. Thanks!  (San Diego)

I can send image if given an address.

**Comment by barbeau** [comment]
@jerryhall trying tapping on the alert and then choosing "hide". If that doesn't work please email me at android-app@onebusaway.org! Thanks!
