### ISSUE TITLE
Ghost notification "Updating reminders"

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#977]
**Summary:** 

Reported on Twitter at:
https://twitter.com/MoeFwacky/status/1118593631659495424

>For what feels like months now, I've been getting ghost notifications on my phone. I finally tracked down the cause. OneBusAway "updating reminders." I don't even take the bus, I just kept the app for when I might occasionally need to. I'm relieved, but also so angry about this.... I discovered that it was the cause of the ghost vibrations that had been interrupting me since the Android 8 update...they only seemed to happen at work, right next to a transit center.

Another user replied saying:

>The update about the tunnels was also causing some ghost notifications on this side of the water too. It was quite sometime after the reroutes before I actually got to see it.

I'm not sure what's causing this, but a guess is that the rescheduling Service isn't being canceled or rescheduled correctly in certain conditions, and the Service that reschedules them is repeatedly triggering, perhaps with higher priority than it should have, which could cause vibration and alarm tone.  Alternately, it could be a data problem, with trip_ids changing as a result of the massive Puget Sound data update with the tunnel closure and updates being triggered somewhat randomly because of this.

**EDIT** More info from user - https://twitter.com/gatzby_/status/1120794385300377601:

>No Reminders here. Moto x4, provider: Google Fi (also the software variant), Android 9 with March 1 security update

**Steps to reproduce:** 

Unknown

**Expected behavior:** 

Only provide notifications when the user schedule

**Observed behavior:** 

User is getting "ghost notifications"

**Device and Android version:** 

Moto x4, provider: Google Fi (also the software variant), Android 9 with March 1 security update

**Comment by barbeau** [comment]
From another user:

>My phone just randomly started vibrating it odd times, like I was getting notifications. But when I checked, I had no new notifications. After googling this issue, people recommended getting a notification log and I saw that it was OneBusAway sending notifications. I didn't take a screenshot so I don't know what they were for, but when I disabled notifications from your app, the phantom vibrations stopped. Here's my info:
>
>App Version: 2.4.4
Model: XT1635-01
OS Version: 8.0.0 / 26
Google Play Services App: 16.0.91 (040308-244116403)
Google Play Services Library: 12451000
Region/API: Puget Sound (selected automatically)

**Comment by barbeau** [comment]
Another user report - the common thread so far seems to be that these are all Motorola devices:

>Recently, I started getting notifications that say "Updating Your Reminders" before they automatically clear themselves, which also cause my phone to vibrate. I don't have any set reminders and haven't even used the app to make trips for a few months (for obvious reasons), so this strikes me as unnecessary.
>
I'm not really sure why there's a notification for this, but at a minimum it shouldn't vibrate my phone or there should be an option to disable it. Gmail has a similar kind of notification for syncing, which does not cause my phone to vibrate.
>
>App Version: 2.7.4
Model: Moto Z3 Play
OS Version: 9 / 28
Google Play Services App: 20.21.17 (100408-316502805)
Google Play Services Library: 12451000
Region/API: Puget Sound (selected automatically)

**Comment by jrtom** [comment]
I've been noticing this on my non-Motorola device for the past few months, at least.  I also don't have any set reminders, and also haven't used the app recently.

It's issuing ~73 notifications per day according to the app info, which seems suspiciously close to one every 20 minutes.

App version: 2.7.4
Phone: Pixel 3a XL
OS: 10, 11 (recently upgraded, had no noticeable effect)
Region: Puget Sound

Please LMK if further information would be useful.

**Comment by barbeau** [comment]
@jrtom Ugh, I wish I had more information to hunt down why this is happening. So this was happening on 10 prior to the update to 11, right? If you uninstall and reinstall, does it keep happening (you can backup favorites via Settings first)?

**Comment by barbeau** [comment]
Reported by another user:

>App Version: 2.8.0
Model: Pixel 5
OS Version: 11 / 30
Google Play Services App: 21.21.16 (150400-378233385)
Google Play Services Library: 12451000
Region/API: Puget Sound (selected automatically)
>
>Constantly waking my phone up for "updating reminders" notifications. Cannot seem to stop this from happening.

**Comment by barbeau** [comment]
Reported by another user:

>Recently, I've started getting brief notifications on my Note 20 that OneBusAway is checking - apparently - for reminders. The OBA notification appears on the lock screen for just a few seconds then disappears.  At times, this happens every minute. Why is this happening when I have no reminders set (verified in the My Reminders zero of three app)? I assume this is taking up resources, and it even affects my phone volume; if I have music playing for instance, the volume dips for a second when the notification appears.  I've already tried deleting & reinstalling the app. How do i fix this?

**Comment by barbeau** [comment]
It's possible that this is related to/caused by https://github.com/OneBusAway/onebusaway-android/issues/1076.

**Comment by amrhossamdev** [comment]
Fixed: #1258
