### ISSUE TITLE
Alerts Without End Time Do Not Show in App

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-android#990]
**Summary:** 
If an alert is active without an end time, the alert is not shown in the app.

**Steps to reproduce:** 

Add an alert without an end period.  We add the alert to a 3rd-party system which then creates a GTFS-RT alert feed that is ingested by OBA.  

**Expected behavior:** 

Show the alert in the app.

**Observed behavior:** 

The alert doesn't show.

I have attached two json API responses.  One with no end time and one with end time.  The one with an end time shows an actual time value. The one without an end time lists "0" as the end time of the active period.

![alert_differences](https://user-images.githubusercontent.com/5028299/60218192-75414580-9823-11e9-9c92-6b5b35b434a4.png)

[MTS_arrivals_and_departures_for_stop_no_end_time.json.txt](https://github.com/OneBusAway/onebusaway-android/files/3332068/MTS_arrivals_and_departures_for_stop_no_end_time.json.txt)
[MTS_arrivals_and_departures_for_stop_with_end_time.json.txt](https://github.com/OneBusAway/onebusaway-android/files/3332069/MTS_arrivals_and_departures_for_stop_with_end_time.json.txt)

**Comment by barbeau** [comment]
Thanks @devinbraun!  Looks like the app is interpreting `0` as the end time, which is always less than the actual end time, and therefore the app never thinks the alert is in the active time window.  This should be a quick fix.

**Comment by barbeau** [comment]
@devinbraun This will be fixed in the next release.

**Comment by barbeau** [comment]
BTW, thanks for the example attached responses - it makes the fix go so much faster :clap:

**Comment by barbeau** [comment]
This is fixed in v2.5.3 that I'm rolling out to beta testing now via Google Play:
https://github.com/OneBusAway/onebusaway-android/releases/tag/v2.5.3
