### ISSUE TITLE
Starred stops are not saved

### ISSUE THREAD

**Issue by israteneda** [OneBusAway/onebusaway-android#994]
**Summary:** 

When I star a stop on the arrivals screen by tapping on the star this stop is not saved in starred stops.

**Steps to reproduce:** 

Tapping on the star next to stop name in OneBusAway app and Agency Y

**Expected behavior:** 

List the stops on the starred stops

**Observed behavior:** 

The starred stops did not list in the starred stops page

**Device and Android version:** 

Try with Samsung A5 from the manufacturer ROM and Google Play Services 17.7.85 version, Android Version 7.0
Also in an Emulator Pixel 2 XL API 28 Android 9.0 and Google Play Services 16.0.89 version

**Screenshots:** 

![Starred Stops](https://media.giphy.com/media/iFVWjSRwEQe69xvLK5/giphy.gif)

**Comment by barbeau** [comment]
@israteneda Please be sure to tap on the star next to the stop name, not the route name (see below screenshot). Right now tapping on the star next to the route name (or via the menu after tapping on the arrival time) stars the route, and pins it to the top of the sliding panel. This allows you to quickly tap on stops on the map and see the arrival time for routes you care about. I plan to add a separate “Starred routes” list, although I don’t have a specific timeline for this yet. You can follow progress at https://github.com/OneBusAway/onebusaway-android/issues/354.

![image](https://user-images.githubusercontent.com/928045/60978904-d37c2700-a2ff-11e9-8bfe-9a315b42bc47.png)

**Comment by israteneda** [comment]
Thank you for your answer and the effort put in this app, sorry for the mistake.
